"""好力 GO 设备单据 — 编码规则代码（与 core.config.code_rule_pages 中 rule_code 一致）。"""

HAOLIGO_EQUIPMENT_SPOT_CHECK_NO = "HAOLIGO_EQUIPMENT_SPOT_CHECK_NO"
HAOLIGO_EQUIPMENT_ROUTE_PATROL_NO = "HAOLIGO_EQUIPMENT_ROUTE_PATROL_NO"
HAOLIGO_EQUIPMENT_OUTPUT_RECORD_NO = "HAOLIGO_EQUIPMENT_OUTPUT_RECORD_NO"

HAOLIGO_EQUIPMENT_UPKEEP_SHEET_NO = "HAOLIGO_EQUIPMENT_UPKEEP_SHEET_NO"
HAOLIGO_EQUIPMENT_UPKEEP_COMPLETE_SHEET_NO = "HAOLIGO_EQUIPMENT_UPKEEP_COMPLETE_SHEET_NO"
