"""好力 GO — 设备验收单工作流状态。"""

WORKFLOW_DRAFT = "draft"
WORKFLOW_COMMISSIONING = "commissioning"
WORKFLOW_PENDING_TRIAL = "pending_trial"
WORKFLOW_TRIAL_RECORDING = "trial_recording"
WORKFLOW_ACCEPTED = "accepted"
WORKFLOW_CLOSED = "closed"

WORKFLOW_VALUES = frozenset(
    {
        WORKFLOW_DRAFT,
        WORKFLOW_COMMISSIONING,
        WORKFLOW_PENDING_TRIAL,
        WORKFLOW_TRIAL_RECORDING,
        WORKFLOW_ACCEPTED,
        WORKFLOW_CLOSED,
    }
)

RESULT_PASS = "合格"
RESULT_FAIL = "不合格"
RESULT_VALUES = frozenset({RESULT_PASS, RESULT_FAIL})

LEDGER_ACTION_NONE = "none"
LEDGER_ACTION_CREATED = "created"
LEDGER_ACTION_LINKED = "linked"
LEDGER_ACTION_VALUES = frozenset({LEDGER_ACTION_NONE, LEDGER_ACTION_CREATED, LEDGER_ACTION_LINKED})
