"""好力 GO 财务 — 付款方式常量。"""

FINANCE_PAYMENT_METHOD_BANK = "银行转账"
FINANCE_PAYMENT_METHOD_ACCEPTANCE = "承兑汇票"
FINANCE_PAYMENT_METHOD_CASH = "现金"
FINANCE_PAYMENT_METHOD_CHECK = "支票"
FINANCE_PAYMENT_METHOD_OTHER = "其他"
FINANCE_PAYMENT_METHODS = (
    FINANCE_PAYMENT_METHOD_BANK,
    FINANCE_PAYMENT_METHOD_ACCEPTANCE,
    FINANCE_PAYMENT_METHOD_CASH,
    FINANCE_PAYMENT_METHOD_CHECK,
    FINANCE_PAYMENT_METHOD_OTHER,
)
