"""好力 GO 财务 — 材料供应商单价常量。"""

FINANCE_PRICE_TYPE_TAX_INCLUSIVE = "含税"
FINANCE_PRICE_TYPE_TAX_EXCLUSIVE = "不含税"
FINANCE_PRICE_TYPES = (FINANCE_PRICE_TYPE_TAX_INCLUSIVE, FINANCE_PRICE_TYPE_TAX_EXCLUSIVE)

FINANCE_PRICE_CHANGE_SOURCE_MANUAL = "手工维护"
FINANCE_PRICE_CHANGE_SOURCE_INVOICE_VERIFY = "验票改价"
FINANCE_PRICE_CHANGE_SOURCE_QUICK_ADD = "验票快速添加"
FINANCE_PRICE_CHANGE_SOURCE_IMPORT = "批量导入"
