"""好力 GO 财务 — 发票与验收单状态常量。"""

FINANCE_INVOICE_STATUS_REGISTERED = "已登记"
# 兼容旧常量名（合并验收等仍用此状态表示可操作发票）
FINANCE_INVOICE_STATUS_PENDING = FINANCE_INVOICE_STATUS_REGISTERED
FINANCE_INVOICE_STATUS_ACCEPTED = "已验收"
FINANCE_INVOICE_STATUS_REJECTED = "已拒收"
FINANCE_INVOICE_STATUSES = (
    FINANCE_INVOICE_STATUS_REGISTERED,
    FINANCE_INVOICE_STATUS_ACCEPTED,
    FINANCE_INVOICE_STATUS_REJECTED,
)

FINANCE_INVOICE_LINE_STATUS_MATCH = "一致"
FINANCE_INVOICE_LINE_STATUS_NEED_PRICE_CHANGE = "差异"
FINANCE_INVOICE_LINE_STATUS_MISSING_PRICE = "未登记"
FINANCE_INVOICE_LINE_STATUS_REJECTED = "已拒收"
FINANCE_INVOICE_LINE_STATUSES = (
    FINANCE_INVOICE_LINE_STATUS_MATCH,
    FINANCE_INVOICE_LINE_STATUS_NEED_PRICE_CHANGE,
    FINANCE_INVOICE_LINE_STATUS_MISSING_PRICE,
    FINANCE_INVOICE_LINE_STATUS_REJECTED,
)

FINANCE_ACCEPTANCE_STATUS_DRAFT = "草稿"
FINANCE_ACCEPTANCE_STATUS_CONFIRMED = "已确认"
FINANCE_ACCEPTANCE_STATUS_REJECTED = "已拒收"
FINANCE_ACCEPTANCE_STATUSES = (
    FINANCE_ACCEPTANCE_STATUS_DRAFT,
    FINANCE_ACCEPTANCE_STATUS_CONFIRMED,
    FINANCE_ACCEPTANCE_STATUS_REJECTED,
)
