"""好力 GO — 消息模板代码（与 core_message_templates.code 对应）。"""

HAOLIGO_EQUIPMENT_SPOT_CHECK_REPORT = "HAOLIGO_EQUIPMENT_SPOT_CHECK_REPORT"
HAOLIGO_EQUIPMENT_ROUTE_PATROL_REPORT = "HAOLIGO_EQUIPMENT_ROUTE_PATROL_REPORT"
HAOLIGO_PATROL_ISSUE_REGISTER_REPORT = "HAOLIGO_PATROL_ISSUE_REGISTER_REPORT"
