"""试模不合格 — 处理方式"""

TRIAL_FAILURE_HANDLING_PENDING = "待处理"
TRIAL_FAILURE_HANDLING_REPAIR = "立即送修"
TRIAL_FAILURE_HANDLING_DISPATCHED = "已发出"
TRIAL_FAILURE_HANDLING_RECALLED = "已收回"

# 表单可选
TRIAL_FAILURE_HANDLING_FORM_VALUES = (
    TRIAL_FAILURE_HANDLING_PENDING,
    TRIAL_FAILURE_HANDLING_REPAIR,
)

TRIAL_FAILURE_HANDLING_TERMINAL_VALUES = (
    TRIAL_FAILURE_HANDLING_DISPATCHED,
    TRIAL_FAILURE_HANDLING_RECALLED,
)

TRIAL_FAILURE_HANDLING_ALL_VALUES = (
    TRIAL_FAILURE_HANDLING_PENDING,
    TRIAL_FAILURE_HANDLING_REPAIR,
    *TRIAL_FAILURE_HANDLING_TERMINAL_VALUES,
)
