"""试模单 — 试模 / 试产两阶段流程状态。"""

WORKFLOW_PHASE_TRIAL = "试模"
WORKFLOW_PHASE_TRIAL_PASS_PENDING_PRODUCTION = "试模合格待试产"
WORKFLOW_PHASE_CLOSED = "已结案"

WORKFLOW_PHASE_ALL_VALUES = (
    WORKFLOW_PHASE_TRIAL,
    WORKFLOW_PHASE_TRIAL_PASS_PENDING_PRODUCTION,
    WORKFLOW_PHASE_CLOSED,
)
