"""试模不合格 — 处理方式"""

TRIAL_FAILURE_HANDLING_PENDING = "待处理"
TRIAL_FAILURE_HANDLING_REPAIR = "立即送修"
TRIAL_FAILURE_HANDLING_DISPATCHED = "已发出"
TRIAL_FAILURE_HANDLING_ADJUSTMENT_DONE = "调整完成"
TRIAL_FAILURE_HANDLING_RECALLED = "已收回"

# 表单可选
TRIAL_FAILURE_HANDLING_FORM_VALUES = (
    TRIAL_FAILURE_HANDLING_PENDING,
    TRIAL_FAILURE_HANDLING_REPAIR,
)

TRIAL_FAILURE_HANDLING_TERMINAL_VALUES = (
    TRIAL_FAILURE_HANDLING_DISPATCHED,
    TRIAL_FAILURE_HANDLING_ADJUSTMENT_DONE,
    TRIAL_FAILURE_HANDLING_RECALLED,
)

TRIAL_FAILURE_HANDLING_ALL_VALUES = (
    TRIAL_FAILURE_HANDLING_PENDING,
    TRIAL_FAILURE_HANDLING_REPAIR,
    *TRIAL_FAILURE_HANDLING_TERMINAL_VALUES,
)

# 外协侧可操作「调整完成」的前置状态
TRIAL_FAILURE_HANDLING_VENDOR_ADJUSTABLE = (
    TRIAL_FAILURE_HANDLING_REPAIR,
    TRIAL_FAILURE_HANDLING_DISPATCHED,
)

# 审核通过后尚未「确认收回」的处理中状态（流程不应结案）
TRIAL_FAILURE_HANDLING_IN_PROGRESS = (
    TRIAL_FAILURE_HANDLING_PENDING,
    TRIAL_FAILURE_HANDLING_REPAIR,
    TRIAL_FAILURE_HANDLING_DISPATCHED,
    TRIAL_FAILURE_HANDLING_ADJUSTMENT_DONE,
)
