"""好力 GO 模具类单据 — 与 core.config.code_rule_pages 中 rule_code 一致。"""

HAOLIGO_MOLD_TRIAL_SHEET_NO = "HAOLIGO_MOLD_TRIAL_SHEET_NO"
HAOLIGO_MOLD_BORROW_SHEET_NO = "HAOLIGO_MOLD_BORROW_SHEET_NO"
HAOLIGO_MOLD_RETURN_SHEET_NO = "HAOLIGO_MOLD_RETURN_SHEET_NO"
# 厂内维保：维修 / 保养各用独立规则与单号前缀（WX / BY）
HAOLIGO_MOLD_MAINTENANCE_REPAIR_SHEET_NO = "HAOLIGO_MOLD_MAINTENANCE_REPAIR_SHEET_NO"
HAOLIGO_MOLD_MAINTENANCE_UPKEEP_SHEET_NO = "HAOLIGO_MOLD_MAINTENANCE_UPKEEP_SHEET_NO"
HAOLIGO_MOLD_MAINTENANCE_COMPLETE_SHEET_NO = "HAOLIGO_MOLD_MAINTENANCE_COMPLETE_SHEET_NO"
HAOLIGO_MOLD_OUTSOURCE_MAINTENANCE_SHEET_NO = "HAOLIGO_MOLD_OUTSOURCE_MAINTENANCE_SHEET_NO"
HAOLIGO_MOLD_OUTSOURCE_MAINTENANCE_COMPLETE_SHEET_NO = "HAOLIGO_MOLD_OUTSOURCE_MAINTENANCE_COMPLETE_SHEET_NO"
