/**
 * 工序表单 Schema 配置
 */

import type { FieldConfig } from './form-schemas';

export const operationFormSchema: FieldConfig[] = [
  {
    name: 'code',
    type: 'text',
    labelKey: 'field.operation.code',
    placeholderKey: 'field.operation.codePlaceholder',
    required: true,
    colSpan: 12,
    rules: [{ required: true, messageKey: 'field.operation.codeRequired' }],
    fieldProps: { style: { textTransform: 'uppercase' } },
  },
  {
    name: 'name',
    type: 'text',
    labelKey: 'field.operation.name',
    placeholderKey: 'field.operation.namePlaceholder',
    required: true,
    colSpan: 12,
    rules: [{ required: true, messageKey: 'field.operation.nameRequired' }],
  },
  { type: 'slot', name: '__inspectionMode__', slotKey: 'inspectionMode', colSpan: 12 },
  {
    name: 'defaultPersonnelConfigs',
    type: 'select',
    labelKey: 'field.operation.defaultPersonnelConfigs',
    placeholderKey: 'field.operation.defaultPersonnelConfigsPlaceholder',
    colSpan: 12,
    mode: 'multiple',
    fieldProps: { allowClear: true },
  },
  { type: 'slot', name: '__inspectionDetail__', slotKey: 'inspectionDetail', colSpan: 24 },
  {
    name: 'defaultWorkshopIds',
    type: 'select',
    labelKey: 'field.operation.defaultWorkshopIds',
    placeholderKey: 'field.operation.defaultWorkshopIdsPlaceholder',
    colSpan: 12,
    mode: 'multiple',
    fieldProps: { allowClear: true },
  },
  {
    name: 'defaultResourceConfigs',
    type: 'select',
    labelKey: 'field.operation.defaultResourceConfigs',
    placeholderKey: 'field.operation.defaultResourceConfigsPlaceholder',
    colSpan: 12,
    mode: 'multiple',
    fieldProps: { allowClear: true },
  },
  {
    name: 'defaultEquipmentIds',
    type: 'select',
    labelKey: 'field.operation.defaultEquipmentIds',
    placeholderKey: 'field.operation.defaultEquipmentIdsPlaceholder',
    colSpan: 12,
    mode: 'multiple',
    fieldProps: { allowClear: true },
  },
  {
    name: 'reportingType',
    type: 'select',
    labelKey: 'field.operation.reportingType',
    placeholderKey: 'field.operation.reportingTypePlaceholder',
    required: true,
    colSpan: 12,
    rules: [{ required: true, messageKey: 'field.operation.reportingTypeRequired' }],
    extraKey: 'field.operation.reportingTypeExtra',
    extraAsTooltip: true,
    options: [
      { labelKey: 'field.operation.reportingTypeQuantity', value: 'quantity' },
      { labelKey: 'field.operation.reportingTypeStatus', value: 'status' },
    ],
  },
  {
    name: 'overReportMode',
    type: 'select',
    labelKey: 'field.operation.overReportMode',
    colSpan: 12,
    options: [
      { labelKey: 'field.operation.overReportModeNone', value: 'none' },
      { labelKey: 'field.operation.overReportModeFixed', value: 'fixed' },
      { labelKey: 'field.operation.overReportModePercent', value: 'percent' },
    ],
  },
  {
    name: 'overReportValue',
    type: 'number',
    labelKey: 'field.operation.overReportValue',
    placeholderKey: 'field.operation.overReportValuePlaceholder',
    colSpan: 12,
    fieldProps: { min: 0, precision: 4, style: { width: '100%' } },
    extraKey: 'field.operation.overReportValueExtra',
    extraAsTooltip: true,
  },
  { type: 'slot', name: '__customFields__', slotKey: 'customFields', colSpan: 24 },
  {
    name: 'description',
    type: 'textarea',
    labelKey: 'field.operation.description',
    colSpan: 24,
    fieldProps: { rows: 2, maxLength: 500 },
  },
  {
    name: 'isActive',
    type: 'switch',
    labelKey: 'field.operation.isActive',
    colSpan: 12,
  },
];
