#!/usr/bin/env python3
"""Batch 3 rich document help — kuaizhizao, equipment, kuaicaiwu."""
from __future__ import annotations


def _detail_table_doc(
    title: str,
    p1: str,
    *,
    p2: str | None = None,
    b1: str | None = None,
    b2: str | None = None,
    b3: str | None = None,
    b4: str | None = None,
    workflow: tuple[str, str, str, str, str, str] | None = None,
    pull_hint: str | None = None,
    push_items: tuple[str, ...] = (),
    push_alert: str | None = None,
    layout_p1: str | None = None,
    layout_b2: str | None = None,
    search_b2: str | None = None,
    entity: str | None = None,
    audit_enabled: bool = True,
    hub_note: str | None = None,
) -> dict[str, str]:
    ent = entity or title
    p2_text = p2 or f"本页面向业务操作人员：可在表头视图批量处理，在明细视图按行项目核对数量与状态。"
    wf = workflow or (
        f"新建{title}：空白新建或从上游单据取单带入头行。",
        f"维护行项目：确认物料、数量、仓库等必填项，保存草稿或提交审核。",
        "审核通过：单据进入执行态，可进行下推或过账类操作（若适用）。",
        "执行：按业务流程完成收货、发运、检验或财务处理。",
        "异常处理：驳回、撤回或走变更/冲销通道（若组织启用）。",
        "关单：业务完成后关单，冻结后续下推。",
    )
    push_b = list(push_items) + [
        "下推前请确认单据已审核、目标模块已启用且您具备对应权限。",
        "已存在下游单据时，可推数量会扣减已执行部分。",
        "部分下推仅在 capability 允许时出现，置灰时悬停查看原因。",
        "具体可下推类型以工具栏与行内菜单实际展示为准。",
    ]
    while len(push_b) < 8:
        push_b.append("具体可下推类型以工具栏与行内菜单实际展示为准。")
    push_b = push_b[:8]

    return {
        "overview.label": "1. 概述",
        "overview.title": "1. 概述",
        "overview.p1": p1,
        "overview.p2": p2_text,
        "overview.b1": b1 or f"记录{ent}业务数据，作为下游流程的依据。",
        "overview.b2": b2 or "支持表头/明细视图切换，满足不同岗位核对习惯。",
        "overview.b3": b3 or "配合指标卡与状态列快速发现待处理与异常单据。",
        "overview.b4": b4 or ("支持从上游业务单据取单，减少重复录入。" if pull_hint else "工具栏提供新建、批量与导入导出（以权限为准）。"),
        "workflow.label": "2. 典型业务流程",
        "workflow.title": "2. 典型业务流程",
        "workflow.p1": "以下为常见路径，具体节点是否启用取决于组织配置与权限。",
        "workflow.s1": wf[0],
        "workflow.s2": wf[1],
        "workflow.s3": wf[2],
        "workflow.s4": wf[3],
        "workflow.s5": wf[4],
        "workflow.s6": wf[5],
        "layout.label": "3. 页面布局",
        "layout.title": "3. 页面布局",
        "layout.p1": layout_p1 or "页面自上而下分为指标区（若有）、工具栏与列表区；右上角可切换表头/明细/帮助视图。",
        "layout.b1": "指标卡：待审核、逾期、待执行等；部分卡片可点击自动带入筛选。" if audit_enabled else "指标卡：待处理、逾期等快照（若有）。",
        "layout.b2": layout_b2 or "工具栏：新建/取单、下推（需选中单条）、批量审核、打印、导入导出等。",
        "layout.b3": "列表列：单号叠列伙伴/物料、进度与右侧固定状态；行操作提供查看、编辑、审核等。",
        "layout.b4": hub_note or "交期或到期类高亮以页面实际配置为准。",
        "search.label": "4. 查询与筛选",
        "search.title": "4. 查询与筛选",
        "search.p1": "表头视图与明细视图共用同一套筛选条件，切换视图不会丢失已填条件。",
        "search.b1": "关键词：模糊匹配单号、编码、名称等主字段。",
        "search.b2": search_b2 or "伙伴/仓库/部门：按业务维度下拉筛选（若已配置）。",
        "search.b3": "业务日期范围：按单据日期或计划日期过滤。",
        "search.b4": "生命周期/状态：筛选草稿、待审核、执行中、已关单等。",
        "search.b5": "高级搜索：展开更多条件（含自定义字段，若已配置）。",
        "search.b6": "点击指标卡：快速跳转到对应状态集合。",
        "guide.label": "5. 操作指南",
        "create.label": "5.1 新建与取单",
        "create.title": "5.1 新建与取单",
        "create.p1": pull_hint or f"推荐优先使用取单或复制类似{ent}，保证与上游数据一致。",
        "create.s1": "点击新建旁下拉，选择空白新建或取单入口（若提供）。",
        "create.s2": "在取单弹窗中筛选来源单据行，确认带入头行信息。",
        "create.s3": "在表单中补全仓库、数量、日期等必填项，检查行单位与数量。",
        "create.s4": "保存草稿供后续修改，或提交审核进入待审队列。",
        "create.b1": f"空白新建：适用于无上游单据的零星{ent}。",
        "create.b2": "导入：按模板批量创建，导入前请确认主数据编码已存在。",
        "create.b3": "已审核单据修改通常需走变更单或冲销流程，勿直接改已生效数据。",
        "views.label": "5.2 表头视图与明细视图",
        "views.title": "5.2 表头视图与明细视图",
        "views.p1": "两种视图服务不同工作场景，可随时切换对比。",
        "orderTitle": "表头视图（默认）",
        "orderP1": f"一行一张{ent}，适合批量审核、下推、关单与跟单。",
        "orderB1": "可展开行查看行项目摘要（若启用展开）。",
        "orderB2": "支持多选批量操作与工具栏下推（选中单条时）。",
        "orderB3": "生命周期、执行进度在单据级展示。",
        "detailTitle": "明细视图",
        "detailP1": "一行一条行项目，适合按物料核对数量与执行进度。",
        "detailB1": "只读查看，不可在此视图直接编辑行。",
        "detailB2": "无行勾选时，批量操作请切回表头视图。",
        "detailB3": "分页按行计数，与表头视图总数可能不同属正常现象。",
        "batch.label": "5.3 工具栏与批量操作",
        "batch.title": "5.3 工具栏与批量操作",
        "batch.p1": "批量按钮是否可用取决于选中行状态与您的权限码；灰色按钮悬停可查看原因。",
        "batch.b1": "批量删除：通常仅允许删除草稿等未执行单据。",
        "batch.b2": "批量审核：提交、撤回、通过、驳回（以组织审核配置为准）。" if audit_enabled else "批量操作：以工具栏实际按钮为准，置灰时请悬停查看原因。",
        "batch.b3": "批量关单/重开：终止或恢复执行（若提供）。",
        "batch.b4": "批量下推：选中符合条件的单据批量生成下游（以 capability 为准）。",
        "batch.b5": "批量打印：选中单条或多条后打印模板单据。",
        "batch.b6": "导出：导出当前列表筛选结果。",
        "push.label": "5.4 下推与下游单据",
        "push.title": "5.4 下推与下游单据",
        "push.p1": "下推入口位于工具栏「下推」按钮（通常需选中恰好一条）或行内下推菜单。系统会先校验状态、剩余数量与模块是否启用。",
        "push.p2": "多数下推会先打开预览窗，展示可推数量与目标单据类型，确认后再生成下游单据。",
        "push.b1": push_b[0],
        "push.b2": push_b[1],
        "push.b3": push_b[2],
        "push.b4": push_b[3],
        "push.b5": push_b[4],
        "push.b6": push_b[5],
        "push.b7": push_b[6],
        "push.b8": push_b[7],
        "push.alert": push_alert or "下推按钮置灰时，将鼠标悬停可查看具体原因（未审核、模块未启用、无权限、无可推数量等）。",
        "lifecycle.label": "5.5 状态与审核",
        "lifecycle.title": "5.5 状态与审核",
        "lifecycle.p1": "右侧「生命周期」或状态列展示当前阶段，与行内审核按钮联动。",
        "lifecycle.auditTitle": "审核相关",
        "lifecycle.auditP1": "是否启用多级审核由组织配置决定；行内按钮可能显示提交、通过、驳回、撤回等。",
        "lifecycle.auditB1": "草稿：可编辑、可删除（有权限时）。",
        "lifecycle.auditB2": "待审核：等待审批人处理，通常不可直接下推。" if audit_enabled else "待处理：等待相关人员处理。",
        "lifecycle.auditB3": "已审核：可下推、可打印，修改需走正式变更通道。" if audit_enabled else "已完成：只读或有限编辑，依单据类型而定。",
        "lifecycle.closeTitle": "关单与重开",
        "lifecycle.closeP1": "关单表示业务终止或已全部执行完毕，关单后通常不可再下推。",
        "lifecycle.closeB1": "批量关单前请确认无进行中的下游作业。",
        "lifecycle.closeB2": "误关单且业务允许时，可使用批量重开恢复执行态。",
        "detail.label": "5.6 详情抽屉与行操作",
        "detail.title": "5.6 详情抽屉与行操作",
        "detail.p1": "点击行内「查看」或单号打开详情抽屉，集中阅读头信息、行项目与跟踪信息。",
        "detail.b1": "查看：只读打开详情，可查看关联链路。",
        "detail.b2": "编辑：草稿或允许修改的状态下打开表单弹窗。",
        "detail.b3": "审核/打印/下推：与工具栏能力互补，适合单笔处理。",
        "detail.b4": "抽屉内可刷新单据，操作成功后列表与抽屉数据会同步更新。",
        "faq.q1": "Q: 为什么下推或审核按钮是灰的？",
        "faq.a1": "A: 常见原因：未选中单据、选中多条、未审核、目标模块未启用、无权限、行已无可推数量。请悬停按钮查看系统给出的具体原因。",
        "faq.q2": "Q: 表头视图与明细视图数量不一致？",
        "faq.a2": "A: 表头按单据计数，明细按行项目计数，分页 total 不同属正常现象。",
        "faq.q3": "Q: 已审核单据如何修改？",
        "faq.a3": f"A: 请使用组织配置的变更单、冲销或反审核流程，不要直接编辑已生效{ent}。",
        "faq.q4": "Q: 导入失败常见原因？",
        "faq.a4": "A: 编码不存在、单位不匹配、必填为空、状态不合法等。请先维护主数据并下载最新模板。",
        "faq.q5": "Q: 明细视图为什么不能批量操作？",
        "faq.a5": "A: 明细视图按行展示且通常为只读，无行勾选；批量操作请在表头视图进行。",
        "faq.q6": "Q: 看不到某工具栏按钮？",
        "faq.a6": "A: 按钮受 RBAC 权限与单据 capability 双重控制；外协账号可能只见授权范围内的操作。",
    }


def _equipment_order(title: str, asset: str, p1: str, **kwargs) -> dict[str, str]:
    return _detail_table_doc(title, p1, entity=title, b2=f"关联{asset}台账，执行记录回写设备状态与履历。", **kwargs)


def _eq_doc(key: str, title: str, p1: str, **kwargs) -> tuple[str, dict[str, str]]:
    return key, _equipment_order(title, "设备", p1, **kwargs)


def _mold_doc(key: str, title: str, p1: str, **kwargs) -> tuple[str, dict[str, str]]:
    return key, _equipment_order(title, "模具", p1, **kwargs)


def _tool_doc(key: str, title: str, p1: str, **kwargs) -> tuple[str, dict[str, str]]:
    return key, _equipment_order(title, "工装", p1, **kwargs)


BATCH3_KZ_DOC_KEYS = [
    "sales-delivery",
    "sales-order-change",
    "sales-review",
    "purchase-order-change",
    "purchase-receipt",
    "demand-computation",
    "demand-management",
    "incoming-inspection",
    "finished-goods-inspection",
    "process-inspection",
    "oqc-inspection",
    "fai-order",
    "outsource-work-order",
    "outsource-order",
    "rework-order",
    "reporting",
    "stocktaking",
    "inventory-transfer",
    "other-inbound",
    "other-outbound",
    "material-borrow",
    "material-return",
    "delivery-note",
]

BATCH3_KZ_DOC_CONTENT: dict[str, dict[str, str]] = {
    "sales-delivery": _detail_table_doc(
        "销售出库",
        "销售出库 Hub 页集中处理销售发运类出库单（含销售出库、发货关联出库等，以功能区切换为准）。审核后过账扣减库存，衔接发货通知与销售订单履约。",
        hub_note="功能区 Segmented 切换出库类型，切换后列与取数可能变化，筛选条件按当前类型生效。",
        pull_hint="优先从发货通知或销售订单取单，保证发运数量与订单一致。",
        push_items=("财务侧可下推销售发票（若启用）。", "退货场景走销售退货入库。", "打印出库单供物流交接。"),
        search_b2="出库类型：通过 beforeSearchButtons 切换不同类型出库。",
        layout_b2="工具栏：新建/取单、审核、过账、打印；类型切换在搜索区之前。",
    ),
    "sales-order-change": _detail_table_doc(
        "销售订单变更",
        "销售订单变更用于已审核销售订单的正式改价、改量、改交期通道，保留原单审计轨迹。",
        workflow=(
            "选择需变更的销售订单（通常从下推或关联入口发起，亦可在本页新建）。",
            "填写变更原因与变更行：新数量、新交期、新价格等。",
            "提交审核：变更单进入审批流。",
            "审核通过：回写销售订单头行，下游可推数量随之调整。",
            "通知相关计划/生产/物流岗位关注变更结果。",
            "关闭变更单：变更生效后归档。",
        ),
        push_items=("一般不直接下推仓储，影响体现在原销售订单。",),
        pull_hint="从销售订单带入不可变更的标识字段，仅修改允许变更的业务字段。",
    ),
    "sales-review": _detail_table_doc(
        "订单评审",
        "订单评审在正式创建销售订单前评估交期、产能与物料可得性，评审通过后可下推生成销售订单。",
        pull_hint="可从报价单或销售合同取单带入评审头行。",
        push_items=("下推销售订单：评审通过后生成正式订单。", "下推需求计算：评估物料缺口（若启用）。"),
    ),
    "purchase-order-change": _detail_table_doc(
        "采购订单变更",
        "采购订单变更是已审核采购订单改价改量改交期的正式通道，避免直接修改已生效订单。",
        pull_hint="从采购订单关联发起，带入原单标识。",
        push_items=("变更生效后影响未到货数量与收货计划。",),
    ),
    "purchase-receipt": _detail_table_doc(
        "采购收货",
        "采购收货 Hub 页处理采购入库类收货单，衔接采购订单与库存入账。",
        hub_note="功能区可切换收货/入库类型；切换后重新取数。",
        pull_hint="从采购订单或收货通知取单，核对到货数量与仓库。",
        push_items=("下推采购发票。", "异常到货走采购退货。", "质检未完成时可能限制过账（若启用来料检验）。"),
        search_b2="入库类型：Segmented 切换不同收货场景。",
    ),
    "demand-computation": _detail_table_doc(
        "需求计算",
        "需求计算根据销售、预测与库存策略运算物料需求，可下推需求计划或生产工单。",
        pull_hint="选择运算方案与期间，执行运算生成结果行。",
        push_items=("下推需求计划。", "下推生产工单（MTO 场景）。", "导出运算结果供计划会议使用。"),
        layout_b2="工具栏：运行运算、下推、导出；结果列表只读展示运算输出。",
    ),
    "demand-management": _detail_table_doc(
        "需求计划",
        "需求计划维护计划周期内的物料需求明细，可下推生产工单或采购申请。",
        pull_hint="从需求计算取单带入计划行，或手工维护计划。",
        push_items=("下推生产工单。", "下推采购申请。", "计划关闭后冻结下推。"),
    ),
    "incoming-inspection": _detail_table_doc(
        "来料检验",
        "来料检验对采购到货物料进行质检判定，合格数量方可入库或放行。",
        pull_hint="从采购收货/到货通知取单带入待检行。",
        push_items=("质检放行后允许入库过账。", "不合格品走退货或隔离流程。"),
        search_b2="检验结果：合格、不合格、待检等。",
    ),
    "finished-goods-inspection": _detail_table_doc(
        "成品检验",
        "成品检验对生产完工产品进行出货前质量判定，合格方可成品入库或发货。",
        pull_hint="从生产工单或完工汇报取单。",
        push_items=("下推成品入库。", "不合格品走返工或报废流程。"),
    ),
    "process-inspection": _detail_table_doc(
        "过程检验",
        "过程检验在工序报工过程中抽检半成品质量，异常可触发返工或停线。",
        pull_hint="关联工单工序或报工记录。",
        push_items=("触发返工工单（若启用）。", "记录不良原因供质量分析。"),
    ),
    "oqc-inspection": _detail_table_doc(
        "出货检验",
        "出货检验（OQC）在发运前对成品或批次进行最后质量确认。",
        pull_hint="从销售出库或完工入库待发货批次取单。",
        push_items=("检验通过后允许销售出库过账。",),
    ),
    "fai-order": _detail_table_doc(
        "首件检验",
        "首件检验（FAI）在新产品或新工艺首批生产时验证质量，通过后方可批量生产。",
        pull_hint="关联工单与工序，记录首件测量数据。",
        push_items=("通过后工单可继续批量报工。", "不合格则冻结批量生产直至复验。"),
    ),
    "outsource-work-order": _detail_table_doc(
        "外协工单",
        "外协工单将部分工序委外加工，跟踪发料、回货与加工费。",
        pull_hint="从生产工单工序下推或手工创建。",
        push_items=("下推外协发料。", "外协回货入库。", "下推外协订单对账。"),
    ),
    "outsource-order": _detail_table_doc(
        "外协订单",
        "外协订单是对外协供应商的采购式委外合同，衔接外协工单与财务对账。",
        pull_hint="从外协工单汇总生成或手工创建。",
        push_items=("下推外协发料/回货。", "下推应付或对账。"),
    ),
    "rework-order": _detail_table_doc(
        "返工工单",
        "返工工单处理检验不合格或客户退货需重新加工的产品，独立于原工单跟踪进度。",
        pull_hint="从不合格品记录或原工单下推。",
        push_items=("下推生产领料。", "完工后成品检验与入库。"),
    ),
    "reporting": _detail_table_doc(
        "生产报工",
        "生产报工记录工序开始、暂停、完工与数量，是工单进度与工时统计的数据来源。",
        audit_enabled=False,
        pull_hint="通常从工单或移动端扫码发起报工，PC 页查询与补录。",
        push_items=("报工数据回写工单进度。", "触发过程检验（若配置）。", "完工数量驱动画成品检验。"),
        layout_b2="工具栏：开工/报工/完工操作、导出；部分操作亦可在移动端完成。",
        workflow=(
            "选择工单与工序，确认工作中心与操作人员。",
            "开工：记录开始时间与在制状态。",
            "报工：录入良品/不良品数量与工时。",
            "暂停/复工：记录异常停机（若启用）。",
            "完工：工序完成，驱动下道或成品流程。",
            "关单：全部工序完成后工单完工。",
        ),
    ),
    "stocktaking": _detail_table_doc(
        "盘点单",
        "盘点单用于周期或抽盘库存，录入账面与实盘差异并过账调整库存。",
        pull_hint="新建盘点单选择仓库与盘点范围，锁盘期间谨慎作业。",
        push_items=("盘点差异过账调整库存。", "导出盘点表供现场抄录。"),
        workflow=(
            "新建盘点单：选择仓库、盘点类型与物料范围。",
            "冻结/锁盘：限制出入库（若组织启用）。",
            "录入实盘数量：PC 或移动端录入。",
            "审核差异：确认盘盈盘亏原因。",
            "过账：生成库存调整记录。",
            "关闭盘点单：完成本次盘点周期。",
        ),
    ),
    "inventory-transfer": _detail_table_doc(
        "调拨单",
        "调拨单在仓库或库位间转移库存，审核后发出仓扣减、接收仓增加。",
        pull_hint="手工新建或从补货建议取单（若启用）。",
        push_items=("在途状态跟踪调拨在途量。", "接收确认完成调拨。"),
        search_b2="发出仓/接收仓：按仓库组合筛选。",
    ),
    "other-inbound": _detail_table_doc(
        "其他入库",
        "其他入库处理非采购、非生产完工等场景的入库，如赠品、样品、盘盈入库。",
        pull_hint="手工新建选择入库类型与原因代码。",
        push_items=("过账增加库存。", "关联费用或成本中心（若配置）。"),
    ),
    "other-outbound": _detail_table_doc(
        "其他出库",
        "其他出库处理非销售发运等场景的出库，如样品、报废、盘亏出库。",
        pull_hint="手工新建并填写出库原因。",
        push_items=("过账扣减库存。",),
    ),
    "material-borrow": _detail_table_doc(
        "借料单",
        "借料单从仓库借出物料供现场或研发临时使用，须后续还料或消耗。",
        pull_hint="手工新建或从工单关联借料。",
        push_items=("下推还料单。", "超期未还触发提醒（若配置）。"),
    ),
    "material-return": _detail_table_doc(
        "还料单",
        "还料单将借料剩余物料退回仓库，冲减借料在途。",
        pull_hint="从借料单下推带入待还行。",
        push_items=("过账增加库存。",),
    ),
    "delivery-note": _detail_table_doc(
        "送货单",
        "送货单记录物流送货信息，衔接销售出库与客户签收。",
        pull_hint="从销售出库取单带入发运行。",
        push_items=("打印送货单。", "客户签收回写（若启用）。"),
    ),
}

_EQUIPMENT_DOC_SPECS: list[tuple[str, dict[str, str]]] = [
    _eq_doc("equipment-repairs", "设备维修", "设备维修单记录故障报修、维修过程与完修确认，恢复设备可用状态。"),
    _eq_doc("equipment-faults", "设备故障", "设备故障登记故障现象与停机时间，可下推维修单。"),
    _eq_doc("equipment-calibrations", "设备校准", "设备校准记录计量器具校准结果与下次校准日。"),
    _eq_doc("equipment-scrap", "设备报废", "设备报废申请经审批后注销台账资产。"),
    _eq_doc("equipment-transfers", "设备调拨", "设备调拨在厂区或部门间转移设备台账归属。"),
    _eq_doc("equipment-status", "设备状态", "设备状态页查看或维护设备运行/待机/故障等状态快照（以实现为准）。"),
    _eq_doc("maintenance-plans", "保养计划", "保养计划按周期生成保养任务，可下推保养执行单。"),
    _eq_doc("maintenance-executions", "保养执行", "保养执行单记录计划保养的实际执行与完修。"),
    _eq_doc("maintenance-reminders", "保养提醒", "保养提醒列表展示即将到期或逾期的保养任务。"),
    _eq_doc("spot-checks", "设备点检", "设备点检按点检方案记录日常巡检结果。"),
    _eq_doc("route-patrols", "路线巡检", "路线巡检按固定路线依次点检多台设备。"),
    _eq_doc("spare-part-requisitions", "备件领用", "备件领用单从备件库领取维修所需物料。"),
    _eq_doc("spare-parts", "备件档案", "备件档案维护备件编码、库存与安全库存，供维修领用引用。", audit_enabled=False),
    _mold_doc("mold-repairs", "模具维修", "模具维修单记录模具故障维修与完修。"),
    _mold_doc("mold-maintenances", "模具保养", "模具保养单按计划保养模具，延长寿命。"),
    _mold_doc("mold-calibrations", "模具校准", "模具校准记录精度检测与下次校准日期。"),
    _mold_doc("mold-borrows", "模具借用", "模具借用单记录模具借出与预计归还日。"),
    _mold_doc("mold-returns", "模具归还", "模具归还单将借出模具退回并更新台账状态。"),
    _mold_doc("mold-scrap-applications", "模具报废", "模具报废申请经审批后注销模具台账。"),
    _mold_doc("mold-trials", "模具试模", "模具试模记录试模参数与合格判定。"),
    _tool_doc("tool-repairs", "工装维修", "工装维修单记录工装故障维修。"),
    _tool_doc("tool-maintenances", "工装保养", "工装保养单执行保养项目并记录。"),
    _tool_doc("tool-calibrations", "工装校准", "工装校准记录计量与下次校准日。"),
    _tool_doc("tool-borrows", "工装借用", "工装借用单记录借出与归还计划。"),
    _tool_doc("tool-returns", "工装归还", "工装归还单完成借出工装退回。"),
    _tool_doc("tool-scrap-applications", "工装报废", "工装报废申请注销工装台账。"),
    _eq_doc("maintenance-schemes", "保养方案", "保养方案定义设备保养周期与项目组合。", audit_enabled=False),
    _eq_doc("maintenance-items", "保养项目", "保养项目维护单个保养动作与标准工时。", audit_enabled=False),
    _eq_doc("inspection-schemes", "点检方案", "点检方案定义点检路线与检查项。", audit_enabled=False),
    _eq_doc("inspection-items", "点检项目", "点检项目维护检查内容与判定标准。", audit_enabled=False),
    _eq_doc("patrol-routes", "巡检路线", "巡检路线维护依次点检的设备顺序。", audit_enabled=False),
    _mold_doc("mold-maintenance-schemes", "模具保养方案", "模具保养方案定义模具保养周期与项目。", audit_enabled=False),
    _mold_doc("mold-maintenance-items", "模具保养项目", "模具保养项目维护单个保养动作。", audit_enabled=False),
    _mold_doc("mold-repair-schemes", "模具维修方案", "模具维修方案定义常见故障处理模板。", audit_enabled=False),
    _mold_doc("mold-repair-items", "模具维修项目", "模具维修项目维护维修动作与备件。", audit_enabled=False),
    _tool_doc("tool-maintenance-schemes", "工装保养方案", "工装保养方案定义保养周期。", audit_enabled=False),
    _tool_doc("tool-maintenance-items", "工装保养项目", "工装保养项目维护保养动作。", audit_enabled=False),
    _tool_doc("tool-repair-schemes", "工装维修方案", "工装维修方案定义维修模板。", audit_enabled=False),
    _tool_doc("tool-repair-items", "工装维修项目", "工装维修项目维护维修动作。", audit_enabled=False),
]

BATCH3_EQUIPMENT_DOC_KEYS = [k for k, _ in _EQUIPMENT_DOC_SPECS]
BATCH3_EQUIPMENT_DOC_CONTENT = dict(_EQUIPMENT_DOC_SPECS)
BATCH3_EQUIPMENT_DOC_KEYS.append("maintenance-plan-calendar")
BATCH3_EQUIPMENT_DOC_CONTENT["maintenance-plan-calendar"] = _detail_table_doc(
    "保养计划日历",
    "保养计划日历以日历视图展示保养计划与执行安排，便于保全人员按日安排作业。",
    layout_p1="页面以日历为主视图，可切换月/周（以实现为准）；点击日程可跳转保养单详情。",
    audit_enabled=False,
    pull_hint="日历数据来自保养计划与执行单，本页通常不提供新建入口。",
    push_items=("点击日程打开关联保养执行单。", "逾期保养以醒目样式展示（若配置）。"),
)

BATCH3_KUAICAIWU_DOC_KEYS = [
    "receipt",
    "payment",
    "receivable",
    "payable",
    "sales-invoice",
    "purchase-invoice",
    "settlement",
    "price-settlement",
    "voucher",
    "prepayment",
    "notes-receivable",
    "notes-payable",
    "bank-account",
    "document-reconciliation",
    "opening-balance",
    "period-close",
]

BATCH3_KUAICAIWU_DOC_CONTENT: dict[str, dict[str, str]] = {
    "receipt": _detail_table_doc(
        "收款单",
        "收款单记录客户来款，可与应收单、销售发票核销，完成回款入账。",
        pull_hint="从应收单或销售发票取单带入待核销行。",
        push_items=("核销应收单。", "关联银行流水（若启用）。", "下推总账凭证（若启用）。"),
        search_b2="客户/结算方式：按伙伴与收款方式筛选。",
    ),
    "payment": _detail_table_doc(
        "付款单",
        "付款单记录供应商付款，可与应付单、采购发票核销。",
        pull_hint="从应付单或采购发票取单。",
        push_items=("核销应付单。", "关联银行流水。", "下推总账凭证。"),
    ),
    "receivable": _detail_table_doc(
        "应收单",
        "应收单记录对客户应收账款，来源于销售发票或手工录入，供收款核销与账龄分析。",
        pull_hint="从销售发票或销售出库下推生成。",
        push_items=("下推收款单。", "账龄分析报表钻取（菜单入口）。"),
        search_b2="账龄/到期：可 URL 参数 aging_bucket、overdue_only 带入筛选。",
    ),
    "payable": _detail_table_doc(
        "应付单",
        "应付单记录对供应商应付账款，来源于采购发票或入库，供付款核销。",
        pull_hint="从采购发票或采购入库下推。",
        push_items=("下推付款单。", "账龄分析。"),
    ),
    "sales-invoice": _detail_table_doc(
        "销售发票",
        "销售发票是销售开票与应收依据，可下推应收单与收款。",
        pull_hint="从销售出库取单带入开票行。",
        push_items=("下推应收单。", "下推收款单。", "导出税务接口（若配置）。"),
    ),
    "purchase-invoice": _detail_table_doc(
        "采购发票",
        "采购发票记录供应商发票，可下推应付单与付款。",
        pull_hint="从采购入库或采购订单取单。",
        push_items=("下推应付单。", "下推付款单。"),
    ),
    "settlement": _detail_table_doc(
        "核销",
        "核销页将收款/付款与应收/应付进行匹配冲账，完成往来清账。",
        audit_enabled=False,
        pull_hint="选择待核销的债权与债务单据，指定核销金额。",
        push_items=("核销完成后更新往来余额。", "不可超额核销，系统会校验剩余未核销额。"),
        layout_b2="工具栏：自动匹配、手工核销、撤销核销（高权限）。",
    ),
    "price-settlement": _detail_table_doc(
        "价格结算",
        "价格结算处理伙伴价格差异、返利或临时调价后的结算单。",
        pull_hint="从销售/采购业务取单或按结算规则生成。",
        push_items=("下推应收或应付调整。", "导出结算明细。"),
    ),
    "voucher": _detail_table_doc(
        "凭证",
        "凭证是总账记账依据，可手工录入或从业务单据自动生成。",
        pull_hint="从模板新建或从业务下推生成凭证。",
        push_items=("审核过账后影响科目余额。", "冲销凭证生成反向分录。"),
        search_b2="会计期间/科目：按期间与科目筛选。",
    ),
    "prepayment": _detail_table_doc(
        "预收预付",
        "预收预付单记录客户预收款或供应商预付款，后续与正式发票核销。",
        pull_hint="手工新建或从合同带入。",
        push_items=("与应收/应付核销。", "退款流程（若启用）。"),
    ),
    "notes-receivable": _detail_table_doc(
        "应收票据",
        "应收票据台账管理承兑汇票等应收票据，状态变更须走后端 action API。",
        pull_hint="从收款单关联票据或手工录入票面信息。",
        push_items=("背书、贴现、到期托收等动作通过行内 action 提交。", "禁止在页面手写第二套状态机。"),
    ),
    "notes-payable": _detail_table_doc(
        "应付票据",
        "应付票据台账管理开出或承兑的应付票据，兑付与拒付走标准 action。",
        pull_hint="从付款单关联或手工录入。",
        push_items=("到期兑付 action。", "拒付处理。"),
    ),
    "bank-account": _detail_table_doc(
        "银行账户",
        "银行账户维护企业银行账号，供收付款单与对账引用。",
        audit_enabled=False,
        pull_hint="主数据维护，新建账号并设置默认收款/付款账户。",
        push_items=("无业务下推。", "启用/停用控制是否可选。"),
    ),
    "document-reconciliation": _detail_table_doc(
        "单据对账",
        "单据对账核对业务单据与财务记录差异，发现未达账项。",
        audit_enabled=False,
        pull_hint="选择对账维度与期间执行对账。",
        push_items=("导出差异明细。", "调整建议需人工确认后处理。"),
    ),
    "opening-balance": _detail_table_doc(
        "期初余额",
        "期初余额录入总账科目与各辅助核算期初，启用新账套或新年度时使用。",
        pull_hint="按科目与辅助核算维度录入期初借贷。",
        push_items=("审核后期初锁定。", "下推试算平衡检查。"),
    ),
    "period-close": _detail_table_doc(
        "期末结账",
        "期末结账按会计期间执行关账，关账后禁止再录入该期凭证。",
        pull_hint="选择期间执行结账检查与关账。",
        push_items=("反结账需高权限。", "结账前须完成凭证审核与损益结转。"),
    ),
}

BATCH3_DOC_KEYS = BATCH3_KZ_DOC_KEYS + BATCH3_EQUIPMENT_DOC_KEYS + BATCH3_KUAICAIWU_DOC_KEYS
BATCH3_DOC_CONTENT: dict[str, dict[str, str]] = {
    **BATCH3_KZ_DOC_CONTENT,
    **BATCH3_EQUIPMENT_DOC_CONTENT,
    **BATCH3_KUAICAIWU_DOC_CONTENT,
}
