"""One-off builder for lo_post_glossary.json manual term batch."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
GLOSSARY = ROOT / "locale_glossary" / "lo_post_glossary.json"

MANUAL: dict[str, str] = {
    "Batch No.": "ເລກກຸ່ມ",
    "Batch / Serial No.": "ເລກກຸ່ມ / ໝາຍເລກລຳດັບ",
    "Batch / Serial": "ເລກກຸ່ມ / ໝາຍເລກລຳດັບ",
    "Batch + Serial": "ເລກກຸ່ມ + ໝາຍເລກລຳດັບ",
    "Serial No.": "ໝາຍເລກລຳດັບ",
    "Doc No.": "ເລກເອກະສານ",
    "Voucher No.": "ເລກໃບສຳຄັນ",
    "Checkout No.": "ເລກເຊັກເອົາ",
    "Handle No.": "ເລກຈັດການ",
    "Disassembly No.": "ເລກແຍກຊິ້ນ",
    "Batching No.": "ເລກຈັດຊຸດ",
    "Disassembly Order": "ໃບສັ່ງແຍກຊິ້ນ",
    "Disassembly Orders": "ໃບສັ່ງແຍກຊິ້ນ",
    "Disassembly Qty": "ຈຳນວນແຍກຊິ້ນ",
    "Rework Order": "ໃບສັ່ງຜະລິດຄືນ",
    "Outsource WO No.": "ເລກ WO ຮຸ້ງຊ່ວງ",
    "Outsource WO": "WO ຮຸ້ງຊ່ວງ",
    "Outsource WOs": "WO ຮຸ້ງຊ່ວງ",
    "Outsource Supplier": "ຜູ້ສະໜອງຮຸ້ງຊ່ວງ",
    "Outsource Qty": "ຈຳນວນຮຸ້ງຊ່ວງ",
    "Outsource Query": "ສອບຖາມຮຸ້ງຊ່ວງ",
    "Outsource Recon": "ກວດສອບຮຸ້ງຊ່ວງ",
    "Outsource": "ຮຸ້ງຊ່ວງ",
    "Backflush": "ຄືນວັດສະດຸອັດຕະໂນມັດ",
    "Backflush Qty": "ຈຳນວນຄືນວັດສະດຸ",
    "Phantom": "ວັດສະດຸຈຳລອງ",
    "First Pass Yield": "ອັດຕາຜ່ານຄັ້ງທຳອິດ",
    "First Pass Yield (%)": "ອັດຕາຜ່ານຄັ້ງທຳອິດ (%)",
    "Line-side Staging": "ຈຸດຈັດວັດສະດຸຂ້າງເສັ້ນ",
    "Mold Calibration": "ການປັບທຽບແມ່ພິມ",
    "Mold Calibrations": "ການປັບທຽບແມ່ພິມ",
    "Mold Scrap Request": "ຄຳຮ້ອງຂໍຕັດຈຳແມ່ພິມ",
    "Mold Borrows": "ການຢືມແມ່ພິມ",
    "Fixture": "ອຸປະກອນຈັບຊິ້ນ",
    "Exec": "ດຳເນີນການ",
    "Recompute": "ຄິດໄລ່ໃໝ່",
    "Push Preview": "ເບິ່ງກ່ອນສົ່ງຕໍ່",
    "Push Qty": "ຈຳນວນສົ່ງຕໍ່",
    "Backlog": "ຄົງຄ້າງ",
    "Batch Enable": "ເປີດໃຊ້ເປັນກຸ່ມ",
    "Batch Execute": "ດຳເນີນການເປັນກຸ່ມ",
    "Batch Recompute": "ຄິດໄລ່ໃໝ່ເປັນກຸ່ມ",
    "Batch Outbound": "ອອກສາງເປັນກຸ່ມ",
    "Batch Freeze": "ແຊ່ແຂງເປັນກຸ່ມ",
    "Batch Unfreeze": "ປົດແຊ່ແຂງເປັນກຸ່ມ",
    "Batch Void": "ຍົກເລີກເປັນກຸ່ມ",
    "Batch Post": "ບັນທຶກບັນຊີເປັນກຸ່ມ",
    "Batch Records": "ບັນທຶກເປັນກຸ່ມ",
    "Batch Unban": "ປົດລະງັບເປັນກຸ່ມ",
    "Batch Default Supplier": "ຜູ້ສະໜອງເລີ່ມຕົ້ນເປັນກຸ່ມ",
    "Batch Mark as Read ({{count}})": "ໝາຍວ່າອ່ານແລ້ວ {{count}} ລາຍການ",
    "Del": "ລຶບ",
    "Seq.": "ລຳດັບ",
    "WIP": "ງານຄ້າງ",
    "SKUs": "SKU",
    "pcs": "ຊິ້ນ",
    "Kanban": "ກະດານຄັນບັນ",
    "Gantt": "ແຜນຂັ້ນ Gantt",
    "Carousel": "ການສະແດງແບບມ້ວນ",
    "Anchor hint": "ຄຳແນະນຳຈຸດຢຶດ",
    "Bottleneck Title": "ຫົວຂໍ້ຈຸດຄອຂວດ",
    "Gap Flags": "ສັນຍາກຊ່ອງຫວ່າງ",
    "Config Center": "ສູນການຕັ້ງຄ່າ",
    "Config Overview": "ພາບລວມການຕັ້ງຄ່າ",
    "Config Template Management": "ຈັດການແມ່ແບບການຕັ້ງຄ່າ",
    "Config (JSON)": "ການຕັ້ງຄ່າ (JSON)",
    "Node Config": "ການຕັ້ງຄ່າໂນດ",
    "Flow Config": "ການຕັ້ງຄ່າກະແສ",
    "Field Config": "ການຕັ້ງຄ່າຊ່ອງ",
    "Field Block": "ບລັອກຊ່ອງ",
    "Emp Config": "ການຕັ້ງຄ່າພະນັກງານ",
    "Integration Config": "ການຕັ້ງຄ່າການເຊື່ອມຕໍ່",
    "Core Tech Stack": "ກຸ່ມເທັກໂນໂລຊີຫຼັກ",
    "Page Metrics Config": "ການຕັ້ງຄ່າເມຕຣິກຫນ້າ",
    "Crop Platform Logo": "ຕັດໂລໂກ້ແພລດຟອร์ມ",
    "Cell Padding (px)": "ຊ່ອງຫວ່າງເຊລ (px)",
    "APIs": "API",
    "API Key": "ລະຫັດ API",
    "AP Management": "ຈັດການເຈົ້າຫນี้",
    "AP Recon": "ກວດສອບເຈົ້າຫນี้",
    "AP reconciliation": "ກວດສອບເຈົ້າຫนี้",
    "AR Recon": "ກວດສອບລູກຫນี้",
    "Enterprise Unrecorded Debit": "ເຈົ້າຫນี້ທີ່ຍັງບໍ່ໄດ້ບັນທຶກ",
    "Gross Margin": "ອັດຕາກຳໄລຂັ້ນຕົ້ນ",
    "GL": "ບັນຊີແຍກປະເພດ",
    "KPI Coefficient": "ສັກປະສິດ KPI",
    "KPI Defs": "ຄຳນິຍາມ KPI",
    "COD": "ເກັບເງິນປາຍທາງ",
    "Kitting semantics": "ຄວາມໝາຍການຈັດຊຸດ",
    "8D Workbench": "ໂຕະງານ 8D",
    "AI-Assisted Development": "ພັດທະນາດ້ວຍ AI",
    "Ingest Payload": "ຂໍ້ມູນຮັບເຂົ້າ",
    "Ingest subtitle": "ຄຳອະທິບາຍຮັບເຂົ້າ",
    ", batching {{codes}}": ", ຈັດຊຸດ {{codes}}",
    "{{count}} docs →": "{{count}} ເອກະສານ →",
    "{{count}} WIP": "{{count}} ງານຄ້າງ",
    "Doc #{{id}}": "ເອກະສານ #{{id}}",
    "Col {{n}}": "ຖັນ {{n}}",
    "1D Barcode": "ບາໂຄ້ດ 1D",
    "2D Barcode": "ບາໂຄ້ດ 2D",
    "MTD": "ເດືອນນີ້",
    "OEE": "OEE",
    "OEE %": "OEE %",
    "CNY": "ຫຍວນ",
    "CNY (RMB)": "ຫຍວນ (RMB)",
    "CNY ￥": "￥ ຫຍວນ",
    "USD": "ໂດລ່າ",
    "HKD": "ໂດລ່າຮ່ອງກົງ",
    "GBP": "ປອນດ໌",
    "JPY": "ເຢນ",
    "CC Node": "ໂນດ CC",
    "New Outsource": "ສ້າງ WO ຮຸ້ງຊ່ວງ",
    "Edit Outsource": "ແກ້ໄຂ WO ຮຸ້ງຊ່ວງ",
    "Total Outsource": "WO ຮຸ້ງຊ່ວງທັງໝົດ",
    "Outsource ໃບສັ່ງຜະລິດ": "ໃບສັ່ງຜະລິດຮຸ້ງຊ່ວງ",
    "New Outsource ໃບສັ່ງຜະລິດ": "ສ້າງໃບສັ່ງຜະລິດຮຸ້ງຊ່ວງ",
    "Edit Outsource ໃບສັ່ງຜະລິດ": "ແກ້ໄຂໃບສັ່ງຜະລິດຮຸ້ງຊ່ວງ",
    "Outsource ໃບສັ່ງຜະລິດ Details": "ລາຍລະອຽດໃບສັ່ງຜະລິດຮຸ້ງຊ່ວງ",
    "Total Outsource ໃບສັ່ງຜະລິດs": "ໃບສັ່ງຜະລິດຮຸ້ງຊ່ວງທັງໝົດ",
    "Outsource ຊື່ WO": "ຊື່ WO ຮຸ້ງຊ່ວງ",
    "Outsource ໃບສັ່ງຜະລິດs": "ໃບສັ່ງຜະລິດຮຸ້ງຊ່ວງ",
    "customer_pool_{{date}}.csv": "customer_pool_{{date}}.csv",
    "{{from}} -> {{to}}": "{{from}} -> {{to}}",
    "material-market-price": "material-market-price",
    # --- batch 2: menus, labels, connectors ---
    "Spot Check Scheme Bindings": "ການຜູກແຜນກວດຈຸດ",
    "Ops Master Data": "ຂໍ້ມູນຫຼັກດ້ານດຳເນີນງານ",
    "Mold Ops": "ດຳເນີນງານແມ່ພິມ",
    "Tool Ops": "ດຳເນີນງານອຸປະກອນ",
    "Linked Supplier ID": "ID ຜູ້ສະໜອງທີ່ເຊື່ອມ",
    "Line Stop Feedback": "ຄຳຕິຊົມຢຸດສາຍ",
    "Line Stop Report": "ລາຍງານຢຸດສາຍ",
    "Line View": "ມຸມມອງສາຍ",
    "Hex Bolt": "ໂບລທຫົກຫຼ່ຽມ",
    "Die Casting Add-on": "ໂມດູນຫຼ่อมຊິ້ນ die casting",
    "Injection Molding Add-on": "ໂມດູນຂึ้นรูปພລາສຕິກ",
    "Dot Matrix 241 Full (241x280mm)": "Dot Matrix 241 ເຕັມ (241x280mm)",
    "Dot Matrix 241 Half (241x140mm)": "Dot Matrix 241 ຄູ່ (241x140mm)",
    "Dot Matrix 241 Third (241x93mm)": "Dot Matrix 241 1/3 (241x93mm)",
    "FQC / OQC": "FQC / OQC",
    "IQC / IPQC": "IQC / IPQC",
    "Menu group": "ກຸ່ມເມນູ",
    "Scheduled task": "ວຽກຕາມກຳນົດ",
    "Custom field": "ຊ່ອງກຳນົດເອງ",
    "Permission resource": "ຊັບພະຍາກກຳນົດສິດ",
    "Document tracking": "ຕິດຕາມເອກະສານ",
    "Relation graph": "ແຜນຜັງຄວາມສຳພັນ",
    "Pull query": "ດຶງຂໍ້ມູນສອບຖາມ",
    "Code rule": "ກົດເລກໂຄ້ດ",
    "Report designer": "ສ້າງແບບລາຍງານ",
    "Tech stack": "ກຸ່ມເທັກໂນໂລຊີ",
    "RiverEdge SaaS": "RiverEdge SaaS",
    "Default platform name": "ຊື່ແພລດຟອร์ມເລີ່ມຕົ້ນ",
    "Wechat login": "ເຂົ້າສູ່ລະບົບ WeChat",
    "wechatLogin": "WeChat",
    "Config center": "ສູນການຕັ້ງຄ່າ",
    "Data center": "ສູນຂໍ້ມູນ",
    "Mold calibration": "ການປັບທຽບແມ່ພິມ",
    "Tool calibration": "ການປັບທຽບອຸປະກອນ",
    "Tool ledger": "ບັນຊີອຸປະກອນ",
    "Tool usage": "ການນຳໃຊ້ອຸປະກອນ",
    "Calibration Alerts": "ແຈ້ງເຕືອນການປັບທຽບ",
    "Checkout/Check-in": "ເຊັກເອົາ/ເຊັກຄືນ",
    "Normal": "ປົກກະຕິ",
    "正常": "ປົກກະຕິ",
    "Spot check": "ກວດຈຸດ",
    "Spot Check": "ກວດຈຸດ",
    "Scheme binding": "ການຜູກແຜນ",
    "Initial data": "ຂໍ້ມູນເລີ່ມຕົ້ນ",
    "Import example": "ຕົວຢ່າງນຳເຂົ້າ",
    "Template file": "ໄຟລ໌ແມ່ແບບ",
    "Error CSV": "CSV ຂໍ້ຜິດພາດ",
    "Linked document": "ເອກະສານທີ່ເຊື່ອມ",
    "Linked supplier": "ຜູ້ສະໜອງທີ່ເຊື່ອມ",
    "Market price": "ລາຄາຕະຫຼາດ",
    "Agile quoting": "ສະເໜີລາຄາດ່ວນ",
    "Demand computation": "ຄິດໄລ່ຄວາມຕ້ອງການ",
    "Batching center": "ສູນຈັດຊຸດ",
    "Customer pool": "ກຸ່ມລູກຄ້າສາທາລະນະ",
    "Coordination pipeline": "ຂັ້ນຕອນປະສານງານ",
    "Purchase arrival": "ການມາຮອດຈັດຊື້",
    "Mobile equipment": "ອຸປະກອນມືຖື",
    "Equipment ops": "ດຳເນີນງານອຸປະກອນ",
    "Work reporting": "ລາຍງານການຜະລິດ",
    "Quick report": "ລາຍງານດ່ວນ",
    "Last op": "ຂັ້ນຕອນສຸດທ້າຍ",
    "Direct inbound": "ຮັບເຂົ້າສາງໂດຍກົງ",
    "Inbound notice": "ແຈ້ງຮັບເຂົ້າສາງ",
    "No auto inbound": "ບໍ່ຮັບເຂົ້າອັດຕະໂນມັດ",
    "Post action": "ການກະທຳຫຼັງສົ່ງ",
    "Fqc blocked": "FQC ບລັອກ",
    "Pending inbound": "ລໍຖ້າຮັບເຂົ້າ",
    "Confirmed inbound": "ຮັບເຂົ້າຢືນຢັນແລ້ວ",
    "Failed inbound": "ຮັບເຂົ້າລົ້ມເຫຼວ",
}


def main() -> None:
    existing = json.loads(GLOSSARY.read_text(encoding="utf-8"))
    merged = {**existing, **MANUAL}
    GLOSSARY.write_text(json.dumps(merged, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {len(merged)} glossary entries to {GLOSSARY.name}")


if __name__ == "__main__":
    main()
