#!/usr/bin/env python3
"""Generate custom field page locale modules from backend custom_field_pages.py."""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BACKEND_SRC = ROOT / "riveredge-backend" / "src"
FRONTEND = ROOT / "riveredge-frontend"
OUT_LOCALE = FRONTEND / "src" / "locales" / "generated" / "customFieldPage"
OUT_REGISTRY = FRONTEND / "src" / "utils" / "generated" / "customFieldPageRegistry.ts"
EN_JSON = Path(__file__).resolve().parent / "custom_field_page_i18n_en.json"

sys.path.insert(0, str(BACKEND_SRC))

from core.config.custom_field_pages import CUSTOM_FIELD_PAGES  # noqa: E402


def ts_escape(s: str) -> str:
    return (s or "").replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n")


def page_key(page_code: str, field: str) -> str:
    return f"customFieldPage.{page_code}.{field}"


def collect_manifest() -> dict[str, dict[str, str]]:
    pages: dict[str, dict[str, str]] = {}
    for item in CUSTOM_FIELD_PAGES:
        code = str(item["page_code"])
        pages[code] = {
            "pageName": item.get("page_name") or "",
            "tableNameLabel": item.get("table_name_label") or "",
            "module": item.get("module") or "",
        }
    return {"pages": pages}


def build_entries(manifest: dict, lang: str, en_data: dict) -> dict[str, str]:
    entries: dict[str, str] = {}
    en_pages = en_data.get("pages", {})
    en_page_names = en_data.get("pageName", {})
    en_table_labels = en_data.get("tableNameLabel", {})

    for page_code, fields in manifest["pages"].items():
        en_page = en_pages.get(page_code, {})
        for field in ("pageName", "tableNameLabel"):
            zh = fields.get(field, "")
            k = page_key(page_code, field)
            if lang == "zh-CN":
                entries[k] = zh
            else:
                fallback_map = en_page_names if field == "pageName" else en_table_labels
                entries[k] = (
                    en_page.get(field)
                    or fallback_map.get(zh)
                    or zh
                )

    return entries


def write_ts_locale(path: Path, const_name: str, entries: dict[str, str]) -> None:
    lines = [
        "/** Auto-generated by scripts/generate_custom_field_page_locale.py — do not edit manually */",
        f"const {const_name} = {{",
    ]
    for k in sorted(entries.keys()):
        lines.append(f"  '{ts_escape(k)}': '{ts_escape(entries[k])}',")
    lines.append("} as const;")
    lines.append("")
    lines.append(f"export default {const_name};")
    lines.append("")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def write_registry(page_codes: list[str]) -> None:
    codes_str = ", ".join(f"'{ts_escape(c)}'" for c in sorted(page_codes))
    content = f"""/** Auto-generated by scripts/generate_custom_field_page_locale.py — do not edit manually */

export const CUSTOM_FIELD_PAGE_CODES = new Set<string>([{codes_str}]);

export function isCustomFieldPageCode(pageCode: string | undefined | null): boolean {{
  return !!pageCode && CUSTOM_FIELD_PAGE_CODES.has(pageCode);
}}
"""
    OUT_REGISTRY.parent.mkdir(parents=True, exist_ok=True)
    OUT_REGISTRY.write_text(content, encoding="utf-8")


def main() -> None:
    manifest = collect_manifest()
    en_data = json.loads(EN_JSON.read_text(encoding="utf-8")) if EN_JSON.exists() else {}
    zh_entries = build_entries(manifest, "zh-CN", en_data)
    en_entries = build_entries(manifest, "en-US", en_data)
    write_ts_locale(OUT_LOCALE / "zh-CN.ts", "customFieldPageZhCN", zh_entries)
    write_ts_locale(OUT_LOCALE / "en-US.ts", "customFieldPageEnUS", en_entries)
    write_registry(list(manifest["pages"].keys()))
    print(f"Generated {len(manifest['pages'])} custom field pages, {len(zh_entries)} locale keys")


if __name__ == "__main__":
    main()
