#!/usr/bin/env python3
"""Generate code rule page locale modules from backend code_rule_pages.py (SSOT)."""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BACKEND_SRC = ROOT / "riveredge-backend" / "src"
FRONTEND = ROOT / "riveredge-frontend"
OUT_LOCALE = FRONTEND / "src" / "locales" / "generated" / "codeRulePage"
OUT_REGISTRY = FRONTEND / "src" / "utils" / "generated" / "codeRulePageRegistry.ts"
EN_JSON = Path(__file__).resolve().parent / "code_rule_page_i18n_en.json"

sys.path.insert(0, str(BACKEND_SRC))

from core.config.code_rule_pages import CODE_RULE_PAGES  # noqa: E402


def ts_escape(s: str) -> str:
    return (s or "").replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n")


def page_key(page_code: str, field: str) -> str:
    return f"codeRulePage.{page_code}.{field}"


def module_key(module_zh: str) -> str:
    return f"codeRulePage.module.{module_zh}"


def collect_manifest() -> dict[str, dict[str, str]]:
    pages: dict[str, dict[str, str]] = {}
    modules: dict[str, str] = {}
    for item in CODE_RULE_PAGES:
        code = str(item["page_code"])
        pages[code] = {
            "pageName": item.get("page_name") or "",
            "codeFieldLabel": item.get("code_field_label") or "",
            "module": item.get("module") or "",
        }
        mod = item.get("module") or ""
        if mod:
            modules[mod] = mod
    return {"pages": pages, "modules": modules}


def build_entries(manifest: dict, lang: str, en_data: dict) -> dict[str, str]:
    entries: dict[str, str] = {}
    en_pages = en_data.get("pages", {})
    en_modules = en_data.get("modules", {})
    en_page_names = en_data.get("pageName", {})
    en_code_labels = en_data.get("codeFieldLabel", {})

    seen_modules: set[str] = set()
    for page_code, fields in manifest["pages"].items():
        en_page = en_pages.get(page_code, {})
        for field in ("pageName", "codeFieldLabel"):
            zh = fields.get(field, "")
            k = page_key(page_code, field)
            if lang == "zh-CN":
                entries[k] = zh
            else:
                entries[k] = (
                    en_page.get(field)
                    or (en_page_names.get(zh) if field == "pageName" else en_code_labels.get(zh))
                    or zh
                )

        mod = fields.get("module", "")
        if mod and mod not in seen_modules:
            seen_modules.add(mod)
            mk = module_key(mod)
            if lang == "zh-CN":
                entries[mk] = mod
            else:
                entries[mk] = en_modules.get(mod, mod)

    return entries


def write_ts_locale(path: Path, const_name: str, entries: dict[str, str]) -> None:
    lines = [
        "/** Auto-generated by scripts/generate_code_rule_page_locale.py — do not edit manually */",
        f"const {const_name} = {{",
    ]
    for k in sorted(entries.keys()):
        lines.append(f"  '{ts_escape(k)}': '{ts_escape(entries[k])}',")
    lines.append("} as const;")
    lines.append("")
    lines.append(f"export default {const_name};")
    lines.append("")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def write_registry(page_codes: list[str]) -> None:
    codes_str = ", ".join(f"'{ts_escape(c)}'" for c in sorted(page_codes))
    content = f"""/** Auto-generated by scripts/generate_code_rule_page_locale.py — do not edit manually */

export const CODE_RULE_PAGE_CODES = new Set<string>([{codes_str}]);

export function isCodeRulePageCode(pageCode: string | undefined | null): boolean {{
  return !!pageCode && CODE_RULE_PAGE_CODES.has(pageCode);
}}
"""
    OUT_REGISTRY.parent.mkdir(parents=True, exist_ok=True)
    OUT_REGISTRY.write_text(content, encoding="utf-8")


def main() -> None:
    manifest = collect_manifest()
    en_data = json.loads(EN_JSON.read_text(encoding="utf-8")) if EN_JSON.exists() else {}
    zh_entries = build_entries(manifest, "zh-CN", en_data)
    en_entries = build_entries(manifest, "en-US", en_data)
    write_ts_locale(OUT_LOCALE / "zh-CN.ts", "codeRulePageZhCN", zh_entries)
    write_ts_locale(OUT_LOCALE / "en-US.ts", "codeRulePageEnUS", en_entries)
    write_registry(list(manifest["pages"].keys()))
    print(f"Generated {len(manifest['pages'])} code rule pages, {len(zh_entries)} locale keys")


if __name__ == "__main__":
    main()
