#!/usr/bin/env python3
"""Generate system dictionary locale modules from backend SYSTEM_DICTIONARIES + EN JSON."""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BACKEND_SRC = ROOT / "riveredge-backend" / "src"
FRONTEND = ROOT / "riveredge-frontend"
OUT_DIR = FRONTEND / "src" / "locales" / "generated" / "systemDictionary"
EN_JSON = Path(__file__).resolve().parent / "system_dictionary_i18n_en.json"

sys.path.insert(0, str(BACKEND_SRC))
from core.config.system_dictionaries import SYSTEM_DICTIONARIES  # noqa: E402


def item_value_key(value: str) -> str:
    return value.replace("/", "__")


def ts_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n")


def build_locale_entries(lang: str, en_data: dict) -> dict[str, str]:
    entries: dict[str, str] = {}
    for d in SYSTEM_DICTIONARIES:
        code = d["code"]
        if lang == "zh-CN":
            entries[f"systemDictionary.{code}.name"] = d["name"]
            entries[f"systemDictionary.{code}.desc"] = d.get("description") or ""
        else:
            en_dict = en_data.get(code, {})
            entries[f"systemDictionary.{code}.name"] = en_dict.get("name", d["name"])
            entries[f"systemDictionary.{code}.desc"] = en_dict.get("desc", d.get("description") or "")

        en_items = en_data.get(code, {}).get("items", {})
        for item in d.get("items", []):
            value = item["value"]
            vk = item_value_key(value)
            label_key = f"systemDictionary.{code}.item.{vk}.label"
            desc_key = f"systemDictionary.{code}.item.{vk}.desc"
            if lang == "zh-CN":
                entries[label_key] = item.get("label") or ""
                entries[desc_key] = item.get("description") or ""
            else:
                en_item = en_items.get(value, {})
                entries[label_key] = en_item.get("label", item.get("label") or "")
                entries[desc_key] = en_item.get("desc", item.get("description") or "")
    return entries


def write_ts_file(path: Path, lang: str, entries: dict[str, str]) -> None:
    lines = [
        "/** Auto-generated by scripts/generate_system_dictionary_locale.py — do not edit manually */",
        f"const systemDictionary{lang.replace('-', '')} = {{",
    ]
    for key in sorted(entries.keys()):
        lines.append(f"  '{ts_escape(key)}': '{ts_escape(entries[key])}',")
    lines.append("} as const;")
    lines.append("")
    lines.append(f"export default systemDictionary{lang.replace('-', '')};")
    lines.append("")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    en_data = json.loads(EN_JSON.read_text(encoding="utf-8"))
    write_ts_file(OUT_DIR / "zh-CN.ts", "zh-CN", build_locale_entries("zh-CN", en_data))
    write_ts_file(OUT_DIR / "en-US.ts", "en-US", build_locale_entries("en-US", en_data))
    print(f"Generated {OUT_DIR}/zh-CN.ts and en-US.ts ({len(SYSTEM_DICTIONARIES)} dictionaries)")


if __name__ == "__main__":
    main()
