/**
 * Schema 驱动表单渲染器（共享）
 *
 * 根据 FieldConfig 配置渲染 ProForm 组件，标签和校验文案从 i18n 读取。
 * 供 master-data、system、infra 等模块复用。
 */

import React from 'react';
import { useTranslation } from 'react-i18next';
import { Tooltip, Space } from 'antd';
import { QuestionCircleOutlined } from '@ant-design/icons';
import {
  ProFormText,
  ProFormTextArea,
  ProFormSwitch,
  ProFormDigit,
  ProFormDatePicker,
  ProFormDateTimePicker,
  ProFormSelect,
  ProFormTreeSelect,
} from '@ant-design/pro-components';
import type { FieldConfig } from './form-schemas';

export interface SchemaFormRendererProps {
  schema: FieldConfig[];
  /** slot 插槽内容，key 对应 schema 中 type: 'slot' 的 slotKey */
  slots?: Record<string, React.ReactNode>;
  /** 编码规则相关：编码字段名，用于显示 extra 提示 */
  codeField?: string;
  codeAutoGenerated?: boolean;
  /** 编码自动生成时的 placeholder/extra 文案 i18n key，如 field.customer.codeAutoGenerated */
  codeAutoGeneratedKey?: string;
  isEdit?: boolean;
  /** select 类型字段的 options，key 为字段名 */
  optionsMap?: Record<string, Array<{ value: any; label: string }>>;
  /** treeSelect 类型字段的 treeData，key 为字段名，格式 { title, value, key, children? } */
  treeDataMap?: Record<string, Array<{ title: string; value: string; key?: string; children?: any[] }>>;
  /** 编辑时是否允许修改编码字段（默认 false，编辑时编码禁用） */
  allowEditCodeWhenEdit?: boolean;
}

function buildRules(field: FieldConfig, t: (key: string) => string): any[] {
  const rules: any[] = [];
  for (const r of field.rules || []) {
    const msg = r.messageKey ? t(r.messageKey) : r.message;
    if (r.required) {
      rules.push({ required: true, message: msg });
    } else if (r.maxLength != null) {
      rules.push({ max: r.maxLength, message: msg });
    } else if (r.type === 'email') {
      rules.push({ type: 'email', message: msg });
    } else if (r.pattern) {
      rules.push({ pattern: r.pattern, message: msg });
    }
  }
  return rules;
}

const DEFAULT_CODE_AUTO_GENERATED_KEY = 'app.master-data.formSchema.enterPlaceholder';

export const SchemaFormRenderer: React.FC<SchemaFormRendererProps> = ({
  schema,
  slots = {},
  codeField,
  codeAutoGenerated,
  codeAutoGeneratedKey = DEFAULT_CODE_AUTO_GENERATED_KEY,
  isEdit,
  optionsMap = {},
  treeDataMap = {},
  allowEditCodeWhenEdit = false,
}) => {
  const { t } = useTranslation();

  const buildLabel = (field: FieldConfig, labelText: string): React.ReactNode => {
    if (field.extraAsTooltip && field.extraKey) {
      return (
        <Space size={4}>
          <span>{labelText}</span>
          <Tooltip title={t(field.extraKey)}>
            <QuestionCircleOutlined style={{ color: 'rgba(0,0,0,0.45)', fontSize: 12, cursor: 'help' }} />
          </Tooltip>
        </Space>
      );
    }
    return labelText;
  };

  return (
    <>
      {schema.map((field) => {
        if (field.type === 'slot' && field.slotKey) {
          const slotContent = slots[field.slotKey];
          return slotContent ? <React.Fragment key={field.name}>{slotContent}</React.Fragment> : null;
        }
        const labelText = t(field.labelKey!);
        const label = buildLabel(field, labelText);
        const placeholder = field.placeholderKey ? t(field.placeholderKey) : undefined;
        const extraContent = field.extraAsTooltip && field.extraKey ? undefined : (field.extraKey ? t(field.extraKey) : undefined);
        const rules = buildRules(field, t);
        const colSpan = field.colSpan ?? 12;
        const isCodeField = codeField && field.name === codeField;

        if (field.type === 'treeSelect') {
          const treeData = treeDataMap[field.name] ?? [];
          return (
            <ProFormTreeSelect
              key={field.name}
              name={field.name}
              label={label}
              placeholder={placeholder}
              colProps={{ span: colSpan }}
              rules={rules}
              fieldProps={{
                treeData,
                showSearch: true,
                allowClear: field.allowClear ?? true,
                treeNodeFilterProp: 'title',
                ...field.fieldProps,
              }}
              extra={extraContent}
            />
          );
        }

        if (field.type === 'select') {
          const optionsFromMap = optionsMap[field.name];
          const options = optionsFromMap ?? (field.options?.map((o) => ({ label: t(o.labelKey), value: o.value })) ?? []);
          const selectDisabled = (field.disabledWhenEdit && isEdit) || field.fieldProps?.disabled;
          return (
            <ProFormSelect
              key={field.name}
              name={field.name}
              label={label}
              placeholder={placeholder}
              colProps={{ span: colSpan }}
              rules={rules}
              options={options}
              extra={extraContent}
              fieldProps={{
                showSearch: true,
                filterOption: (input: string, option: any) =>
                  (option?.label ?? '').toString().toLowerCase().includes(input.toLowerCase()),
                allowClear: field.allowClear,
                mode: field.mode,
                optionFilterProp: 'label',
                disabled: selectDisabled,
                ...field.fieldProps,
              }}
            />
          );
        }

        if (field.type === 'textarea') {
          return (
            <ProFormTextArea
              key={field.name}
              name={field.name}
              label={label}
              placeholder={placeholder}
              colProps={{ span: colSpan }}
              rules={rules}
              fieldProps={field.fieldProps}
            />
          );
        }

        if (field.type === 'switch') {
          return (
            <ProFormSwitch
              key={field.name}
              name={field.name}
              label={label}
              colProps={{ span: colSpan }}
              extra={extraContent}
              initialValue={true}
            />
          );
        }

        if (field.type === 'number') {
          return (
            <ProFormDigit
              key={field.name}
              name={field.name}
              label={label}
              placeholder={placeholder}
              colProps={{ span: colSpan }}
              rules={rules}
              fieldProps={field.fieldProps}
            />
          );
        }

        if (field.type === 'date') {
          return (
            <ProFormDatePicker
              key={field.name}
              name={field.name}
              label={label}
              placeholder={placeholder}
              colProps={{ span: colSpan }}
              rules={rules}
              fieldProps={field.fieldProps}
            />
          );
        }

        if (field.type === 'datetime') {
          return (
            <ProFormDateTimePicker
              key={field.name}
              name={field.name}
              label={label}
              placeholder={placeholder}
              colProps={{ span: colSpan }}
              rules={rules}
              fieldProps={field.fieldProps}
              extra={extraContent}
            />
          );
        }

        // default: text
        const textFieldProps = { ...field.fieldProps };
        if (isCodeField && isEdit && !allowEditCodeWhenEdit) {
          textFieldProps.disabled = true;
        }
        return (
          <ProFormText
            key={field.name}
            name={field.name}
            label={label}
            placeholder={isCodeField && codeAutoGenerated ? t(codeAutoGeneratedKey, { label: labelText }) : placeholder}
            colProps={{ span: colSpan }}
            rules={rules}
            fieldProps={textFieldProps}
            extra={undefined}
          />
        );
      })}
    </>
  );
};
