/**
 * Schema 驱动表单渲染器（共享）
 *
 * 根据 FieldConfig 配置渲染 ProForm 组件，标签和校验文案从 i18n 读取。
 * 供 master-data、system、infra 等模块复用。
 */

import React from 'react';
import { useTranslation } from 'react-i18next';
import {
  ProFormText,
  ProFormTextArea,
  ProFormSwitch,
  ProFormDigit,
  ProFormDatePicker,
  ProFormDateTimePicker,
  ProFormSelect,
  ProFormTreeSelect,
} from '@ant-design/pro-components';
import type { FieldConfig } from './form-schemas';

export interface SchemaFormRendererProps {
  schema: FieldConfig[];
  /** 编码规则相关：编码字段名，用于显示 extra 提示 */
  codeField?: string;
  codeAutoGenerated?: boolean;
  /** 编码自动生成时的 placeholder/extra 文案 i18n key，如 field.customer.codeAutoGenerated */
  codeAutoGeneratedKey?: string;
  isEdit?: boolean;
  /** select 类型字段的 options，key 为字段名 */
  optionsMap?: Record<string, Array<{ value: any; label: string }>>;
  /** treeSelect 类型字段的 treeData，key 为字段名，格式 { title, value, key, children? } */
  treeDataMap?: Record<string, Array<{ title: string; value: string; key?: string; children?: any[] }>>;
}

function buildRules(field: FieldConfig, t: (key: string) => string): any[] {
  const rules: any[] = [];
  for (const r of field.rules || []) {
    const msg = r.messageKey ? t(r.messageKey) : r.message;
    if (r.required) {
      rules.push({ required: true, message: msg });
    } else if (r.maxLength != null) {
      rules.push({ max: r.maxLength, message: msg });
    } else if (r.type === 'email') {
      rules.push({ type: 'email', message: msg });
    } else if (r.pattern) {
      rules.push({ pattern: r.pattern, message: msg });
    }
  }
  return rules;
}

const DEFAULT_CODE_AUTO_GENERATED_KEY = 'field.customer.codeAutoGenerated';

export const SchemaFormRenderer: React.FC<SchemaFormRendererProps> = ({
  schema,
  codeField,
  codeAutoGenerated,
  codeAutoGeneratedKey = DEFAULT_CODE_AUTO_GENERATED_KEY,
  isEdit,
  optionsMap = {},
  treeDataMap = {},
}) => {
  const { t } = useTranslation();

  return (
    <>
      {schema.map((field) => {
        const label = t(field.labelKey);
        const placeholder = field.placeholderKey ? t(field.placeholderKey) : undefined;
        const rules = buildRules(field, t);
        const colSpan = field.colSpan ?? 12;
        const isCodeField = codeField && field.name === codeField;

        if (field.type === 'treeSelect') {
          const treeData = treeDataMap[field.name] ?? [];
          const extra = field.extraKey ? t(field.extraKey) : undefined;
          return (
            <ProFormTreeSelect
              key={field.name}
              name={field.name}
              label={label}
              placeholder={placeholder}
              colProps={{ span: colSpan }}
              rules={rules}
              fieldProps={{
                treeData,
                showSearch: true,
                allowClear: field.allowClear ?? true,
                treeNodeFilterProp: 'title',
                ...field.fieldProps,
              }}
              extra={extra}
            />
          );
        }

        if (field.type === 'select') {
          const optionsFromMap = optionsMap[field.name];
          const options = optionsFromMap ?? (field.options?.map((o) => ({ label: t(o.labelKey), value: o.value })) ?? []);
          const extra = field.extraKey ? t(field.extraKey) : undefined;
          const selectDisabled = (field.disabledWhenEdit && isEdit) || field.fieldProps?.disabled;
          return (
            <ProFormSelect
              key={field.name}
              name={field.name}
              label={label}
              placeholder={placeholder}
              colProps={{ span: colSpan }}
              rules={rules}
              options={options}
              extra={extra}
              fieldProps={{
                showSearch: true,
                filterOption: (input: string, option: any) =>
                  (option?.label ?? '').toString().toLowerCase().includes(input.toLowerCase()),
                allowClear: field.allowClear,
                mode: field.mode,
                optionFilterProp: 'label',
                disabled: selectDisabled,
                ...field.fieldProps,
              }}
            />
          );
        }

        if (field.type === 'textarea') {
          return (
            <ProFormTextArea
              key={field.name}
              name={field.name}
              label={label}
              placeholder={placeholder}
              colProps={{ span: colSpan }}
              rules={rules}
              fieldProps={field.fieldProps}
            />
          );
        }

        if (field.type === 'switch') {
          const extra = field.extraKey ? t(field.extraKey) : undefined;
          return (
            <ProFormSwitch
              key={field.name}
              name={field.name}
              label={label}
              colProps={{ span: colSpan }}
              extra={extra}
              initialValue={true}
            />
          );
        }

        if (field.type === 'number') {
          return (
            <ProFormDigit
              key={field.name}
              name={field.name}
              label={label}
              placeholder={placeholder}
              colProps={{ span: colSpan }}
              rules={rules}
              fieldProps={field.fieldProps}
            />
          );
        }

        if (field.type === 'date') {
          return (
            <ProFormDatePicker
              key={field.name}
              name={field.name}
              label={label}
              placeholder={placeholder}
              colProps={{ span: colSpan }}
              rules={rules}
              fieldProps={field.fieldProps}
            />
          );
        }

        if (field.type === 'datetime') {
          const extra = field.extraKey ? t(field.extraKey) : undefined;
          return (
            <ProFormDateTimePicker
              key={field.name}
              name={field.name}
              label={label}
              placeholder={placeholder}
              colProps={{ span: colSpan }}
              rules={rules}
              fieldProps={field.fieldProps}
              extra={extra}
            />
          );
        }

        // default: text
        const textFieldProps = { ...field.fieldProps };
        if (isCodeField && isEdit) {
          textFieldProps.disabled = true;
        }
        return (
          <ProFormText
            key={field.name}
            name={field.name}
            label={label}
            placeholder={isCodeField && codeAutoGenerated ? t(codeAutoGeneratedKey) : placeholder}
            colProps={{ span: colSpan }}
            rules={rules}
            fieldProps={textFieldProps}
            extra={isCodeField && !isEdit && codeAutoGenerated ? t(codeAutoGeneratedKey) : undefined}
          />
        );
      })}
    </>
  );
};
