import type { ProColumns, ProDescriptionsItemProps } from '@ant-design/pro-components'

type FieldRankMap = Record<string, number>
/** 未在对应视图 rank 登记的字段落到此段（业务列与审计列之间） */
export const DEFAULT_UNRANKED_FIELD_RANK = 91.5

function normalizeFieldKey(dataIndex: unknown, fallbackKey?: unknown): string {
  // 显式 key 优先：多字段 dataIndex 数组时仍按业务意图排序（如来源单号）。
  if (typeof fallbackKey === 'string' && fallbackKey.trim()) return fallbackKey.trim()
  if (typeof dataIndex === 'string' && dataIndex.trim()) return dataIndex.trim()
  if (Array.isArray(dataIndex) && dataIndex.length > 0) {
    return String(dataIndex[dataIndex.length - 1] ?? '').trim()
  }
  return ''
}

function sortByRank<T>(
  items: T[],
  getKey: (item: T) => string,
  rankMap: FieldRankMap,
): T[] {
  return items
    .map((item, index) => {
      const key = getKey(item)
      const rank = key && rankMap[key] != null ? rankMap[key] : DEFAULT_UNRANKED_FIELD_RANK
      return { item, index, rank }
    })
    .sort((a, b) => (a.rank === b.rank ? a.index - b.index : a.rank - b.rank))
    .map((x) => x.item)
}

/**
 * 普通表格视图（订单/头表）列序唯一真源。
 * 仓储单据除外，见 WAREHOUSE_DOC_LIST_FIELD_RANK。
 *
 * 禁止：页面内 `...GLOBAL_DOC_LIST_FIELD_RANK` 浅覆盖另起 map。
 * 新增/调序：只改本对象；同类字段必须落在同一段位。
 *
 * 段位约定（语义聚类）：
 * - 10–14 单据名称 / 编号 / 主标识叠列；报工：workOrderStacked→operation；返工：product_name_code_stacked→rework_type→original_work_order_code；异常单据：exception_doc_work_order_code→物料/计划结束；检验四单据（同来料）：quality_inspection_kind→inspection_code→第二业务叠列→quality_inspection_material；设备单据：单号→设备/路线/计划名
 * - 15–19 伙伴主称谓（客户/供应商等，非叠列时）；销售/项目上下文：project_name
 * - 20–29 类型类（合同类型、预测周期、版本、业务模式、分类等）；工单委外：owo_product_stacked→priority；异常：exception_type/alert_level/severity；设备：fault/repair/plan 类型→级别/结果标识
 * - 30–49 品种数 / 数量 / 金额 / 价税度量；报工：work_hours(32) → worker_name(32.5)；work_start_end_stacked(67.05)→reported_at
 * - 50–59 下推 / 进度类
 * - 60–74 时间相关（业务日、计划日、跟进日等）；设备：点检/巡检/故障/维修/执行/调拨/报废/校准日
 * - 75–84 责任人 / 正文 / 关联单号；设备：维修人/执行人/申请人、校准证书号
 * - 88–91.4 审核相位 / 生命周期 / 状态
 * - 91.5 未登记字段（保持声明顺序）
 * - 91.6 isActive
 * - 92–94 更新时间 / 操作
 */
export const GLOBAL_DOC_LIST_FIELD_RANK = {
  // —— 10 单据名称 / 编号 ——
  code: 10,
  name_code: 10,
  calculation_no: 10,
  order_code: 10,
  quotation_code: 10,
  contract_code: 10,
  forecast_code: 10,
  notice_code: 10,
  requisition_code: 10,
  inquiry_code: 10,
  purchase_order_code: 10,
  purchase_receipt_code: 10,
  /** 质量检验单号（来料/工序/成品/OQC） */
  inspection_code: 10,
  /** 首件检验 FAI 单号 */
  fai_code: 10,
  receipt_code: 10,
  /** 轻财务单据主标识叠列（伙伴名 + 单号） */
  finance_doc_partner_stacked: 10,
  receivable_code: 10,
  payment_code: 10,
  invoice_code: 10,
  account_code: 10,
  statement_code: 10,
  /** 系统配置：账户头像（用户名左侧） */
  avatar: 9.5,
  /** 系统配置：账户/应用/字典等编码列 */
  username: 10,
  account: 10,
  app_code: 10,
  dict_code: 10,
  locale: 10,
  return_code: 10,
  change_code: 10,
  project_code: 10,
  requirement_code: 10,
  review_code: 10,
  fmea_code: 10,
  /** 轻办公：申请/采买/模板/计划/证照编码（asset_code 见资产段） */
  request_code: 10,
  purchase_code: 10,
  template_code: 10,
  plan_code: 10,
  record_code: 10,
  license_code: 10,
  document_code: 10,
  document_type: 21,
  demand_code: 10,
  computation_code: 10,
  /** 需求变更（重排任务）编码 */
  task_code: 10,
  ticket_code: 10,
  batchNo: 10,
  serialNo: 10,
  photo_file_uuid: 10.2,
  forecast_name: 10.3,
  name: 10.4,
  title: 10.4,
  shortName: 10.5,
  source_code: 10.6,
  /** 报工等：工单名称/编号叠列（列上须设 key=workOrderStacked） */
  workOrderStacked: 10,
  /** 返工工单：产品名称/返工单编号叠列 */
  product_name_code_stacked: 10,
  /** 报工等：工序紧跟主标识，固定为第二业务列 */
  operation_name: 11,
  outsource_operation: 11.1,
  /** 工序委外：供应商/单号叠列 → 工序名称/工单编号叠列（第二业务列） */
  supplier_code_stacked: 10,
  operation_work_order_stacked: 11,
  /** 返工工单：返工类型 → 原工单号（第二、第三业务列） */
  rework_type: 11,
  original_work_order_code: 12,
  /**
   * 发货/收货通知、销退/采退：仓库与关联单号紧跟主标识（列上须设同名 key）。
   * 销售：出库仓库 + 销售订单/关联单据；采购：入库仓库 + 采购订单/关联单据。
   */
  outbound_warehouse: 12,
  inbound_warehouse: 12,
  sales_return_warehouse: 12,
  purchase_return_warehouse: 12,
  shipment_sales_order_code: 12.5,
  receipt_purchase_order_code: 12.5,
  sales_return_related_docs: 12.5,
  purchase_return_related_docs: 12.5,

  // —— 15 伙伴主称谓 / 项目上下文 ——
  customer_name: 15,
  partnerName: 15,
  partnerId: 15.1,
  supplier_name: 15.2,
  /** 客户/供应商价格本：伙伴叠列 → 物料叠列 → 伙伴料号/品名 */
  price_book_material_stacked: 15.5,
  partnerMaterialCode: 15.6,
  partnerMaterialName: 15.7,
  /** 订单评审等：项目名称紧跟客户，勿落 75+ 偶发段 */
  project_name: 16,

  /**
   * 异常单据（缺料/延期/质量）：工单编号 → 第二业务列（物料叠列 / 计划结束）→ 类型/级别 → …
   * 异常处理流程：exception_doc_work_order_code → exception_process_type → exception_process_steps
   */
  exception_doc_work_order_code: 10,
  exception_material_stacked: 11,
  exception_planned_end: 11,
  /** 异常处理流程：类型（filled）→ 步骤节点轴 */
  exception_process_type: 11,
  exception_process_steps: 12,
  /**
   * 检验四单据列表段位（以来料检验为准，四页共用同一 map，勿页面浅覆盖）：
   * inspection_code → quality_inspection_kind → supplierReceipt / quality_inspection_partner_stacked
   * → quality_inspection_material → 数量类 → quality_inspection_extra → downstream_push_progress
   * → inspector_name → lifecycle
   *
   * 不良处理：code → nc_source_inspection → operation_work_order_stacked → quality_inspection_material
   * → nc_defect_type → disposition → defect_quantity → defect_reason → 降级/回用关联 → lifecycle → action
   */
  /** 检验类型（简易 / 方案），不含勾选列时的第二列（紧挨单号后） */
  quality_inspection_kind: 10.5,
  /** 不良处理：源检验单（紧跟台账编号） */
  nc_source_inspection: 10.6,
  supplierReceipt: 11,
  quality_inspection_partner_stacked: 11,
  quality_inspection_material: 12,
  /**
   * 8D 管理：标题/编号叠列 → 严重度 → 阶段节点轴 → 来源 → 负责人 → 验证结果 → 计划完成
   */
  eightDStacked: 10,
  eight_d_stages: 23,
  eight_d_source: 24,
  eight_d_owner: 25,
  verification_result: 26,
  /**
   * 设备/模具/工装单据：单号 → 资产编码/名称 → 类型/级别/紧急度 → 结果标识 → 日期 → 人员 → lifecycle/status → action
   */
  document_no: 10,
  fault_no: 10,
  repair_no: 10,
  plan_no: 10,
  execution_no: 10,
  requisition_no: 10,
  application_no: 10,
  route_name: 11,
  plan_name: 11,
  equipment_code: 12,
  equipment_name: 12.5,
  mold_code: 12,
  mold_name: 12.5,
  tool_code: 12,
  tool_name: 12.5,
  fault_type: 20,
  repair_type: 20,
  plan_type: 20,
  folderName: 19.5,
  folder_name: 19.5,
  drawingType: 20,
  drawing_type: 20,
  securityLevel: 20.05,
  security_level: 20.05,
  dueAt: 65,
  due_at: 65,
  returnedAt: 65.5,
  returned_at: 65.5,
  maintenance_type: 20.5,
  fault_level: 21,
  urgency: 21,
  repair_required: 22,
  has_abnormality: 23,
  execution_result: 23.5,
  repair_result: 23.5,
  trial_result: 23.5,
  /** 校准结果列 dataIndex 为 result，须设 key=equipment_calibration_result */
  equipment_calibration_result: 23.5,
  purpose: 40,
  check_date: 60,
  patrol_date: 60,
  fault_date: 60,
  repair_date: 60,
  execution_date: 60,
  transfer_date: 60,
  scrap_date: 60,
  calibration_date: 60,
  maintenance_date: 60,
  trial_date: 60,
  borrow_date: 60,
  return_date: 60,
  certificate_no: 81,
  repairer_name: 76.6,
  executor_name: 76.6,
  applicant_name: 76.7,
  /**
   * 物流：货运单/运费单 → 主单号 → 方向/类型 → 承运商 → 运单号 → 金额/应付 → lifecycle
   * 主数据：车牌/承运商名码/驾驶员名码 → 类型/归属 → 联系人 → 启用/状态 → action
   */
  bill_code: 10,
  plate_number: 10,
  logistics_carrier_stacked: 10,
  logistics_driver_stacked: 10,
  business_direction: 20,
  transport_mode: 20.1,
  vehicle_type: 20,
  carrier_type: 20,
  service_hotline: 20.5,
  ownership: 21,
  carrier_name: 22,
  logistics_vehicle_driver_stacked: 22.5,
  tracking_number: 23,
  freight_route_stacked: 24,
  planned_depart_at: 60,
  planned_arrive_at: 60.1,
  payable_code: 24,
  contact_name: 77,
  is_enabled: 91.6,
  review_status: 90,
  lifecycle: 91,
  /**
   * 售后：工单/安装/维修/派工/备件/结算/回访/装机档案
   * 主单号(+客户) → 类型/方式 → 来源/工程师 → 时间 → lifecycle
   */
  asset_code: 10,
  job_code: 10,
  dispatch_code: 10,
  settlement_code: 10,
  visit_code: 10,
  after_sales_ticket_stacked: 10,
  after_sales_install_stacked: 10,
  after_sales_asset_stacked: 10,
  repair_mode: 20.4,
  supply_source: 20.4,
  visit_method: 20.4,
  current_stage_key: 23,
  engineer_name: 76.3,
  satisfaction_score: 35,
  planned_start_at: 71,
  visited_at: 71,
  site_address: 77.6,
  serial_number: 28,
  /**
   * 绩效：主数据名码/员工叠列 → 类型 → 数量金额 → 日期/时段 → 启用/汇总状态 → action
   */
  performance_name_code_stacked: 10,
  performance_employee_stacked: 10,
  performance_dept_pos_stacked: 10,
  performance_holiday_stacked: 10,
  calc_mode: 20.4,
  description: 82,
  hourly_rate: 34.05,
  default_piece_rate: 34.15,
  base_salary: 34.25,
  overtimeDate: 60,
  startAt: 70,
  endAt: 70.5,
  stationId: 22,
  reason: 82.1,
  // —— 20 类型类（同类靠拢，均在数量之前）——
  /** 不良处理：缺陷类型 / 处置方式 */
  nc_defect_type: 20,
  disposition: 21,
  /** 质量异常等：异常子类型（非流程页首列） */
  exception_type: 20,
  exception_work_order_code: 21,
  alert_level: 22,
  severity: 22,
  /**
   * MRP 例外收件箱：严重级 → 说明 → 物料叠列 → 计算单 → 分桶日 → 关联单号 → 计算完成
   */
  mrp_inbox_severity: 20,
  mrp_inbox_message: 21,
  mrp_inbox_material: 22,
  mrp_inbox_computation: 23,
  mrp_inbox_bucket_date: 24,
  mrp_inbox_document: 25,
  mrp_inbox_computed_at: 26,
  /** 快数采：连接/点位/规则/边缘类型与健康类 MarkerTag 列 */
  tag_key: 10.15,
  connection_type: 20,
  protocol: 20.05,
  rule_type: 20.1,
  value_type: 20.15,
  map_target: 20.2,
  health_status: 22.1,
  agent_status: 22.15,
  is_online: 91.55,
  last_seen_at: 70,
  last_agent_heartbeat_at: 70.1,
  contract_type: 20,
  forecast_period: 20,
  period: 20,
  forecast_type: 20.2,
  business_mode: 20.2,
  /** 需求变更：重排模式（净变更/全量/what-if） */
  mode: 20.2,
  source_type: 20.3,
  version_no: 20.5,
  version: 20.5,
  change_version: 20.55,
  holidayType: 21,
  category: 21,
  review_type: 21,
  fmea_type: 21,
  demand_type: 21,
  calculation_type: 21,
  /** 成本核算台账：工单单号紧跟核算类型（列上须设 key=cost_calculation_work_order_code） */
  cost_calculation_work_order_code: 21.05,
  calc_type: 21.1,
  target_type: 21.2,
  cost_item_type: 21.3,
  /** 工单委外：产品名称/编码叠列（列上须设 key=owo_product_stacked），优先级紧随其后 */
  owo_product_stacked: 21.9,
  priority: 22,
  activity_type_code: 22,
  /** 客户跟进：跟进内容紧跟跟进方式；售后工单等同名字段同段 */
  content: 22.05,
  request_type: 22.1,
  pool_status: 22.5,
  poolStatus: 22.5,
  /** 客户池：归属业务员 / 协作人 / 联系人电话 紧跟池状态 */
  pool_salesman_name: 22.6,
  collaborators: 22.7,
  pool_contact_phone_stacked: 22.8,
  risk_level: 22.5,
  requirement_source_type: 23,
  change_category: 23,
  calculation_status: 23.5,
  /** 轻财务：开票/收票状态（MarkerTag） */
  invoice_status: 23.6,
  batch_no: 25,

  // —— 30 品种数 / 数量 / 金额 ——
  items_count: 30,
  total_quantity: 31,
  quantity: 31,
  required_quantity: 31,
  available_quantity: 31.1,
  shortage_quantity: 31.2,
  delay_days: 31,
  outsource_quantity: 31.1,
  received_quantity: 31.2,
  inspection_quantity: 31.3,
  sample_qty: 31.3,
  qualified_quantity: 31.4,
  unqualified_quantity: 31.5,
  /** 不良处理：不合格数量（与检验 unqualified_quantity 同段） */
  defect_quantity: 31.5,
  /** 检验四单据：数量类之后、下推进度之前的专属结论列（如 OQC 放行） */
  quality_inspection_extra: 32,
  reported_quantity: 31.6,
  total_hours: 32,
  standardHours: 32,
  /** 报工工时；生产人员紧随其后 */
  work_hours: 32,
  worker_name: 32.5,
  total_pieces: 32.1,
  unit_price: 33,
  unitPrice: 33,
  variantPrices: 33.1,
  standard_value: 33.2,
  unit: 33.3,
  total_amount: 34,
  /** 工单委外：已发料数量（紧接金额；下推进度 50 须排在其后） */
  issued_quantity: 34.5,
  issuedQuantity: 34.5,
  time_amount: 34.1,
  piece_amount: 34.2,
  released_amount: 34.3,
  delta_amount: 34.4,
  weight: 35,
  rate: 35.1,
  kpi_score: 35.2,
  kpi_coefficient: 35.3,
  material_cost: 36,
  labor_cost: 36.1,
  manufacturing_cost: 36.2,
  unit_cost: 36.3,
  total_cost: 36.4,
  effective_date: 37,
  price_date: 37.05,
  priceDate: 37.05,
  /** 异常单据：延期原因 / 问题描述 */
  delay_reason: 40,
  problem_description: 40,
  defect_reason: 40,
  /** 异常单据：建议动作 */
  suggested_action: 50,

  // —— 50 下推 / 进度（工单委外：须在 issued_quantity 34.5 之后）——
  work_order_push_progress: 50,
  order_push_progress: 50,
  downstream_push_progress: 50,
  computation_push_progress: 50,
  /** 发货/收货通知：出库转单 / 入库转单，紧挨关联单号之后、下推进度之前 */
  shipment_outbound_conversion: 13,
  receipt_inbound_conversion: 13,
  outbound_push_progress: 50,
  inbound_push_progress: 50,
  delivery_progress: 51,
  receipt_progress: 51,

  // —— 60 时间相关 ——
  order_date: 60,
  quotation_date: 60,
  contract_date: 60,
  calculation_date: 60,
  holidayDate: 60,
  start_date: 60.5,
  end_date: 60.6,
  planned_start_date: 61,
  planned_end_date: 61.1,
  /** 返工等：计划开始/结束叠列 */
  planned_start_end_stacked: 61,
  /** 工单委外 / 工序委外：计划起止叠列 */
  planned_range_stacked: 61,
  required_date: 61.2,
  delivery_date: 62,
  planned_ship_date: 62.1,
  planned_receipt_date: 62.1,
  valid_to: 62.5,
  effectiveFrom: 63,
  effectiveTo: 63.1,
  productionDate: 63.2,
  expiryDate: 63.3,
  factoryDate: 63.4,
  return_time: 64,
  notified_at: 64.1,
  assigned_at: 64.2,
  recycle_at: 64.3,
  applied_at: 64.4,
  issued_at: 64.5,
  issuedAt: 64.5,
  recalled_at: 64.6,
  recalledAt: 64.6,
  scheduled_at: 65,
  review_date: 65,
  computation_start_time: 65.1,
  computation_end_time: 65.2,
  started_at: 65.1,
  finished_at: 65.2,
  /** 需求变更：创建时间（非固定列末位，列用 key 避开全局 created_at=93） */
  task_created_at: 88,
  timeRange: 66,
  occurred_at: 67,
  registered_at: 67,
  /** 报工：工序开始/完成时间叠列（须在 reported_at / 更新时间之前） */
  work_start_end_stacked: 67.05,
  reported_at: 67.1,
  next_follow_up_at: 68,
  last_follow_up_at: 68.1,
  closed_at: 68.5,
  crossesMidnight: 69,

  // —— 75 责任人 / 正文 / 关联 / 物料（列表偶发列）——
  salesman_name: 75,
  salesman_quotation_date_stacked: 75,
  salesman_id: 75.1,
  salesmanName: 75,
  salesmanId: 75.1,
  buyer_name: 75.5,
  buyer_id: 75.55,
  buyerName: 75.5,
  buyerId: 75.55,
  employee_name: 76,
  reviewer_name: 76.1,
  owner_name: 76.2,
  inspector_name: 76.4,
  issued_by_name: 76.45,
  issuedByName: 76.45,
  recalled_by_name: 76.46,
  recalledByName: 76.46,
  responsible_person_name: 76.5,
  inspectorName: 76.4,
  contact_person: 77,
  contactPerson: 77,
  contactTitle: 77.1,
  phone: 77.2,
  contact_phone: 77.2,
  mobile: 77.3,
  email: 77.4,
  address: 77.5,
  department_name: 78,
  position_name: 78.1,
  warehouse_name: 78.5,
  product_code: 79,
  product_name: 79.1,
  material_code: 79.2,
  materialCode: 79.2,
  material_name: 79.3,
  materialName: 79.3,
  material_id: 79.35,
  materialId: 79.35,
  materialModel: 79.4,
  target_code: 80.1,
  target_name: 80.2,
  downgrade_material_name: 80.3,
  other_inbound_id: 81.4,
  sales_order_code: 81,
  work_order_code: 81.1,
  source_order_code: 81.2,
  sales_delivery_code: 81.3,
  change_reason: 82,
  failure_reason: 82.1,

  // —— 88 审核 / 生命周期 / 系统 ——
  audit_phase: 89,
  phase: 89,
  /** 需求变更：审核态（右固定，紧挨 lifecycle 之前） */
  approval_status: 90,
  lifecycle_stage: 90.5,
  status: 91,
  is_active: 91.6,
  isActive: 91.6,
  updatedAt: 92,
  createdAt: 93,
  updated_at: 92,
  created_at: 93,
  action: 94,
} satisfies FieldRankMap

/**
 * @deprecated 与 GLOBAL_DOC_LIST_FIELD_RANK 同一对象；保留别名兼容旧 import。
 */
export const SALES_DOC_LIST_FIELD_RANK = GLOBAL_DOC_LIST_FIELD_RANK

/**
 * 明细表格视图列序唯一真源（UniTable detailTable）。
 * 禁止套用 GLOBAL_DOC_LIST_FIELD_RANK；禁止页面浅覆盖另起 map。
 *
 * 段位约定（与头表语义对齐）：
 * - 10 单据主标识
 * - 20 产品 / 物料（品种）
 * - 25 类型类（周期/类型等行上带回）
 * - 30–39 数量 / 价税 / 已交未交
 * - 50–59 行下推 / 进度
 * - 60–69 时间
 * - 88–94 更新时间 / 审核 / 生命周期 / 操作
 */
export const GLOBAL_DOC_DETAIL_TABLE_FIELD_RANK = {
  // 单据标识
  quotation_code: 10,
  order_code: 10,
  contract_code: 10,
  forecast_code: 10,
  inquiry_code: 10,
  purchase_order_code: 10,
  requisition_code: 10,
  notice_code: 10,
  // 品种 / 物料
  material_display: 20,
  material_name: 20,
  material_code: 20.1,
  materialName: 20,
  materialCode: 20.1,
  // 类型类
  forecast_period: 25,
  forecast_type: 25.2,
  // 数量 / 金额
  quote_quantity: 30,
  required_quantity: 30,
  contract_quantity: 30,
  forecast_quantity: 30,
  ordered_quantity: 30,
  quantity: 30,
  unit_price: 31,
  unitPrice: 31,
  tax_rate: 32,
  total_amount: 33,
  item_amount: 33,
  total_price: 33,
  delivered_quantity: 34,
  received_quantity: 34,
  remaining_quantity: 35,
  outstanding_quantity: 35,
  bom_check: 36,
  // 行下推 / 进度
  line_push_progress: 50,
  line_delivery_progress: 51,
  line_release_progress: 52,
  line_receipt_progress: 53,
  // 时间
  quotation_date: 60,
  contract_date: 60,
  forecast_date: 60,
  order_date: 60,
  delivery_date: 61,
  required_date: 62,
  quote_deadline: 63,
  // 系统尾部
  updated_at: 88,
  audit_phase: 89,
  lifecycle_stage: 90,
  status: 91,
  action: 94,
} satisfies FieldRankMap

export function alignProColumns<T extends Record<string, unknown>>(
  columns: ProColumns<T>[],
  rankMap: FieldRankMap = GLOBAL_DOC_LIST_FIELD_RANK,
): ProColumns<T>[] {
  return sortByRank(
    columns,
    (col) => normalizeFieldKey(col.dataIndex as unknown, col.key as unknown),
    rankMap,
  )
}

/**
 * 详情抽屉「基本信息」字段序唯一真源（试点：销售订单）。
 * 页面用 alignDescriptionColumns(cols, GLOBAL_DOC_DETAIL_BASIC_FIELD_RANK)，禁止手排 Descriptions。
 * 本单号用单据自己的 *_code（10）；关联他单用 sales_order_code / quotation_code_link / linked_contract_code，
 * 或列上显式 key（normalizeFieldKey 优先 key）。
 *
 * 段位（3 列栅格，对照 SalesOrderDetailBasicPane）：
 * - 10–19 本单号 → 单据日 → 交期/有效期 → 版本
 * - 20–29 客户/供应商 → 联系人 → 电话
 * - 40–49 关联单号 → 收货地址（span 3）
 * - 50–59 责任人 → 交货方式 → 付款条件 → 币种
 * - 60–69 计价类型 → 折扣 → 数量/金额/费用
 * - 80 备注（自定义字段插在金额与备注之间，不进 map）
 * - 88–91 状态（协作区已有生命周期则基本信息省略）
 * - 92–94 创建/更新
 */
export const GLOBAL_DOC_DETAIL_BASIC_FIELD_RANK = {
  quotation_code: 10,
  /** 订单评审单号（与 PLM review_code 列表段位同为 10） */
  review_code: 10,
  contract_code: 10,
  order_code: 10,
  forecast_code: 10,
  notice_code: 10,
  change_code: 10,
  return_code: 10,
  receipt_code: 10,
  payment_code: 10,
  calculation_no: 10,
  inbound_code: 10,
  outbound_code: 10,
  picking_code: 10,
  borrow_code: 10,
  transfer_code: 10,
  registration_code: 10,
  delivery_code: 10,
  code: 10,
  demand_code: 10,
  computation_code: 10,
  inquiry_code: 10,
  requisition_code: 10,
  work_order_code: 10,
  rework_code: 10,
  outsource_order_code: 10,
  box_no: 10,
  ticket_code: 10,
  asset_code: 10,
  job_code: 10,
  dispatch_code: 10,
  settlement_code: 10,
  visit_code: 10,
  inspection_code: 10,
  report_code: 10,
  document_code: 10,
  node_id: 10,
  node_type: 20,
  document_type: 21,
  order_date: 11,
  quotation_date: 11,
  review_date: 11,
  contract_date: 11,
  inquiry_date: 11,
  requisition_date: 11,
  receipt_date: 11,
  payment_date: 11,
  calculation_date: 11,
  inbound_date: 11,
  outbound_date: 11,
  stocktaking_date: 11,
  transfer_date: 11,
  registration_date: 11,
  period: 11.15,
  forecast_name: 11.2,
  demand_name: 11.2,
  requisition_name: 11.2,
  work_order_name: 11.2,
  title: 11.3,
  delivery_date: 12,
  planned_delivery_date: 12,
  expected_return_date: 12.08,
  due_date: 12.05,
  dueAt: 12.06,
  due_at: 12.06,
  returnedAt: 12.07,
  returned_at: 12.07,
  purpose: 40.1,
  planned_ship_date: 12,
  planned_receipt_date: 12,
  required_date: 12,
  start_date: 12,
  planned_start_date: 12,
  planned_start_time: 12,
  valid_until: 13,
  valid_from: 13,
  valid_to: 13,
  quote_deadline: 13,
  end_date: 13,
  planned_end_date: 13,
  planned_end_time: 13,
  notified_at: 14,
  applied_at: 14,
  issued_at: 14.02,
  issuedAt: 14.02,
  recalled_at: 14.03,
  recalledAt: 14.03,
  receipt_time: 14,
  borrow_time: 14,
  delivery_time: 14,
  sent_at: 14,
  processed_at: 14.12,
  executed_at: 14.15,
  registered_at: 14.05,
  reported_at: 14.06,
  accepted_at: 14.07,
  warranty_start_at: 14.08,
  warranty_end_at: 14.09,
  started_at: 14.12,
  checkin_at: 14.13,
  visited_at: 14.16,
  closed_at: 14.22,
  planned_start_at: 12.2,
  planned_end_at: 13.2,
  actual_start_at: 14.11,
  actual_end_at: 14.21,
  return_time: 14,
  occurred_at: 14,
  inspection_time: 14.05,
  bound_at: 14,
  actual_start_date: 14.1,
  actual_end_date: 14.2,
  next_follow_up_at: 14.2,
  computation_start_time: 14.3,
  computation_end_time: 14.4,
  version_no: 14.5,
  change_version: 14.6,

  employee_name: 20,
  customer_name: 20,
  supplier_name: 20,
  project_name: 20.05,
  urgency: 20.08,
  risk_level: 20.09,
  customer_contact: 21,
  supplier_contact: 21,
  customer_phone: 22,
  supplier_phone: 22,
  forecast_period: 20,
  contract_type: 20,
  change_category: 20,
  return_type: 20,
  activity_type_code: 20,
  demand_type: 20,
  business_mode: 20.1,
  source_type: 20.3,
  order_type: 20.4,
  request_type: 20.42,
  repair_mode: 20.43,
  supply_source: 20.44,
  visit_method: 20.45,
  warranty_status: 20.5,
  warranty_policy: 20.55,
  warranty_months: 21.5,
  serial_number: 21.45,
  receipt_type: 20.4,
  outbound_type: 20.4,
  reason_type: 20.4,
  stocktaking_type: 20.4,
  line_granularity: 20.55,
  production_mode: 20.5,
  manufacturing_mode: 20.6,
  rework_type: 20.5,
  exception_type: 20,
  product_name: 20.7,
  material_name: 20.72,
  material_spec: 20.74,
  product_code: 20.8,
  material_code: 20.82,
  operation_name: 20.9,
  effective_batch_no: 21.2,
  batch_no: 21.25,
  batch_number: 21.26,
  effective_serial_no: 21.4,
  alert_level: 21.6,
  severity: 21.7,
  quality_status: 21.75,
  inspection_result: 21.85,
  /** 首件检验结论（合格/不合格，MarkerTag） */
  conclusion: 21.84,
  defect_type: 21.86,
  disposition: 21.87,
  release_decision: 21.9,
  delay_reason: 22,
  business_direction: 20,
  transport_mode: 20.1,
  carrier_name: 22,
  driver_name: 50.28,
  driver_phone: 22.6,
  vehicle_plate: 51.12,
  origin_address: 45,
  sender_phone: 45.02,
  destination_address: 45.05,
  recipient_phone: 45.07,
  planned_depart_at: 12,
  planned_arrive_at: 12.1,
  actual_depart_at: 14.05,
  actual_arrive_at: 14.15,
  signed_by: 50.23,
  receipt_result: 50.24,
  remark: 80,

  quotation_code_link: 40,
  nc_source_inspection: 40.15,
  incoming_inspection_code: 40.2,
  process_inspection_code: 40.3,
  finished_goods_inspection_code: 40.4,
  linked_contract_code: 40,
  linked_source_code: 40,
  sales_order_code: 41,
  after_sales_ticket_code: 41.5,
  service_asset_code: 41.6,
  install_execution_code: 41.7,
  sales_return_code: 42.1,
  source_order_code: 41,
  purchase_order_code: 41.2,
  linked_work_order_code: 41.4,
  original_work_order_code: 41.4,
  sales_delivery_code: 42,
  other_inbound_id: 42.15,
  purchase_receipt_code: 42.2,
  shipment_notice_code: 42.4,
  linked_picking_code: 42.6,
  linked_demand_code: 43,
  linked_computation_code: 44,
  computation_type: 20.2,
  calculation_type: 20.25,
  shipping_address: 45,
  install_address: 45.06,
  site_address: 45.07,
  problem_description: 45.2,
  reason_desc: 45.3,
  transfer_reason: 45.4,

  salesman_name: 50,
  buyer_name: 50,
  applicant_name: 50.2,
  returner_name: 50,
  worker_name: 50.3,
  inspector_name: 50.32,
  owner_name: 50.34,
  engineer_name: 50.44,
  visitor_name: 50.46,
  recorded_by_name: 50.4,
  operator_name: 50.36,
  receiver_name: 50.22,
  deliverer_name: 50.24,
  borrower_name: 50.25,
  department: 50.26,
  processed_by_name: 50.38,
  executed_by_name: 50.42,
  assigned_to_name: 50.5,
  suggested_action: 50.52,
  alternative_material_name: 50.72,
  downgrade_material_name: 50.73,
  downgrade_warehouse_name: 51.02,
  priority: 50.6,
  shipping_method: 51,
  warehouse_name: 51,
  bank_account: 51.08,
  bank_account_note: 51.09,
  from_warehouse_name: 51,
  to_warehouse_name: 51.05,
  carrier: 51.1,
  tracking_number: 51.15,
  workshop_name: 51.2,
  work_center_name: 51.4,
  workstation_name: 51.6,
  payment_terms: 52,
  payment_method: 52.2,
  settlement_type: 52.3,
  currency_code: 53,

  price_type: 60,
  discount_amount: 61,
  quantity: 62,
  total_quantity: 62,
  total_hours: 62.15,
  total_duration_hours: 62.16,
  total_duration_seconds: 62.17,
  total_pieces: 62.16,
  item_count: 62.02,
  satisfaction_score: 62.95,
  total_items: 62.05,
  counted_items: 62.06,
  total_differences: 62.07,
  completed_quantity: 62.1,
  qualified_quantity: 62.2,
  unqualified_quantity: 62.3,
  defect_quantity: 62.32,
  reported_quantity: 62.4,
  outsource_quantity: 62.5,
  packing_quantity: 62.6,
  inspection_quantity: 62.65,
  required_quantity: 62.7,
  available_quantity: 62.8,
  shortage_quantity: 62.85,
  delay_days: 62.9,
  time_amount: 63.12,
  piece_amount: 63.13,
  kpi_score: 63.14,
  kpi_coefficient: 63.15,
  claim_amount: 63.05,
  warranty_free_amount: 63.07,
  chargeable_amount: 63.08,
  total_amount: 63,
  total_difference_amount: 63.1,
  tax_rate: 63.2,
  tax_amount: 63.4,
  net_amount: 63.6,
  material_cost: 64.2,
  labor_cost: 64.3,
  manufacturing_cost: 64.4,
  total_cost: 64.5,
  total_cost_amount: 64.51,
  unit_cost: 64.6,
  total_fee_amount: 64,
  released_amount: 65,
  settled_amount: 65.1,
  remaining_amount: 66,
  unsettled_amount: 66.1,
  before_total_amount: 67,
  after_total_amount: 68,
  delta_amount: 69,

  defect_reason: 70.4,
  root_cause: 70,
  corrective_action: 71,
  preventive_action: 72,
  responsible_person_name: 73,
  planned_completion_date: 74,
  actual_completion_date: 75,
  verification_result: 76,
  handled_by_name: 77,
  handled_at: 77.1,

  change_reason: 79,
  return_reason: 79,
  content: 79.2,
  fault_description: 79.3,
  diagnosis_result: 79.4,
  resolution: 79.5,
  completion_notes: 79.6,
  feedback: 79.7,
  notes: 80,
  review_remarks: 80.1,
  remarks: 80,
  error_message: 80.3,
  release_note: 80.2,
  attachments: 81,
  status: 91,
  process_status: 91,
  calculation_status: 91.2,

  created_by_name: 92,
  created_at: 92.1,
  reviewer_name: 92.2,
  review_time: 92.3,
  reviewed_at: 92.35,
  updated_by_name: 93,
  updated_at: 93.1,
} satisfies FieldRankMap

export function alignDescriptionColumns<T extends Record<string, unknown>>(
  columns: ProDescriptionsItemProps<T>[],
  rankMap: FieldRankMap = GLOBAL_DOC_DETAIL_BASIC_FIELD_RANK,
): ProDescriptionsItemProps<T>[] {
  return sortByRank(
    columns,
    (col) => normalizeFieldKey(col.dataIndex as unknown, col.key as unknown),
    rankMap,
  )
}

/**
 * @deprecated Prefer GLOBAL_DOC_DETAIL_BASIC_FIELD_RANK.
 */
export const SALES_DOC_DETAIL_BASIC_FIELD_RANK = GLOBAL_DOC_DETAIL_BASIC_FIELD_RANK

/**
 * 基础资料详情「基本信息」字段序。须显式传入 alignDescriptionColumns(cols, MASTER_DATA_DETAIL_BASIC_FIELD_RANK)，
 * 禁止用业务单据 GLOBAL_DOC_DETAIL_BASIC_FIELD_RANK（默认）。
 * 段位：编码 → 名称 → 简称/规格 → 类型 → 联系 → 启用 → 地址/说明 → 系统。
 */
export const MASTER_DATA_DETAIL_BASIC_FIELD_RANK = {
  code: 10,
  username: 10,
  template_code: 10,
  mainCode: 10,
  materialCode: 10,
  material_code: 10,
  equipment_code: 10,
  mold_code: 10,
  tool_code: 10,
  plan_code: 10,
  name: 11,
  full_name: 11,
  template_name: 11,
  material_name: 11,
  equipment_name: 11,
  plan_name: 11,
  shortName: 12,
  short_name: 12,
  spec: 12,
  specification: 12,
  baseUnit: 12.2,
  brand: 12.3,
  model: 12.4,
  texture: 12.55,
  partnerName: 11.05,
  tag_key: 10,
  connection_type: 20,
  value_type: 20,
  protocol: 20,
  map_target: 20.5,
  health_status: 41,
  is_online: 41,
  last_seen_at: 33.3,
  last_health_at: 33.4,
  external_device_id: 12.9,
  partnerMaterialCode: 12.7,
  partnerMaterialName: 12.8,
  unit: 12.25,
  priceType: 20.6,
  taxRate: 50.29,
  effectiveFrom: 13,
  effectiveTo: 13.1,
  version: 12.5,
  revision: 12.6,
  bomCode: 10,
  bom_code: 10,
  category: 20,
  groupId: 20,
  type: 20,
  plantName: 20.15,
  plant_name: 20.15,
  warehouseName: 20.16,
  device_id: 20.16,
  warehouse_name: 20.16,
  workshopName: 20.17,
  workshop_name: 20.17,
  storageAreaName: 20.18,
  workCenterName: 20.19,
  work_center_name: 20.19,
  productionLineName: 20.21,
  processRouteName: 20.22,
  rule_type: 20,
  cost_type: 20.1,
  calculation_method: 20.2,
  allocation_basis: 20.3,
  source_module: 20.4,
  wip_valuation_method: 20.5,
  warehouseType: 20,
  warehouse_type: 20,
  plan_type: 20,
  folderName: 19.5,
  folder_name: 19.5,
  drawingType: 20,
  drawing_type: 20,
  securityLevel: 20.05,
  security_level: 20.05,
  operationId: 20,
  operation_id: 20,
  materialId: 20,
  material_id: 20,
  approvalStatus: 41,
  approval_status: 41,
  plate_number: 10,
  vehicle_type: 20,
  carrier_type: 20,
  ownership: 20.5,
  contact_name: 30,
  contact_phone: 31,
  service_hotline: 31.5,
  license_number: 32,
  is_enabled: 40,
  load_capacity: 50.2,
  volume_capacity: 50.3,
  settlement_method: 50.4,
  status: 41,
  remark: 51,
  contactPerson: 30,
  contact_person: 30,
  contactTitle: 30.4,
  members: 30.5,
  phone: 31,
  email: 32,
  barcode: 32.5,
  salesmanName: 33,
  salesman_name: 33,
  assignedAt: 33.1,
  lastFollowUpAt: 33.2,
  poolStatus: 33.05,
  recycleAt: 33.06,
  isActive: 40,
  is_active: 40,
  shelfLifeManaged: 40.3,
  isGiftable: 40.4,
  batchManaged: 40.5,
  variantManaged: 40.6,
  holidayDate: 12,
  holiday_date: 12,
  holidayType: 20,
  holiday_type: 20,
  startTime: 21,
  endTime: 21.1,
  crossesMidnight: 21.2,
  standardHours: 50.2,
  department_name: 20,
  position_name: 21,
  rate: 50.25,
  calc_type: 20,
  weight: 50.3,
  formula_json: 51.2,
  employee_name: 11,
  calc_mode: 20,
  piece_rate_mode: 20.5,
  hourly_rate: 50.26,
  default_piece_rate: 50.3,
  base_salary: 50.4,
  effective_from: 13,
  effective_to: 13.1,
  effectiveDate: 13,
  effective_date: 13,
  expiryDate: 13.1,
  expiry_date: 13.1,
  address: 50,
  taxRegistrationNo: 50.08,
  invoiceTitle: 50.09,
  invoiceAddress: 50.1,
  invoicePhone: 50.11,
  invoiceBankName: 50.12,
  invoiceBankAccount: 50.13,
  unitPrice: 50.27,
  referenceCost: 50.28,
  volume: 50.32,
  countryOfOrigin: 50.35,
  customsCode: 50.36,
  workstationIds: 50.62,
  description: 51,
  remarks: 51,
  content: 51,
  file: 50.5,
  supplementaryFiles: 50.55,
  materials: 50.56,
  linkedBom: 50.57,
  defectTypes: 50.6,
  defect_types: 50.6,
  defaultOperatorNames: 50.7,
  default_operator_names: 50.7,
  operation_sequence: 50.8,
  operationSequence: 50.8,
  isConfigurable: 40.2,
  is_configurable: 40.2,
  alternativeGroupId: 50.15,
  alternative_group_id: 50.15,
  approvedBy: 91.2,
  approved_by: 91.2,
  approvedAt: 91.3,
  approved_at: 91.3,
  approvalComment: 51.1,
  approval_comment: 51.1,
  createdAt: 92,
  created_at: 92,
  createdByName: 92.1,
  created_by_name: 92.1,
  updatedAt: 93,
  updated_at: 93,
  updatedByName: 93.1,
  updated_by_name: 93.1,
} satisfies FieldRankMap

export function getSalesCommonFormLabels(t: (key: string) => string) {
  return {
    contact: t('app.kuaizhizao.salesOrder.customerContact'),
    phone: t('app.kuaizhizao.salesOrder.customerPhone'),
    salesman: t('app.kuaizhizao.salesOrder.salesman'),
  } as const
}
