/** 触屏工位触控尺寸 */
export const HMI_TOUCH = {
  TOUCH_MIN_SIZE: 48,
  BUTTON_MIN_HEIGHT: 60,
  FONT_MIN_SIZE: 24,
  TITLE_FONT_SIZE: 32,
  ELEMENT_MIN_GAP: 20,
  KEYBOARD_BUTTON_SIZE: 60,
  PRIMARY_BTN_HEIGHT: 80,
  PRIMARY_BTN_MIN_WIDTH: 160,
  ACTION_BTN_HEIGHT: 72,
  ACTION_BTN_MIN_WIDTH: 120,
  FOOTER_PADDING_X: 24,
  FOOTER_GAP: 16,
  LIST_ITEM_MIN_HEIGHT: 76,
  INPUT_HEIGHT: 72,
  INPUT_FONT_SIZE: 28,
  OP_CHIP_HEIGHT: 56,
  ACTION_FONT_SIZE: 22,
  LABEL_FONT_SIZE: 18,
  HEADER_BTN_HEIGHT: 48,
  HEADER_BTN_MIN_WIDTH: 120,
} as const;

/** @deprecated 使用 HMI_TOUCH */
export const TOUCH_SCREEN_CONFIG = {
  TOUCH_MIN_SIZE: HMI_TOUCH.TOUCH_MIN_SIZE,
  BUTTON_MIN_HEIGHT: HMI_TOUCH.BUTTON_MIN_HEIGHT,
  FONT_MIN_SIZE: HMI_TOUCH.FONT_MIN_SIZE,
  TITLE_FONT_SIZE: HMI_TOUCH.TITLE_FONT_SIZE,
  ELEMENT_MIN_GAP: HMI_TOUCH.ELEMENT_MIN_GAP,
  KEYBOARD_BUTTON_SIZE: HMI_TOUCH.KEYBOARD_BUTTON_SIZE,
} as const;
