"""Tortoise ORM 模块注册（运行时按应用中心启用状态加载）。"""

ORM_MODEL_MODULES: list[str] = [
    "apps.master_data.models.bom_change",
    "apps.master_data.models.customer",
    "apps.master_data.models.drawing",
    "apps.master_data.models.drawing_change",
    "apps.master_data.models.drawing_distribution",
    "apps.master_data.models.drawing_loan",
    "apps.master_data.models.employee_performance",
    "apps.master_data.models.factory",
    "apps.master_data.models.master_data_sync_binding",
    "apps.master_data.models.material",
    "apps.master_data.models.material_batch",
    "apps.master_data.models.material_code_alias",
    "apps.master_data.models.material_code_mapping",
    "apps.master_data.models.material_market_price",
    "apps.master_data.models.material_product_process",
    "apps.master_data.models.material_serial",
    "apps.master_data.models.partner_price_book",
    "apps.master_data.models.performance",
    "apps.master_data.models.process",
    "apps.master_data.models.process_route_change",
    "apps.master_data.models.product",
    "apps.master_data.models.shift_scheduling",
    "apps.master_data.models.supplier",
    "apps.master_data.models.unit",
    "apps.master_data.models.warehouse",
    "apps.master_data.models.work_calendar",
]
