/**
 * 上下游关系图中的单据节点徽块（样式与原先 DocumentTrackingRelationsBody 内联一致）
 */

import React from 'react';
import { Tag, Typography } from 'antd';
import { useTranslation } from 'react-i18next';
import type { DocumentTrackingRelation } from '../../services/documentTracking';
import type { RelationChainVariant } from './relationGraph';

export interface RelationNodeChipProps {
  variant: RelationChainVariant;
  /** 当前单中心节点 */
  documentType?: string;
  documentId?: number;
  documentCode?: string;
  relation?: DocumentTrackingRelation;
  onDocumentClick?: (type: string, id: number) => void;
}

export const RelationNodeChip: React.FC<RelationNodeChipProps> = ({
  variant,
  documentType,
  documentId,
  documentCode,
  relation,
  onDocumentClick,
}) => {
  const { t } = useTranslation();

  if (variant === 'current') {
    if (documentType == null || documentId == null) return null;
    const currentTypeLabel = t(`components.documentTrackingPanel.docType.${documentType}`, {
      defaultValue: documentType,
    });
    const currentCode = (documentCode || '').trim() || `#${documentId}`;
    return (
      <div
        style={{
          padding: '6px 10px',
          background: 'var(--ant-color-bg-container)',
          borderRadius: 6,
          border: '1px solid var(--ant-color-border)',
          whiteSpace: 'nowrap',
          flexShrink: 0,
          display: 'inline-flex',
          alignItems: 'center',
        }}
      >
        <span style={{ fontWeight: 600 }}>{`${currentTypeLabel}（${currentCode}）`}</span>
      </div>
    );
  }

  if (!relation) return null;

  const rel = relation;
  const clickable =
    !!onDocumentClick && !(variant === 'downstream' && rel.is_deleted);
  const code = (rel.code || '').trim() || `#${rel.id}`;
  const typeLabel = t(`components.documentTrackingPanel.docType.${rel.type}`, { defaultValue: rel.type });
  const primary = `${typeLabel}（${code}）`;
  const nameTrim = (rel.name || '').trim();
  const showExtraName = nameTrim && nameTrim !== code;

  return (
    <div
      style={{
        padding: '6px 10px',
        background: 'var(--ant-color-fill-alter)',
        borderRadius: 6,
        border: '1px solid var(--ant-color-border-secondary)',
        cursor: clickable ? 'pointer' : 'default',
        display: 'inline-flex',
        alignItems: 'center',
        gap: 4,
        whiteSpace: 'nowrap',
        flexShrink: 0,
      }}
      onClick={() => {
        if (!clickable) return;
        onDocumentClick?.(rel.type, rel.id);
      }}
      role={clickable ? 'button' : undefined}
    >
      <span>{primary}</span>
      {showExtraName ? (
        <span style={{ color: 'var(--ant-color-text-secondary)', marginLeft: 6 }}>{nameTrim}</span>
      ) : null}
      {variant === 'downstream' && rel.is_deleted ? (
        <Tag color="error" style={{ marginLeft: 8 }}>
          {t('components.documentTrackingPanel.relationDeleted')}
        </Tag>
      ) : null}
      {variant === 'downstream' && !rel.is_deleted && rel.is_auto_created ? (
        <Tag color="blue" style={{ marginLeft: 8 }}>
          {t('components.documentTrackingPanel.autoGenerated')}
        </Tag>
      ) : null}
      {variant === 'downstream' && !rel.is_deleted && rel.is_changed_after_link ? (
        <Tag color="warning" style={{ marginLeft: 8 }}>
          {t('components.documentTrackingPanel.relationChangedAfterLink')}
        </Tag>
      ) : null}
    </div>
  );
};

/** 空关系时的提示（与原先一致，避免 RelationLayout 重复 i18n） */
export const RelationEmptyHint: React.FC = () => {
  const { t } = useTranslation();
  return (
    <Typography.Text type="secondary" style={{ fontSize: 13 }}>
      {t('components.documentTrackingPanel.noRelations')}
    </Typography.Text>
  );
};
