"""好力 GO — 品质管理消息模板预设。"""

from apps.haoligo.constants.message_template_codes import (
    HAOLIGO_CUSTOMER_COMPLAINT_COMPLETED,
    HAOLIGO_CUSTOMER_COMPLAINT_LONG_TERM_OVERDUE,
    HAOLIGO_CUSTOMER_COMPLAINT_SUBMITTED,
    HAOLIGO_LINE_STOP_COMPLETED,
    HAOLIGO_LINE_STOP_LONG_TERM_OVERDUE,
    HAOLIGO_LINE_STOP_SUBMITTED,
    HAOLIGO_LINE_STOP_TEMPORARY_OVERDUE,
    HAOLIGO_CUSTOMER_COMPLAINT_TEMPORARY_OVERDUE,
    HAOLIGO_QUALITY_ISSUE_LONG_TERM_OVERDUE,
    HAOLIGO_QUALITY_ISSUE_COMPLETED,
    HAOLIGO_QUALITY_ISSUE_SUBMITTED,
    HAOLIGO_QUALITY_ISSUE_TEMPORARY_OVERDUE,
)

HAOLIGO_QUALITY_MESSAGE_TEMPLATE_PRESETS = [
    {
        "name": "品质问题已登记（待处理）",
        "code": HAOLIGO_QUALITY_ISSUE_SUBMITTED,
        "type": "notification",
        "content": "【品质问题】{{title}}（{{sheet_no}}）已登记，请及时处理。",
        "variables": ["title", "sheet_no"],
        "is_active": True,
    },
    {
        "name": "品质问题已处理完成",
        "code": HAOLIGO_QUALITY_ISSUE_COMPLETED,
        "type": "notification",
        "content": "【品质问题】{{title}}（{{sheet_no}}）已处理完成，已回传登记人。",
        "variables": ["title", "sheet_no"],
        "is_active": True,
    },
    {
        "name": "品质问题临时措施逾期",
        "code": HAOLIGO_QUALITY_ISSUE_TEMPORARY_OVERDUE,
        "type": "notification",
        "content": "【品质问题】{{title}}（{{sheet_no}}）临时措施已逾期，请立即跟进。",
        "variables": ["title", "sheet_no"],
        "is_active": True,
    },
    {
        "name": "品质问题长期措施逾期",
        "code": HAOLIGO_QUALITY_ISSUE_LONG_TERM_OVERDUE,
        "type": "notification",
        "content": "【品质问题】{{title}}（{{sheet_no}}）长期措施已逾期，请立即跟进。",
        "variables": ["title", "sheet_no"],
        "is_active": True,
    },
    {
        "name": "客户投诉已登记（待处理）",
        "code": HAOLIGO_CUSTOMER_COMPLAINT_SUBMITTED,
        "type": "notification",
        "content": "【客户投诉】{{title}}（{{sheet_no}}）已登记，请及时处理。",
        "variables": ["title", "sheet_no"],
        "is_active": True,
    },
    {
        "name": "客户投诉已处理完成",
        "code": HAOLIGO_CUSTOMER_COMPLAINT_COMPLETED,
        "type": "notification",
        "content": "【客户投诉】{{title}}（{{sheet_no}}）已处理完成，已回传登记人。",
        "variables": ["title", "sheet_no"],
        "is_active": True,
    },
    {
        "name": "客户投诉临时措施逾期",
        "code": HAOLIGO_CUSTOMER_COMPLAINT_TEMPORARY_OVERDUE,
        "type": "notification",
        "content": "【客户投诉】{{title}}（{{sheet_no}}）临时措施已逾期，请立即跟进。",
        "variables": ["title", "sheet_no"],
        "is_active": True,
    },
    {
        "name": "客户投诉长期措施逾期",
        "code": HAOLIGO_CUSTOMER_COMPLAINT_LONG_TERM_OVERDUE,
        "type": "notification",
        "content": "【客户投诉】{{title}}（{{sheet_no}}）长期措施已逾期，请立即跟进。",
        "variables": ["title", "sheet_no"],
        "is_active": True,
    },
    {
        "name": "停线反馈已登记（待处理）",
        "code": HAOLIGO_LINE_STOP_SUBMITTED,
        "type": "notification",
        "content": "【停线反馈】{{title}}（{{sheet_no}}）已登记，请尽快处置。",
        "variables": ["title", "sheet_no"],
        "is_active": True,
    },
    {
        "name": "停线反馈已处理完成",
        "code": HAOLIGO_LINE_STOP_COMPLETED,
        "type": "notification",
        "content": "【停线反馈】{{title}}（{{sheet_no}}）已处理完成，已回传登记人。",
        "variables": ["title", "sheet_no"],
        "is_active": True,
    },
    {
        "name": "停线反馈临时措施逾期",
        "code": HAOLIGO_LINE_STOP_TEMPORARY_OVERDUE,
        "type": "notification",
        "content": "【停线反馈】{{title}}（{{sheet_no}}）临时措施已逾期，请立即跟进。",
        "variables": ["title", "sheet_no"],
        "is_active": True,
    },
    {
        "name": "停线反馈长期措施逾期",
        "code": HAOLIGO_LINE_STOP_LONG_TERM_OVERDUE,
        "type": "notification",
        "content": "【停线反馈】{{title}}（{{sheet_no}}）长期措施已逾期，请立即跟进。",
        "variables": ["title", "sheet_no"],
        "is_active": True,
    },
]
