"""Unified receivable/payable source_type strings (creation, idempotency, document trace)."""

RECEIVABLE_SOURCE_SALES_DELIVERY = "销售出库"
RECEIVABLE_SOURCE_SALES_INVOICE = "SalesInvoice"
RECEIVABLE_SOURCE_SALES_RETURN = "销售退货"
RECEIVABLE_SOURCE_CONTRACT_MILESTONE = "合同里程碑"
RECEIVABLE_SOURCE_ORDER_MILESTONE = "订单里程碑"
RECEIVABLE_SOURCE_PRICE_SETTLEMENT = "销售调价"

PAYABLE_SOURCE_PURCHASE_RECEIPT = "采购入库"
PAYABLE_SOURCE_PURCHASE_INVOICE = "PurchaseInvoice"
PAYABLE_SOURCE_OUTSOURCE_RECEIPT = "委外收货"
PAYABLE_SOURCE_PURCHASE_RETURN = "采购退货"
PAYABLE_SOURCE_PRICE_SETTLEMENT = "采购调价"
