export {
  KUAIZHIZAO_SALES_ORDER_FIELD_RESOURCE,
  KUAIZHIZAO_QUOTATION_FIELD_RESOURCE,
  KUAIZHIZAO_SALES_CONTRACT_FIELD_RESOURCE,
  KUAIZHIZAO_PURCHASE_ORDER_FIELD_RESOURCE,
  KUAIZHIZAO_PURCHASE_REQUISITION_FIELD_RESOURCE,
  KUAIZHIZAO_OUTSOURCE_ORDER_FIELD_RESOURCE,
  KUAIZHIZAO_DEMAND_FIELD_RESOURCE,
  KUAIZHIZAO_WAREHOUSE_INVENTORY_FIELD_RESOURCE,
} from '../../../constants/fieldPermissionResources';
