"""
编码规则功能页面配置

定义系统中所有有编码字段的功能页面，用于在编码规则页面展示和配置。
"""

from typing import List, Dict, Any

# 页面配置数据结构
CodeRulePageConfig = Dict[str, Any]

# 功能页面配置列表
CODE_RULE_PAGES: List[CodeRulePageConfig] = [
    # 主数据管理 - 工厂建模
    {
        "page_code": "master-data-factory-plant",
        "page_name": "厂区管理",
        "page_path": "/apps/master-data/factory/plants",
        "code_field": "code",
        "code_field_label": "厂区编码",
        "module": "主数据管理",
        "module_icon": "database",
        "auto_generate": False,
    },
    {
        "page_code": "master-data-factory-workshop",
        "page_name": "车间管理",
        "page_path": "/apps/master-data/factory/workshops",
        "code_field": "code",
        "code_field_label": "车间编码",
        "module": "主数据管理",
        "module_icon": "database",
        "auto_generate": False,
    },
    {
        "page_code": "master-data-factory-production-line",
        "page_name": "产线管理",
        "page_path": "/apps/master-data/factory/production-lines",
        "code_field": "code",
        "code_field_label": "产线编码",
        "module": "主数据管理",
        "module_icon": "database",
        "auto_generate": False,
    },
    {
        "page_code": "master-data-factory-workstation",
        "page_name": "工位管理",
        "page_path": "/apps/master-data/factory/workstations",
        "code_field": "code",
        "code_field_label": "工位编码",
        "module": "主数据管理",
        "module_icon": "database",
        "auto_generate": False,
    },
    # 主数据管理 - 仓库管理
    {
        "page_code": "master-data-warehouse-warehouse",
        "page_name": "仓库管理",
        "page_path": "/apps/master-data/warehouse/warehouses",
        "code_field": "code",
        "code_field_label": "仓库编码",
        "module": "主数据管理",
        "module_icon": "database",
        "auto_generate": False,
    },
    {
        "page_code": "master-data-warehouse-storage-area",
        "page_name": "库区管理",
        "page_path": "/apps/master-data/warehouse/storage-areas",
        "code_field": "code",
        "code_field_label": "库区编码",
        "module": "主数据管理",
        "module_icon": "database",
        "auto_generate": False,
    },
    {
        "page_code": "master-data-warehouse-storage-location",
        "page_name": "库位管理",
        "page_path": "/apps/master-data/warehouse/storage-locations",
        "code_field": "code",
        "code_field_label": "库位编码",
        "module": "主数据管理",
        "module_icon": "database",
        "auto_generate": False,
    },
    # 主数据管理 - 物料管理
    {
        "page_code": "master-data-material-group",
        "page_name": "物料分组",
        "page_path": "/apps/master-data/materials",
        "code_field": "code",
        "code_field_label": "分组编码",
        "module": "主数据管理",
        "module_icon": "database",
        "auto_generate": False,
    },
    {
        "page_code": "master-data-material",
        "page_name": "物料管理",
        "page_path": "/apps/master-data/materials",
        "code_field": "main_code",
        "code_field_label": "物料主编码",
        "module": "主数据管理",
        "module_icon": "database",
        "auto_generate": True,
        "rule_code": "MATERIAL_CODE",
        "available_fields": [
            {
                "field_name": "group_code",
                "field_label": "物料分组编码",
                "field_type": "string",
                "description": "物料所属分组的编码"
            },
            {
                "field_name": "group_name",
                "field_label": "物料分组名称",
                "field_type": "string",
                "description": "物料所属分组的名称"
            },
            {
                "field_name": "material_type",
                "field_label": "物料类型",
                "field_type": "string",
                "description": "物料类型（FIN/SEMI/RAW/PACK/AUX）"
            },
            {
                "field_name": "name",
                "field_label": "物料名称",
                "field_type": "string",
                "description": "物料名称"
            }
        ]
    },
    # 主数据管理 - 工艺管理
    {
        "page_code": "master-data-process-operation",
        "page_name": "工序管理",
        "page_path": "/apps/master-data/process/operations",
        "code_field": "code",
        "code_field_label": "工序编码",
        "module": "主数据管理",
        "module_icon": "database",
        "auto_generate": False,
        "rule_code": "OPERATION_CODE",
    },
    {
        "page_code": "master-data-process-route",
        "page_name": "工艺路线",
        "page_path": "/apps/master-data/process/routes",
        "code_field": "code",
        "code_field_label": "路线编码",
        "module": "主数据管理",
        "module_icon": "database",
        "auto_generate": False,
    },
    {
        "page_code": "master-data-defect-type",
        "page_name": "不良品项",
        "page_path": "/apps/master-data/process/defect-types",
        "code_field": "code",
        "code_field_label": "不良品编码",
        "module": "主数据管理",
        "module_icon": "database",
        "auto_generate": False,
        "rule_code": "DEFECT_TYPE_CODE",
    },
    # 主数据管理 - 供应链
    {
        "page_code": "master-data-supply-chain-customer",
        "page_name": "客户管理",
        "page_path": "/apps/master-data/supply-chain/customers",
        "code_field": "code",
        "code_field_label": "客户编码",
        "module": "主数据管理",
        "module_icon": "database",
        "auto_generate": False,
    },
    {
        "page_code": "master-data-supply-chain-supplier",
        "page_name": "供应商管理",
        "page_path": "/apps/master-data/supply-chain/suppliers",
        "code_field": "code",
        "code_field_label": "供应商编码",
        "module": "主数据管理",
        "module_icon": "database",
        "auto_generate": False,
    },
    # 主数据管理 - 绩效管理
    {
        "page_code": "master-data-performance-skill",
        "page_name": "技能管理",
        "page_path": "/apps/master-data/performance/skills",
        "code_field": "code",
        "code_field_label": "技能编码",
        "module": "主数据管理",
        "module_icon": "database",
        "auto_generate": False,
    },
    
    # ==================== 快格轻制造 APP ====================
    # 快格轻制造 - 生产执行
    {
        "page_code": "kuaizhizao-production-work-order",
        "page_name": "工单管理",
        "page_path": "/apps/kuaizhizao/production-execution/work-orders",
        "code_field": "code",
        "code_field_label": "工单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "WORK_ORDER_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-production-rework-order",
        "page_name": "返工单",
        "page_path": "/apps/kuaizhizao/production-execution/rework-orders",
        "code_field": "code",
        "code_field_label": "返工单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "REWORK_ORDER_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-production-outsource-order",
        "page_name": "委外单",
        "page_path": "/apps/kuaizhizao/production-execution/outsource-orders",
        "code_field": "code",
        "code_field_label": "委外单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "OUTSOURCE_ORDER_CODE",
        "allow_manual_edit": True,
    },
    # 快格轻制造 - 采购管理
    {
        "page_code": "kuaizhizao-purchase-order",
        "page_name": "采购订单",
        "page_path": "/apps/kuaizhizao/purchase-management/purchase-orders",
        "code_field": "order_code",
        "code_field_label": "采购订单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "PURCHASE_ORDER_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-purchase-receipt",
        "page_name": "采购收货",
        "page_path": "/apps/kuaizhizao/purchase-management/purchase-receipts",
        "code_field": "receipt_code",
        "code_field_label": "采购收货单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "PURCHASE_RECEIPT_CODE",
        "allow_manual_edit": True,
    },
    # 快格轻制造 - 销售管理
    {
        "page_code": "kuaizhizao-sales-order",
        "page_name": "销售订单",
        "page_path": "/apps/kuaizhizao/sales-management/sales-orders",
        "code_field": "order_code",
        "code_field_label": "销售订单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "SALES_ORDER_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-sales-delivery",
        "page_name": "销售发货",
        "page_path": "/apps/kuaizhizao/sales-management/sales-deliveries",
        "code_field": "delivery_code",
        "code_field_label": "销售发货单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "SALES_DELIVERY_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-sales-forecast",
        "page_name": "销售预测",
        "page_path": "/apps/kuaizhizao/sales-management/sales-forecasts",
        "code_field": "code",
        "code_field_label": "销售预测编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": False,
        "rule_code": "SALES_FORECAST_CODE",
    },
    # 快格轻制造 - 仓储管理
    {
        "page_code": "kuaizhizao-warehouse-inbound",
        "page_name": "生产领料",
        "page_path": "/apps/kuaizhizao/warehouse-management/inbound",
        "code_field": "picking_code",
        "code_field_label": "领料单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "PRODUCTION_PICKING_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-warehouse-finished-goods-inbound",
        "page_name": "成品入库",
        "page_path": "/apps/kuaizhizao/warehouse-management/finished-goods-inventory",
        "code_field": "receipt_code",
        "code_field_label": "成品入库单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "FINISHED_GOODS_RECEIPT_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-warehouse-sales-outbound",
        "page_name": "销售出库",
        "page_path": "/apps/kuaizhizao/warehouse-management/sales-outbound",
        "code_field": "delivery_code",
        "code_field_label": "销售出库单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "SALES_OUTBOUND_CODE",
        "allow_manual_edit": True,
    },
    # 快格轻制造 - 质量管理
    {
        "page_code": "kuaizhizao-quality-incoming-inspection",
        "page_name": "来料检验",
        "page_path": "/apps/kuaizhizao/quality-management/incoming-inspection",
        "code_field": "inspection_code",
        "code_field_label": "来料检验单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "INCOMING_INSPECTION_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-quality-process-inspection",
        "page_name": "过程检验",
        "page_path": "/apps/kuaizhizao/quality-management/process-inspection",
        "code_field": "inspection_code",
        "code_field_label": "过程检验单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "PROCESS_INSPECTION_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-quality-finished-goods-inspection",
        "page_name": "成品检验",
        "page_path": "/apps/kuaizhizao/quality-management/finished-goods-inspection",
        "code_field": "inspection_code",
        "code_field_label": "成品检验单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "FINISHED_GOODS_INSPECTION_CODE",
        "allow_manual_edit": True,
    },
    # 快格轻制造 - 计划管理
    {
        "page_code": "kuaizhizao-plan-production-plan",
        "page_name": "生产计划",
        "page_path": "/apps/kuaizhizao/plan-management/production-plans",
        "code_field": "plan_code",
        "code_field_label": "生产计划编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "PRODUCTION_PLAN_CODE",
        "allow_manual_edit": True,
    },
    # 快格轻制造 - 采购管理（补充）
    {
        "page_code": "kuaizhizao-purchase-return",
        "page_name": "采购退货",
        "page_path": "/apps/kuaizhizao/purchase-management/purchase-returns",
        "code_field": "return_code",
        "code_field_label": "采购退货单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "PURCHASE_RETURN_CODE",
        "allow_manual_edit": True,
    },
    # 快格轻制造 - 销售管理（补充）
    {
        "page_code": "kuaizhizao-sales-return",
        "page_name": "销售退货",
        "page_path": "/apps/kuaizhizao/sales-management/sales-returns",
        "code_field": "return_code",
        "code_field_label": "销售退货单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "SALES_RETURN_CODE",
        "allow_manual_edit": True,
    },
    # 快格轻制造 - 生产执行（补充）
    {
        "page_code": "kuaizhizao-production-outsource-work-order",
        "page_name": "委外工单",
        "page_path": "/apps/kuaizhizao/production-execution/outsource-work-orders",
        "code_field": "code",
        "code_field_label": "委外工单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "OUTSOURCE_WORK_ORDER_CODE",
        "allow_manual_edit": True,
    },
]

