"""
编码规则功能页面配置

定义系统中所有有编码字段的功能页面，用于在编码规则页面展示和配置。
"""

from typing import List, Dict, Any

# 页面代码 -> 固定字符预设（汉语拼音缩写）
# 用于编码规则默认前缀和重置
PAGE_CODE_TO_FIXED_TEXT_PRESET: Dict[str, str] = {
    "master-data-factory-plant": "CQ",           # 厂区
    "master-data-factory-workshop": "CJ",        # 车间
    "master-data-factory-production-line": "CX", # 产线
    "master-data-factory-workstation": "GW",     # 工位
    "master-data-factory-work-center": "GZZX",   # 工作中心
    "master-data-factory-work-group": "GZXZ",    # 工作小组
    "master-data-warehouse-warehouse": "CK",     # 仓库
    "master-data-warehouse-storage-area": "KQ",  # 库区
    "master-data-warehouse-storage-location": "KW",  # 库位
    "master-data-material-group": "FZ",          # 分组
    "master-data-material": "WL",                # 物料
    "master-data-process-operation": "GX",       # 工序
    "master-data-process-route": "GY",           # 工艺
    "master-data-engineering-bom": "GC",         # 物料清单BOM（沿用原工程BOM编码前缀）
    "master-data-defect-type": "BL",             # 不良
    "master-data-supply-chain-customer": "KH",   # 客户
    "master-data-supply-chain-supplier": "GYS",  # 供应商
    "master-data-performance-skill": "JN",       # 技能
    "kuaizhizao-production-work-order": "GD",    # 工单
    "kuaizhizao-production-rework-order": "FGD", # 返工单
    "kuaizhizao-production-outsource-order": "WW",   # 委外
    "kuaizhizao-production-outsource-work-order": "WWGD",  # 委外工单
    "kuaizhizao-production-outsource-material-receipt": "OWR",  # 委外收货
    "kuaizhizao-production-outsource-material-return": "OMR",  # 委外退料
    "kuaizhizao-production-outsource-product-return": "OPR",  # 委外退货
    "kuaizhizao-purchase-order": "CG",           # 采购
    "kuaizhizao-purchase-order-change": "CGBG",  # 采购变更单
    "kuaizhizao-purchase-requisition": "CGSQ",   # 采购申请
    "kuaizhizao-purchase-inquiry": "CGXJ",       # 采购询价单
    "kuaizhizao-purchase-receipt": "CGSD",      # 采购收货
    "kuaizhizao-purchase-return": "CGTH",       # 采购退货
    "kuaizhizao-sales-order": "XS",             # 销售
    "kuaizhizao-sales-order-change": "XSBG",    # 销售变更单
    "kuaizhizao-quotation": "BJ",              # 报价
    "kuaizhizao-sales-contract": "XSHT",       # 销售合同
    "kuaizhizao-sales-contract-change": "XSHTBG",  # 销售合同变更
    "kuaizhizao-sales-delivery": "XSFH",        # 销售发货
    "kuaizhizao-delivery-notice": "SHD",        # 送货单
    "kuaizhizao-shipment-notice": "FHTZ",       # 发货通知单
    "kuaizhizao-receipt-notice": "SHTZ",        # 收货通知单
    "kuaizhizao-sales-forecast": "XSYC",        # 销售预测
    "kuaizhizao-demand-plan": "XQJH",           # 需求计划（手工计划）
    "kuaizhizao-sales-return": "XSTH",          # 销售退货
    "kuaizhizao-warehouse-inbound": "LL",       # 领料
    "kuaizhizao-warehouse-production-return": "TL",       # 生产退料
    "kuaizhizao-warehouse-other-inbound": "QTRK",         # 其他入库
    "kuaizhizao-warehouse-customer-material-registration": "CMR",  # 代工来料（客供料入库）
    "kuaizhizao-warehouse-other-outbound": "QTCK",        # 其他出库
    "kuaizhizao-warehouse-material-borrow": "JL",        # 借料单
    "kuaizhizao-warehouse-material-return": "HL",        # 还料单
    "kuaizhizao-warehouse-material-call": "XLJL",        # 产线叫料
    "kuaizhizao-warehouse-finished-goods-inbound": "CPRK",  # 成品入库
    "kuaizhizao-warehouse-semi-finished-inbound": "BCPRK",  # 半成品入库
    "kuaizhizao-quality-incoming-inspection": "LLJY",   # 来料检验
    "kuaizhizao-quality-process-inspection": "GCJY",   # 过程检验
    "kuaizhizao-quality-finished-goods-inspection": "CPJY",  # 成品检验
    "kuaizhizao-quality-inspection-plan": "ZJFA",  # 质检方案
    "kuaizhizao-quality-oqc-inspection": "CHJY",  # 出货检验
    "kuaizhizao-quality-eight-d-report": "BD",  # 8D报告
    "kuaizhizao-quality-defect-record": "DF",  # 不合格品记录
    "kuaizhizao-quality-scrap-record": "BF",  # 报废记录
    "kuaizhizao-equipment-management-equipment": "EQ",    # 设备（仅此一处使用英文缩写，其余均为汉语拼音）
    "kuaizhizao-equipment-management-mold": "MJ",        # 模具（拼音 muju）
    "kuaizhizao-equipment-management-tool": "GZ",       # 工装（拼音 gongzhuang）
    "kuaizhizao-warehouse-assembly-order": "ZZD",        # 组装单
    "kuaizhizao-warehouse-assembly-template": "ZZMB",   # 组装模板
    "kuaizhizao-warehouse-disassembly-order": "CXD",    # 拆卸单
    "kuaizhizao-warehouse-batching-order": "PL",        # 配料单
    "kuaizhizao-warehouse-stocktaking": "ST",         # 盘点单
    "kuaizhizao-warehouse-inventory-transfer": "TR",  # 调拨单
    "kuaizhizao-warehouse-inventory-alert": "AR",     # 库存预警规则
    # 好力 GO — 模具单据单号前缀（与编码规则固定字一致）
    "haoligo-molds-documents-trial": "SM",
    "haoligo-molds-documents-borrow-out": "LY",
    "haoligo-molds-documents-return-in": "HR",
    "haoligo-molds-documents-maintenance-repair": "WX",
    "haoligo-molds-documents-maintenance-upkeep": "BY",
    "haoligo-molds-documents-maintenance-complete": "WBWX",
    "haoligo-molds-documents-outsource-maintenance": "WXWB",
    "haoligo-molds-documents-outsource-complete": "WXWBWX",
    # 好力 GO — 现场巡查
    "haoligo-patrol-hazard-reports": "XC",
    # 好力 GO — 设备维保单（保养 BY / 维修 WX）
    "haoligo-equipment-documents-upkeep-sheet": "BY",
    "haoligo-equipment-documents-upkeep-repair": "WX",
    "haoligo-equipment-documents-upkeep-complete": "BYWC",
    # 系统配置 — 组织与权限
    "system-department": "BM",
    "system-position": "ZW",
    "system-role": "JS",
    # 轻管理会计 — 财务单据
    "kuaicaiwu-finance-receivable": "YS",           # 应收
    "kuaicaiwu-finance-payable": "PY",              # 应付
    "kuaicaiwu-finance-purchase-invoice": "PI",     # 进项发票
    "kuaicaiwu-finance-settlement": "HX",           # 核销
    "kuaicaiwu-cost-calculations": "CC",            # 成本核算
    "kuaicaiwu-cost-rules": "CR",                   # 成本核算规则
    "kuaiplm-rd-project": "YFXM",                   # 研发项目
    "kuaiplm-delivery-project": "JFXM",             # 交付项目
}

# 页面配置数据结构
CodeRulePageConfig = Dict[str, Any]

# 功能页面配置列表
CODE_RULE_PAGES: List[CodeRulePageConfig] = [
    # 主数据管理 - 工厂建模
    {
        "page_code": "master-data-factory-plant",
        "page_name": "厂区管理",
        "page_path": "/apps/master-data/factory/plants",
        "code_field": "code",
        "code_field_label": "厂区编码",
        "module": "主数据管理",
        "module_icon": "database",
        "auto_generate": True,
        "rule_code": "MASTER_DATA_FACTORY_PLANT",
        "allow_manual_edit": True,
    },
    {
        "page_code": "master-data-factory-workshop",
        "page_name": "车间管理",
        "page_path": "/apps/master-data/factory/workshops",
        "code_field": "code",
        "code_field_label": "车间编码",
        "module": "主数据管理",
        "module_icon": "database",
        "auto_generate": True,
        "rule_code": "MASTER_DATA_FACTORY_WORKSHOP",
        "allow_manual_edit": True,
    },
    {
        "page_code": "master-data-factory-production-line",
        "page_name": "产线管理",
        "page_path": "/apps/master-data/factory/production-lines",
        "code_field": "code",
        "code_field_label": "产线编码",
        "module": "主数据管理",
        "module_icon": "database",
        "auto_generate": True,
        "rule_code": "MASTER_DATA_FACTORY_PRODUCTION_LINE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "master-data-factory-workstation",
        "page_name": "工位管理",
        "page_path": "/apps/master-data/factory/workstations",
        "code_field": "code",
        "code_field_label": "工位编码",
        "module": "主数据管理",
        "module_icon": "database",
        "auto_generate": True,
        "rule_code": "MASTER_DATA_FACTORY_WORKSTATION",
        "allow_manual_edit": True,
    },
    # 主数据管理 - 工作中心（GZZX+4位流水）
    {
        "page_code": "master-data-factory-work-center",
        "page_name": "工作中心",
        "page_path": "/apps/master-data/factory/work-centers",
        "code_field": "code",
        "code_field_label": "工作中心编码",
        "module": "主数据管理",
        "module_icon": "database",
        "auto_generate": True,
        "rule_code": "WORK_CENTER_CODE",
        "allow_manual_edit": True,
        "skip_date": True,  # 工作中心：GZZX+4位流水，不含日期
    },
    # 主数据管理 - 工作小组（GZXZ+4位流水，参考工作中心）
    {
        "page_code": "master-data-factory-work-group",
        "page_name": "工作小组",
        "page_path": "/apps/master-data/factory/work-groups",
        "code_field": "code",
        "code_field_label": "工作小组编码",
        "module": "主数据管理",
        "module_icon": "database",
        "auto_generate": True,
        "rule_code": "WORK_GROUP_CODE",
        "allow_manual_edit": True,
        "skip_date": True,  # 工作小组：GZXZ+4位流水，不含日期
    },
    # 主数据管理 - 仓库管理
    {
        "page_code": "master-data-warehouse-warehouse",
        "page_name": "仓库管理",
        "page_path": "/apps/master-data/warehouse/warehouses",
        "code_field": "code",
        "code_field_label": "仓库编码",
        "module": "主数据管理",
        "module_icon": "database",
        "auto_generate": True,
        "rule_code": "MASTER_DATA_WAREHOUSE_WAREHOUSE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "master-data-warehouse-storage-area",
        "page_name": "库区管理",
        "page_path": "/apps/master-data/warehouse/storage-areas",
        "code_field": "code",
        "code_field_label": "库区编码",
        "module": "主数据管理",
        "module_icon": "database",
        "auto_generate": True,
        "rule_code": "MASTER_DATA_WAREHOUSE_STORAGE_AREA",
        "allow_manual_edit": True,
    },
    {
        "page_code": "master-data-warehouse-storage-location",
        "page_name": "库位管理",
        "page_path": "/apps/master-data/warehouse/storage-locations",
        "code_field": "code",
        "code_field_label": "库位编码",
        "module": "主数据管理",
        "module_icon": "database",
        "auto_generate": True,
        "rule_code": "MASTER_DATA_WAREHOUSE_STORAGE_LOCATION",
        "allow_manual_edit": True,
    },
    # 主数据管理 - 物料管理
    {
        "page_code": "master-data-material-group",
        "page_name": "物料分组",
        "page_path": "/apps/master-data/materials",
        "code_field": "code",
        "code_field_label": "分组编号",
        "module": "主数据管理",
        "module_icon": "database",
        "auto_generate": True,
        "rule_code": "MASTER_DATA_MATERIAL_GROUP",
        "allow_manual_edit": True,
    },
    {
        "page_code": "master-data-material",
        "page_name": "物料管理",
        "page_path": "/apps/master-data/materials",
        "code_field": "main_code",
        "code_field_label": "物料主编码",
        "module": "主数据管理",
        "module_icon": "database",
        "auto_generate": True,
        "rule_code": "MATERIAL_CODE",
        "available_fields": [
            {
                "field_name": "group_code",
                "field_label": "物料分组编号",
                "field_type": "string",
                "description": "物料所属分组的编号（参与编号生成）"
            },
            {
                "field_name": "group_name",
                "field_label": "物料分组名称",
                "field_type": "string",
                "description": "物料所属分组的名称"
            },
            {
                "field_name": "source_type",
                "field_label": "物料来源类型",
                "field_type": "string",
                "description": "物料来源类型（Make/Buy/Outsource/Phantom/Configure）"
            },
            {
                "field_name": "name",
                "field_label": "物料名称",
                "field_type": "string",
                "description": "物料名称"
            }
        ]
    },
    # 主数据管理 - 工艺管理
    {
        "page_code": "master-data-process-operation",
        "page_name": "工序管理",
        "page_path": "/apps/master-data/process/operations",
        "code_field": "code",
        "code_field_label": "工序编码",
        "module": "主数据管理",
        "module_icon": "database",
        "auto_generate": True,
        "rule_code": "OPERATION_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "master-data-process-route",
        "page_name": "工艺路线",
        "page_path": "/apps/master-data/process/routes",
        "code_field": "code",
        "code_field_label": "路线编码",
        "module": "主数据管理",
        "module_icon": "database",
        "auto_generate": True,
        "rule_code": "PROCESS_ROUTE_CODE",
        "allow_manual_edit": True,
        "available_fields": [
            {
                "field_name": "name",
                "field_label": "工艺路线名称",
                "field_type": "string",
                "description": "工艺路线名称"
            }
        ]
    },
    {
        "page_code": "master-data-process-drawing",
        "page_name": "图纸管理",
        "page_path": "/apps/master-data/process/drawings",
        "code_field": "code",
        "code_field_label": "图号",
        "module": "主数据管理",
        "module_icon": "database",
        "auto_generate": True,
        "rule_code": "ENGINEERING_DRAWING_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "master-data-engineering-bom",
        "page_name": "物料清单BOM",
        "page_path": "/apps/master-data/process/engineering-bom",
        "code_field": "bom_code",
        "code_field_label": "BOM编码",
        "module": "主数据管理",
        "module_icon": "database",
        "auto_generate": True,
        "rule_code": "ENGINEERING_BOM_CODE",
        "allow_manual_edit": True,
        "available_fields": [
            {
                "field_name": "material_code",
                "field_label": "主物料编码",
                "field_type": "string",
                "description": "BOM主物料的编码"
            },
            {
                "field_name": "material_name",
                "field_label": "主物料名称",
                "field_type": "string",
                "description": "BOM主物料的名称"
            },
            {
                "field_name": "version",
                "field_label": "版本号",
                "field_type": "string",
                "description": "BOM版本号"
            }
        ]
    },
    {
        "page_code": "master-data-defect-type",
        "page_name": "不良品项",
        "page_path": "/apps/master-data/process/defect-types",
        "code_field": "code",
        "code_field_label": "不良品编码",
        "module": "主数据管理",
        "module_icon": "database",
        "auto_generate": True,
        "rule_code": "DEFECT_TYPE_CODE",
        "allow_manual_edit": True,
    },
    # 主数据管理 - 供应链
    {
        "page_code": "master-data-supply-chain-customer",
        "page_name": "客户管理",
        "page_path": "/apps/master-data/supply-chain/customers",
        "code_field": "code",
        "code_field_label": "客户编码",
        "module": "主数据管理",
        "module_icon": "database",
        "auto_generate": True,
        "rule_code": "customer",
        "allow_manual_edit": True,
    },
    {
        "page_code": "master-data-supply-chain-supplier",
        "page_name": "供应商管理",
        "page_path": "/apps/master-data/supply-chain/suppliers",
        "code_field": "code",
        "code_field_label": "供应商编码",
        "module": "主数据管理",
        "module_icon": "database",
        "auto_generate": True,
        "rule_code": "supplier",
        "allow_manual_edit": True,
    },
    # 主数据管理 - 绩效管理
    {
        "page_code": "master-data-performance-skill",
        "page_name": "技能管理",
        "page_path": "/apps/master-data/performance/skills",
        "code_field": "code",
        "code_field_label": "技能编码",
        "module": "主数据管理",
        "module_icon": "database",
        "auto_generate": False,
    },
    
    # ==================== 快格轻制造 APP ====================
    # 快格轻制造 - 生产执行
    {
        "page_code": "kuaizhizao-production-work-order",
        "page_name": "工单管理",
        "page_path": "/apps/kuaizhizao/production-execution/work-orders",
        "code_field": "code",
        "code_field_label": "工单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "WORK_ORDER_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-production-rework-order",
        "page_name": "返工单",
        "page_path": "/apps/kuaizhizao/production-execution/rework-orders",
        "code_field": "code",
        "code_field_label": "返工单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "REWORK_ORDER_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-production-outsource-order",
        "page_name": "委外单",
        "page_path": "/apps/kuaizhizao/production-execution/outsource-management",
        "code_field": "code",
        "code_field_label": "委外单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "OUTSOURCE_ORDER_CODE",
        "allow_manual_edit": True,
    },
    # 快格轻制造 - 采购管理
    {
        "page_code": "kuaizhizao-purchase-order",
        "page_name": "采购订单",
        "page_path": "/apps/kuaizhizao/purchase-management/purchase-orders",
        "code_field": "order_code",
        "code_field_label": "采购订单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "PURCHASE_ORDER_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-purchase-order-change",
        "page_name": "采购变更单",
        "page_path": "/apps/kuaizhizao/purchase-management/purchase-order-changes",
        "code_field": "change_code",
        "code_field_label": "采购变更单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "PURCHASE_ORDER_CHANGE_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-purchase-requisition",
        "page_name": "采购申请",
        "page_path": "/apps/kuaizhizao/purchase-management/purchase-requisitions",
        "code_field": "requisition_code",
        "code_field_label": "采购申请编号",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "PURCHASE_REQUISITION_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-purchase-inquiry",
        "page_name": "采购询价单",
        "page_path": "/apps/kuaizhizao/purchase-management/purchase-inquiries",
        "code_field": "inquiry_code",
        "code_field_label": "询价单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "PURCHASE_INQUIRY_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-purchase-receipt",
        "page_name": "采购入库",
        "page_path": "/apps/kuaizhizao/warehouse-management/inbound",
        "code_field": "receipt_code",
        "code_field_label": "采购收货单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "PURCHASE_RECEIPT_CODE",
        "allow_manual_edit": True,
    },
    # 快格轻制造 - 销售管理
    {
        "page_code": "kuaizhizao-quotation",
        "page_name": "报价单",
        "page_path": "/apps/kuaizhizao/sales-management/quotations",
        "code_field": "quotation_code",
        "code_field_label": "报价单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "QUOTATION_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-sales-contract",
        "page_name": "销售合同",
        "page_path": "/apps/kuaizhizao/sales-management/sales-contracts",
        "code_field": "contract_code",
        "code_field_label": "合同编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "KUAIZHIZAO_SALES_CONTRACT",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-sales-contract-change",
        "page_name": "销售合同变更",
        "page_path": "/apps/kuaizhizao/sales-management/sales-contracts",
        "code_field": "change_code",
        "code_field_label": "合同变更编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "KUAIZHIZAO_SALES_CONTRACT_CHANGE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-sales-order",
        "page_name": "销售订单",
        "page_path": "/apps/kuaizhizao/sales-management/sales-orders",
        "code_field": "order_code",
        "code_field_label": "销售订单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "SALES_ORDER_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-sales-order-change",
        "page_name": "销售变更单",
        "page_path": "/apps/kuaizhizao/sales-management/sales-order-changes",
        "code_field": "change_code",
        "code_field_label": "销售变更单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "SALES_ORDER_CHANGE_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-sales-delivery",
        "page_name": "销售发货",
        "page_path": "/apps/kuaizhizao/warehouse-management/outbound",
        "code_field": "delivery_code",
        "code_field_label": "销售发货单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "SALES_DELIVERY_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-delivery-notice",
        "page_name": "送货单",
        "page_path": "/apps/kuaizhizao/warehouse-management/delivery-notes",
        "code_field": "notice_code",
        "code_field_label": "送货单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "DELIVERY_NOTICE_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-shipment-notice",
        "page_name": "发货通知单",
        "page_path": "/apps/kuaizhizao/sales-management/shipment-notices",
        "code_field": "notice_code",
        "code_field_label": "发货通知单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "SHIPMENT_NOTICE_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-receipt-notice",
        "page_name": "收货通知单",
        "page_path": "/apps/kuaizhizao/purchase-management/receipt-notices",
        "code_field": "notice_code",
        "code_field_label": "收货通知单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "RECEIPT_NOTICE_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-sales-forecast",
        "page_name": "销售预测",
        "page_path": "/apps/kuaizhizao/sales-management/sales-forecasts",
        "code_field": "forecast_code",
        "code_field_label": "销售预测编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "SALES_FORECAST_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-demand-plan",
        "page_name": "需求计划",
        "page_path": "/apps/kuaizhizao/plan-management/demand-management",
        "code_field": "demand_code",
        "code_field_label": "需求计划编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "DEMAND_PLAN_CODE",
        "allow_manual_edit": True,
    },
    # 快格轻制造 - 仓储管理
    {
        "page_code": "kuaizhizao-warehouse-inbound",
        "page_name": "生产领料",
        "page_path": "/apps/kuaizhizao/warehouse-management/inbound",
        "code_field": "picking_code",
        "code_field_label": "领料单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "PRODUCTION_PICKING_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-warehouse-production-return",
        "page_name": "生产退料",
        "page_path": "/apps/kuaizhizao/warehouse-management/production-returns",
        "code_field": "return_code",
        "code_field_label": "退料单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "PRODUCTION_RETURN_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-warehouse-other-inbound",
        "page_name": "其他入库",
        "page_path": "/apps/kuaizhizao/warehouse-management/other-inbound",
        "code_field": "inbound_code",
        "code_field_label": "入库单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "OTHER_INBOUND_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-warehouse-customer-material-registration",
        "page_name": "代工来料",
        "page_path": "/apps/kuaizhizao/warehouse-management/customer-material-registration",
        "code_field": "registration_code",
        "code_field_label": "代工来料单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "CUSTOMER_MATERIAL_REGISTRATION_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-warehouse-other-outbound",
        "page_name": "其他出库",
        "page_path": "/apps/kuaizhizao/warehouse-management/other-outbound",
        "code_field": "outbound_code",
        "code_field_label": "出库单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "OTHER_OUTBOUND_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-warehouse-material-borrow",
        "page_name": "借料单",
        "page_path": "/apps/kuaizhizao/warehouse-management/material-borrows",
        "code_field": "borrow_code",
        "code_field_label": "借料单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "MATERIAL_BORROW_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-warehouse-material-return",
        "page_name": "还料单",
        "page_path": "/apps/kuaizhizao/warehouse-management/material-returns",
        "code_field": "return_code",
        "code_field_label": "还料单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "MATERIAL_RETURN_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-warehouse-material-call",
        "page_name": "产线叫料",
        "page_path": "/apps/kuaizhizao/warehouse-management/material-calls",
        "code_field": "code",
        "code_field_label": "叫料单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "MATERIAL_CALL_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-warehouse-assembly-order",
        "page_name": "组装单",
        "page_path": "/apps/kuaizhizao/warehouse-management/assembly-orders",
        "code_field": "code",
        "code_field_label": "组装单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "ASSEMBLY_ORDER_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-warehouse-assembly-template",
        "page_name": "组装模板",
        "page_path": "/apps/kuaizhizao/warehouse-management/assembly-orders",
        "code_field": "template_code",
        "code_field_label": "组装模板编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "ASSEMBLY_TEMPLATE_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-warehouse-disassembly-order",
        "page_name": "拆卸单",
        "page_path": "/apps/kuaizhizao/warehouse-management/disassembly-orders",
        "code_field": "code",
        "code_field_label": "拆卸单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "DISASSEMBLY_ORDER_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-warehouse-batching-order",
        "page_name": "配料单",
        "page_path": "/apps/kuaizhizao/warehouse-management/batching-center",
        "code_field": "code",
        "code_field_label": "配料单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "BATCHING_ORDER_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-warehouse-stocktaking",
        "page_name": "盘点单",
        "page_path": "/apps/kuaizhizao/warehouse-management/stocktaking",
        "code_field": "code",
        "code_field_label": "盘点单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "STOCKTAKING_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-warehouse-inventory-transfer",
        "page_name": "调拨单",
        "page_path": "/apps/kuaizhizao/warehouse-management/inventory-transfer",
        "code_field": "code",
        "code_field_label": "调拨单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "INVENTORY_TRANSFER_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-warehouse-inventory-alert",
        "page_name": "库存预警规则",
        "page_path": "/apps/kuaizhizao/warehouse-management/inventory-alert",
        "code_field": "code",
        "code_field_label": "预警规则编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "ALERT_RULE_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-warehouse-finished-goods-inbound",
        "page_name": "成品入库",
        "page_path": "/apps/kuaizhizao/warehouse-management/product-inbound",
        "code_field": "receipt_code",
        "code_field_label": "成品入库单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "FINISHED_GOODS_RECEIPT_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-warehouse-semi-finished-inbound",
        "page_name": "半成品入库",
        "page_path": "/apps/kuaizhizao/warehouse-management/product-inbound",
        "code_field": "receipt_code",
        "code_field_label": "半成品入库单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "SEMI_FINISHED_GOODS_RECEIPT_CODE",
        "allow_manual_edit": True,
    },
    # 快格轻制造 - 质量管理
    {
        "page_code": "kuaizhizao-quality-incoming-inspection",
        "page_name": "来料检验",
        "page_path": "/apps/kuaizhizao/quality-management/incoming-inspection",
        "code_field": "inspection_code",
        "code_field_label": "来料检验单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "INCOMING_INSPECTION_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-quality-process-inspection",
        "page_name": "过程检验",
        "page_path": "/apps/kuaizhizao/quality-management/process-inspection",
        "code_field": "inspection_code",
        "code_field_label": "过程检验单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "PROCESS_INSPECTION_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-quality-inspection-plan",
        "page_name": "质检方案",
        "page_path": "/apps/kuaizhizao/quality-management/inspection-plans",
        "code_field": "plan_code",
        "code_field_label": "质检方案编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "INSPECTION_PLAN_CODE",
        "allow_manual_edit": True,
        "available_fields": [
            {
                "field_name": "plan_type",
                "field_label": "方案类型",
                "field_type": "string",
                "description": "方案类型（incoming/process/finished）"
            },
            {
                "field_name": "material_code",
                "field_label": "物料编码",
                "field_type": "string",
                "description": "适用物料编码"
            }
        ]
    },
    {
        "page_code": "kuaizhizao-quality-finished-goods-inspection",
        "page_name": "成品检验",
        "page_path": "/apps/kuaizhizao/quality-management/finished-goods-inspection",
        "code_field": "inspection_code",
        "code_field_label": "成品检验单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "FINISHED_GOODS_INSPECTION_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-quality-oqc-inspection",
        "page_name": "出货检验",
        "page_path": "/apps/kuaizhizao/quality-management/oqc-inspection",
        "code_field": "inspection_code",
        "code_field_label": "出货检验单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "OQC_INSPECTION_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-quality-eight-d-report",
        "page_name": "8D报告",
        "page_path": "/apps/kuaizhizao/quality-management/eight-d-reports",
        "code_field": "report_code",
        "code_field_label": "8D报告编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "EIGHT_D_REPORT_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-quality-defect-record",
        "page_name": "不合格品记录",
        "page_path": "/apps/kuaizhizao/quality-management/nonconforming-ledger",
        "code_field": "code",
        "code_field_label": "不合格品记录编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "DEFECT_RECORD_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-quality-scrap-record",
        "page_name": "报废记录",
        "page_path": "/apps/kuaizhizao/production-execution/reporting",
        "code_field": "code",
        "code_field_label": "报废单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "SCRAP_RECORD_CODE",
        "allow_manual_edit": True,
    },
    # 快格轻制造 - 计划管理
    # 快格轻制造 - 采购管理（补充）
    {
        "page_code": "kuaizhizao-purchase-return",
        "page_name": "采购退货",
        "page_path": "/apps/kuaizhizao/purchase-management/purchase-returns",
        "code_field": "return_code",
        "code_field_label": "采购退货单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "PURCHASE_RETURN_CODE",
        "allow_manual_edit": True,
    },
    # 快格轻制造 - 销售管理（补充）
    {
        "page_code": "kuaizhizao-sales-return",
        "page_name": "销售退货",
        "page_path": "/apps/kuaizhizao/sales-management/sales-returns",
        "code_field": "return_code",
        "code_field_label": "销售退货单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "SALES_RETURN_CODE",
        "allow_manual_edit": True,
    },
    # 快格轻制造 - 设备管理（EQ+4位流水）
    {
        "page_code": "kuaizhizao-equipment-management-equipment",
        "page_name": "设备管理",
        "page_path": "/apps/kuaizhizao/equipment-management/equipment",
        "code_field": "code",
        "code_field_label": "设备编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "EQUIPMENT_CODE",
        "allow_manual_edit": True,
        "skip_date": True,  # 设备：EQ+4位流水，不含日期
    },
    # 快格轻制造 - 模具管理（MOLD+4位流水）
    {
        "page_code": "kuaizhizao-equipment-management-mold",
        "page_name": "模具管理",
        "page_path": "/apps/kuaizhizao/equipment-management/molds",
        "code_field": "code",
        "code_field_label": "模具编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "MOLD_CODE",
        "allow_manual_edit": True,
        "skip_date": True,  # 模具：MOLD+4位流水，不含日期
    },
    # 快格轻制造 - 工装台账（TOOL+4位流水）
    {
        "page_code": "kuaizhizao-equipment-management-tool",
        "page_name": "工装台账",
        "page_path": "/apps/kuaizhizao/equipment-management/tool-ledger",
        "code_field": "code",
        "code_field_label": "工装编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "TOOL_CODE",
        "allow_manual_edit": True,
        "skip_date": True,  # 工装：TOOL+4位流水，不含日期
    },
    # 快格轻制造 - 生产执行（补充）
    {
        "page_code": "kuaizhizao-production-outsource-work-order",
        "page_name": "委外工单",
        "page_path": "/apps/kuaizhizao/production-execution/outsource-management",
        "code_field": "code",
        "code_field_label": "委外工单编码",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "OUTSOURCE_WORK_ORDER_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-production-outsource-material-receipt",
        "page_name": "委外收货",
        "page_path": "/apps/kuaizhizao/warehouse-management/batching-center",
        "code_field": "code",
        "code_field_label": "委外收货单编号",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "OUTSOURCE_MATERIAL_RECEIPT_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-production-outsource-material-return",
        "page_name": "委外退料",
        "page_path": "/apps/kuaizhizao/warehouse-management/batching-center",
        "code_field": "code",
        "code_field_label": "委外退料单编号",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "OUTSOURCE_MATERIAL_RETURN_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaizhizao-production-outsource-product-return",
        "page_name": "委外退货",
        "page_path": "/apps/kuaizhizao/warehouse-management/batching-center",
        "code_field": "code",
        "code_field_label": "委外退货单编号",
        "module": "快格轻制造",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "OUTSOURCE_PRODUCT_RETURN_CODE",
        "allow_manual_edit": True,
    },
    # 好力 GO — 模具单据单号默认规则（与流水号配置 UI 一致）：固定字符 + 提交日期（YYMMDD）+ 3 位自动计数（每日重置）
    {
        "page_code": "haoligo-molds-documents-trial",
        "page_name": "模具试模单",
        "page_path": "/apps/haoligo/molds/documents/trial",
        "code_field": "sheet_no",
        "code_field_label": "模具试模单单号",
        "module": "好力 GO",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "HAOLIGO_MOLD_TRIAL_SHEET_NO",
        "allow_manual_edit": False,
        "include_date_in_code": True,
        "code_date_preset_format": "YYMMDD",
        "code_counter_digits": 3,
        "code_rule_description": "模具试模单默认规则：固定字符「SM」+ 提交日期（YYMMDD）+ 自动计数（3 位数字，每日重置）",
    },
    {
        "page_code": "haoligo-molds-documents-borrow-out",
        "page_name": "模具领用单",
        "page_path": "/apps/haoligo/molds/documents/borrow-out",
        "code_field": "sheet_no",
        "code_field_label": "模具领用单单号",
        "module": "好力 GO",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "HAOLIGO_MOLD_BORROW_SHEET_NO",
        "allow_manual_edit": False,
        "include_date_in_code": True,
        "code_date_preset_format": "YYMMDD",
        "code_counter_digits": 3,
        "code_rule_description": "模具领用单默认规则：固定字符「LY」+ 提交日期（YYMMDD）+ 自动计数（3 位数字，每日重置）",
    },
    {
        "page_code": "haoligo-molds-documents-return-in",
        "page_name": "模具还入单",
        "page_path": "/apps/haoligo/molds/documents/return-in",
        "code_field": "sheet_no",
        "code_field_label": "模具还入单单号",
        "module": "好力 GO",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "HAOLIGO_MOLD_RETURN_SHEET_NO",
        "allow_manual_edit": False,
        "include_date_in_code": True,
        "code_date_preset_format": "YYMMDD",
        "code_counter_digits": 3,
        "code_rule_description": "模具还入单默认规则：固定字符「HR」+ 提交日期（YYMMDD）+ 自动计数（3 位数字，每日重置）",
    },
    {
        "page_code": "haoligo-molds-documents-maintenance-repair",
        "page_name": "模具厂内维修单",
        "page_path": "/apps/haoligo/molds/documents/repair",
        "code_field": "sheet_no",
        "code_field_label": "维修单单号",
        "module": "好力 GO",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "HAOLIGO_MOLD_MAINTENANCE_REPAIR_SHEET_NO",
        "allow_manual_edit": False,
        "include_date_in_code": True,
        "code_date_preset_format": "YYMMDD",
        "code_counter_digits": 3,
        "code_rule_description": "厂内维修单默认规则：固定字符「WX」+ 提交日期（YYMMDD）+ 自动计数（3 位数字，每日重置）",
    },
    {
        "page_code": "haoligo-molds-documents-maintenance-upkeep",
        "page_name": "模具厂内保养单",
        "page_path": "/apps/haoligo/molds/documents/upkeep",
        "code_field": "sheet_no",
        "code_field_label": "保养单单号",
        "module": "好力 GO",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "HAOLIGO_MOLD_MAINTENANCE_UPKEEP_SHEET_NO",
        "allow_manual_edit": False,
        "include_date_in_code": True,
        "code_date_preset_format": "YYMMDD",
        "code_counter_digits": 3,
        "code_rule_description": "厂内保养单默认规则：固定字符「BY」+ 提交日期（YYMMDD）+ 自动计数（3 位数字，每日重置）",
    },
    {
        "page_code": "haoligo-molds-documents-maintenance-complete",
        "page_name": "模具维保完成单",
        "page_path": "/apps/haoligo/molds/documents/upkeep-complete",
        "code_field": "sheet_no",
        "code_field_label": "模具维保完成单单号",
        "module": "好力 GO",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "HAOLIGO_MOLD_MAINTENANCE_COMPLETE_SHEET_NO",
        "allow_manual_edit": False,
        "include_date_in_code": True,
        "code_date_preset_format": "YYMMDD",
        "code_counter_digits": 3,
        "code_rule_description": "模具维保完成单默认规则：固定字符「WBWX」+ 提交日期（YYMMDD）+ 自动计数（3 位数字，每日重置）",
    },
    {
        "page_code": "haoligo-molds-documents-outsource-maintenance",
        "page_name": "外协维修单",
        "page_path": "/apps/haoligo/molds/documents/outsource-maintenance",
        "code_field": "sheet_no",
        "code_field_label": "外协维修单单号",
        "module": "好力 GO",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "HAOLIGO_MOLD_OUTSOURCE_MAINTENANCE_SHEET_NO",
        "allow_manual_edit": False,
        "include_date_in_code": True,
        "code_date_preset_format": "YYMMDD",
        "code_counter_digits": 3,
        "code_rule_description": "外协维修单默认规则：固定字符「WXWB」+ 提交日期（YYMMDD）+ 自动计数（3 位数字，每日重置）",
    },
    {
        "page_code": "haoligo-molds-documents-outsource-complete",
        "page_name": "外协维修完成单",
        "page_path": "/apps/haoligo/molds/documents/outsource-complete",
        "code_field": "sheet_no",
        "code_field_label": "外协维修完成单单号",
        "module": "好力 GO",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "HAOLIGO_MOLD_OUTSOURCE_MAINTENANCE_COMPLETE_SHEET_NO",
        "allow_manual_edit": False,
        "include_date_in_code": True,
        "code_date_preset_format": "YYMMDD",
        "code_counter_digits": 3,
        "code_rule_description": "外协维修完成单默认规则：固定字符「WXWBWX」+ 提交日期（YYMMDD）+ 自动计数（3 位数字，每日重置）",
    },
    {
        "page_code": "haoligo-equipment-documents-spot-check",
        "page_name": "设备点检单",
        "page_path": "/apps/haoligo/equipment/documents/spot-check",
        "code_field": "sheet_no",
        "code_field_label": "点检单单号",
        "module": "好力 GO",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "HAOLIGO_EQUIPMENT_SPOT_CHECK_NO",
        "allow_manual_edit": False,
        "include_date_in_code": True,
        "code_date_preset_format": "YYMMDD",
        "code_counter_digits": 3,
        "code_rule_description": "设备点检单默认规则：固定字符「DJ」+ 提交日期（YYMMDD）+ 自动计数（3 位数字，每日重置）",
    },
    {
        "page_code": "haoligo-equipment-documents-route-patrol",
        "page_name": "设备路线巡检单",
        "page_path": "/apps/haoligo/equipment/documents/route-patrol",
        "code_field": "sheet_no",
        "code_field_label": "巡检单单号",
        "module": "好力 GO",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "HAOLIGO_EQUIPMENT_ROUTE_PATROL_NO",
        "allow_manual_edit": False,
        "include_date_in_code": True,
        "code_date_preset_format": "YYMMDD",
        "code_counter_digits": 3,
        "code_rule_description": "路线巡检单默认规则：固定字符「XJ」+ 提交日期（YYMMDD）+ 自动计数（3 位数字，每日重置）",
    },
    {
        "page_code": "haoligo-patrol-hazard-reports",
        "page_name": "现场巡查登记",
        "page_path": "/apps/haoligo/patrol/daily/form",
        "code_field": "sheet_no",
        "code_field_label": "登记单号",
        "module": "好力 GO",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "HAOLIGO_PATROL_HAZARD_REPORT_NO",
        "allow_manual_edit": False,
        "include_date_in_code": True,
        "code_date_preset_format": "YYMMDD",
        "code_counter_digits": 3,
        "code_rule_description": "现场巡查登记默认规则：固定字符「XC」+ 提交日期（YYMMDD）+ 自动计数（3 位数字，每日重置）",
    },
    {
        "page_code": "haoligo-equipment-documents-upkeep-sheet",
        "page_name": "设备维保单（保养）",
        "page_path": "/apps/haoligo/equipment/documents/upkeep-sheet",
        "code_field": "sheet_no",
        "code_field_label": "保养维保单号",
        "module": "好力 GO",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "HAOLIGO_EQUIPMENT_UPKEEP_SHEET_NO",
        "allow_manual_edit": False,
        "include_date_in_code": True,
        "code_date_preset_format": "YYMMDD",
        "code_counter_digits": 3,
        "code_rule_description": "设备保养维保单默认规则：固定字符「BY」+ 提交日期（YYMMDD）+ 自动计数（3 位数字，每日重置）",
    },
    {
        "page_code": "haoligo-equipment-documents-upkeep-repair",
        "page_name": "设备维保单（维修）",
        "page_path": "/apps/haoligo/equipment/documents/upkeep-sheet",
        "code_field": "sheet_no",
        "code_field_label": "维修维保单号",
        "module": "好力 GO",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "HAOLIGO_EQUIPMENT_MAINTENANCE_REPAIR_SHEET_NO",
        "allow_manual_edit": False,
        "include_date_in_code": True,
        "code_date_preset_format": "YYMMDD",
        "code_counter_digits": 3,
        "code_rule_description": "设备维修维保单默认规则：固定字符「WX」+ 提交日期（YYMMDD）+ 自动计数（3 位数字，每日重置）",
    },
    {
        "page_code": "haoligo-equipment-documents-upkeep-complete",
        "page_name": "设备维保完成单",
        "page_path": "/apps/haoligo/equipment/documents/upkeep-complete",
        "code_field": "sheet_no",
        "code_field_label": "维保完成单单号",
        "module": "好力 GO",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "HAOLIGO_EQUIPMENT_UPKEEP_COMPLETE_SHEET_NO",
        "allow_manual_edit": False,
        "include_date_in_code": True,
        "code_date_preset_format": "YYMMDD",
        "code_counter_digits": 3,
        "code_rule_description": "设备维保完成单默认规则：固定字符「BYWC」+ 提交日期（YYMMDD）+ 自动计数（3 位数字，每日重置）",
    },
    {
        "page_code": "haoligo-equipment-documents-output-record",
        "page_name": "设备产出单",
        "page_path": "/apps/haoligo/equipment/documents/output-record",
        "code_field": "sheet_no",
        "code_field_label": "产出单单号",
        "module": "好力 GO",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "HAOLIGO_EQUIPMENT_OUTPUT_RECORD_NO",
        "allow_manual_edit": False,
        "include_date_in_code": True,
        "code_date_preset_format": "YYMMDD",
        "code_counter_digits": 3,
        "code_rule_description": "设备产出单默认规则：固定字符「CC」+ 提交日期（YYMMDD）+ 自动计数（3 位数字，每日重置）",
    },
    {
        "page_code": "haoligo-equipment-documents-status-adjustment",
        "page_name": "设备状态调整单",
        "page_path": "/apps/haoligo/equipment/documents/status-adjustment",
        "code_field": "sheet_no",
        "code_field_label": "调整单单号",
        "module": "好力 GO",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "HAOLIGO_EQUIPMENT_STATUS_ADJUSTMENT_NO",
        "allow_manual_edit": False,
        "include_date_in_code": True,
        "code_date_preset_format": "YYMMDD",
        "code_counter_digits": 3,
        "code_rule_description": "设备状态调整单默认规则：固定字符「ZTTZ」+ 提交日期（YYMMDD）+ 自动计数（3 位数字，每日重置）",
    },
    {
        "page_code": "haoligo-equipment-documents-acceptance",
        "page_name": "设备验收单",
        "page_path": "/apps/haoligo/equipment/documents/acceptance",
        "code_field": "sheet_no",
        "code_field_label": "验收单单号",
        "module": "好力 GO",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "HAOLIGO_EQUIPMENT_ACCEPTANCE_NO",
        "allow_manual_edit": False,
        "include_date_in_code": True,
        "code_date_preset_format": "YYMMDD",
        "code_counter_digits": 3,
        "code_rule_description": "设备验收单默认规则：固定字符「SBYS」+ 提交日期（YYMMDD）+ 自动计数（3 位数字，每日重置）",
    },
    {
        "page_code": "haoligo-finance-material-acceptance",
        "page_name": "材料验收单",
        "page_path": "/apps/haoligo/finance/invoice-verify",
        "code_field": "sheet_no",
        "code_field_label": "验收单号",
        "module": "好力 GO",
        "module_icon": "tool",
        "auto_generate": True,
        "rule_code": "HAOLIGO_FINANCE_MATERIAL_ACCEPTANCE_NO",
        "allow_manual_edit": False,
        "include_date_in_code": True,
        "code_date_preset_format": "YYMMDD",
        "code_counter_digits": 3,
        "code_rule_description": "材料验收单默认规则：固定字符「CLYS」+ 提交日期（YYMMDD）+ 自动计数（3 位数字，每日重置）",
    },
    # 系统配置 — 用户管理（导入用户时自动创建部门/职位/角色）
    {
        "page_code": "system-department",
        "page_name": "部门管理",
        "page_path": "/system/departments",
        "code_field": "code",
        "code_field_label": "部门代码",
        "module": "系统配置",
        "module_icon": "setting",
        "auto_generate": True,
        "rule_code": "DEPARTMENT_CODE",
        "allow_manual_edit": True,
        "skip_date": True,
    },
    {
        "page_code": "system-position",
        "page_name": "职位管理",
        "page_path": "/system/positions",
        "code_field": "code",
        "code_field_label": "职位代码",
        "module": "系统配置",
        "module_icon": "setting",
        "auto_generate": True,
        "rule_code": "POSITION_CODE",
        "allow_manual_edit": True,
        "skip_date": True,
    },
    {
        "page_code": "system-role",
        "page_name": "角色管理",
        "page_path": "/system/roles",
        "code_field": "code",
        "code_field_label": "角色代码",
        "module": "系统配置",
        "module_icon": "setting",
        "auto_generate": True,
        "rule_code": "ROLE_CODE",
        "allow_manual_edit": True,
        "skip_date": True,
    },
    # 轻管理会计 - 财务协同
    {
        "page_code": "kuaicaiwu-finance-receivable",
        "page_name": "应收账款",
        "page_path": "/apps/kuaicaiwu/finance-management/receivables",
        "code_field": "receivable_code",
        "code_field_label": "应收单编码",
        "module": "轻管理会计",
        "module_icon": "account-book",
        "auto_generate": True,
        "rule_code": "RECEIVABLE_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaicaiwu-finance-payable",
        "page_name": "应付账款",
        "page_path": "/apps/kuaicaiwu/finance-management/payables",
        "code_field": "payable_code",
        "code_field_label": "应付单编码",
        "module": "轻管理会计",
        "module_icon": "account-book",
        "auto_generate": True,
        "rule_code": "PAYABLE_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaicaiwu-finance-purchase-invoice",
        "page_name": "进项发票",
        "page_path": "/apps/kuaicaiwu/finance-management/purchase-invoices",
        "code_field": "invoice_code",
        "code_field_label": "进项发票编码",
        "module": "轻管理会计",
        "module_icon": "account-book",
        "auto_generate": True,
        "rule_code": "PURCHASE_INVOICE_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaicaiwu-finance-sales-invoice",
        "page_name": "销售发票",
        "page_path": "/apps/kuaicaiwu/finance-management/sales-invoices",
        "code_field": "invoice_code",
        "code_field_label": "销售发票编码",
        "module": "轻管理会计",
        "module_icon": "account-book",
        "auto_generate": True,
        "rule_code": "SALES_INVOICE_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaicaiwu-finance-settlement",
        "page_name": "核销",
        "page_path": "/apps/kuaicaiwu/finance-management/settlement",
        "code_field": "settlement_code",
        "code_field_label": "核销单编码",
        "module": "轻管理会计",
        "module_icon": "account-book",
        "auto_generate": True,
        "rule_code": "SETTLEMENT_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaicaiwu-finance-partner-statement",
        "page_name": "往来对账",
        "page_path": "/apps/kuaicaiwu/finance-management/partner-statements",
        "code_field": "statement_code",
        "code_field_label": "对账单编码",
        "module": "轻管理会计",
        "module_icon": "account-book",
        "auto_generate": True,
        "rule_code": "PARTNER_STATEMENT_CODE",
        "allow_manual_edit": True,
    },
    # 轻管理会计 - 成本管理
    {
        "page_code": "kuaicaiwu-cost-calculations",
        "page_name": "产品成本核算",
        "page_path": "/apps/kuaicaiwu/cost-management/cost-calculations",
        "code_field": "calculation_no",
        "code_field_label": "核算单号",
        "module": "轻管理会计",
        "module_icon": "calculator",
        "auto_generate": True,
        "rule_code": "COST_CALCULATION_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaicaiwu-cost-rules",
        "page_name": "成本核算规则",
        "page_path": "/apps/kuaicaiwu/cost-management/cost-rules",
        "code_field": "code",
        "code_field_label": "规则编码",
        "module": "轻管理会计",
        "module_icon": "calculator",
        "auto_generate": True,
        "rule_code": "COST_RULE_CODE",
        "allow_manual_edit": True,
    },
    # ==================== 快研发 APP ====================
    {
        "page_code": "kuaiplm-rd-project",
        "page_name": "研发项目",
        "page_path": "/apps/kuaiplm/rd-projects",
        "code_field": "project_code",
        "code_field_label": "项目编码",
        "module": "快研发",
        "module_icon": "layers",
        "auto_generate": True,
        "rule_code": "RD_PROJECT_CODE",
        "allow_manual_edit": True,
    },
    {
        "page_code": "kuaiplm-delivery-project",
        "page_name": "交付项目",
        "page_path": "/apps/kuaiplm/rd-projects",
        "code_field": "project_code",
        "code_field_label": "项目编码",
        "module": "快研发",
        "module_icon": "layers",
        "auto_generate": True,
        "rule_code": "DELIVERY_PROJECT_CODE",
        "allow_manual_edit": True,
    },
]


def get_rule_code_to_page_code() -> Dict[str, str]:
    """
    规则代码 -> 页面代码映射
    包含：1) 显式配置的 rule_code  2) 由 page_code 派生的规则代码（如 MASTER_DATA_FACTORY_PLANT）
    用于覆盖所有可能的规则代码格式（包括自定义/未配置 rule_code 的页面）
    """
    mapping: Dict[str, str] = {}
    for p in CODE_RULE_PAGES:
        page_code = p["page_code"]
        # 显式 rule_code
        if p.get("rule_code"):
            mapping[p["rule_code"]] = page_code
        # 派生规则代码（前端无 rule_code 时使用 page_code 转大写+下划线）
        derived = page_code.upper().replace("-", "_")
        mapping[derived] = page_code
    return mapping


# 规则代码 -> 实体模型（用于序列号校准：导入数据后从库中取最大序号，使新生成的序号接着往后）
# 格式: rule_code -> (模块路径, 模型类名, 编码字段名)
# 仅配置支持“前缀+序号”且可查库的实体，用于 generate_code 时自动校准 current_seq
RULE_CODE_ENTITY_FOR_SEQ_SYNC: Dict[str, tuple] = {
    "DEFECT_TYPE_CODE": ("apps.master_data.models.process", "DefectType", "code"),
    "master-data-defect-type": ("apps.master_data.models.process", "DefectType", "code"),
    "OPERATION_CODE": ("apps.master_data.models.process", "Operation", "code"),
    "master-data-process-operation": ("apps.master_data.models.process", "Operation", "code"),
    "ENGINEERING_DRAWING_CODE": ("apps.master_data.models.drawing", "EngineeringDrawing", "code"),
    "master-data-process-drawing": ("apps.master_data.models.drawing", "EngineeringDrawing", "code"),
    "MASTER_DATA_FACTORY_PLANT": ("apps.master_data.models.factory", "Plant", "code"),
    "master-data-factory-plant": ("apps.master_data.models.factory", "Plant", "code"),
    "MASTER_DATA_FACTORY_WORKSHOP": ("apps.master_data.models.factory", "Workshop", "code"),
    "master-data-factory-workshop": ("apps.master_data.models.factory", "Workshop", "code"),
    "MASTER_DATA_FACTORY_PRODUCTION_LINE": ("apps.master_data.models.factory", "ProductionLine", "code"),
    "master-data-factory-production-line": ("apps.master_data.models.factory", "ProductionLine", "code"),
    "MASTER_DATA_FACTORY_WORKSTATION": ("apps.master_data.models.factory", "Workstation", "code"),
    "master-data-factory-workstation": ("apps.master_data.models.factory", "Workstation", "code"),
    "MASTER_DATA_WAREHOUSE_WAREHOUSE": ("apps.master_data.models.warehouse", "Warehouse", "code"),
    "master-data-warehouse-warehouse": ("apps.master_data.models.warehouse", "Warehouse", "code"),
    "MASTER_DATA_WAREHOUSE_STORAGE_AREA": ("apps.master_data.models.warehouse", "StorageArea", "code"),
    "master-data-warehouse-storage-area": ("apps.master_data.models.warehouse", "StorageArea", "code"),
    "MASTER_DATA_WAREHOUSE_STORAGE_LOCATION": ("apps.master_data.models.warehouse", "StorageLocation", "code"),
    "master-data-warehouse-storage-location": ("apps.master_data.models.warehouse", "StorageLocation", "code"),
    "MASTER_DATA_MATERIAL_GROUP": ("apps.master_data.models.material", "MaterialGroup", "code"),
    "master-data-material-group": ("apps.master_data.models.material", "MaterialGroup", "code"),
    "MATERIAL_CODE": ("apps.master_data.models.material", "Material", "main_code"),
    "master-data-material": ("apps.master_data.models.material", "Material", "main_code"),
    "master-data-supply-chain-customer": ("apps.master_data.models.customer", "Customer", "code"),
    "master-data-supply-chain-supplier": ("apps.master_data.models.supplier", "Supplier", "code"),
    "DEPARTMENT_CODE": ("core.models.department", "Department", "code"),
    "system-department": ("core.models.department", "Department", "code"),
    "POSITION_CODE": ("core.models.position", "Position", "code"),
    "system-position": ("core.models.position", "Position", "code"),
    "ROLE_CODE": ("core.models.role", "Role", "code"),
    "system-role": ("core.models.role", "Role", "code"),
    "EQUIPMENT_CODE": ("apps.kuaizhizao.models.equipment", "Equipment", "code"),
    "MOLD_CODE": ("apps.kuaizhizao.models.mold", "Mold", "code"),
    "TOOL_CODE": ("apps.kuaizhizao.models.tool", "Tool", "code"),
    "PURCHASE_ORDER_CHANGE_CODE": (
        "apps.kuaizhizao.models.purchase_order_change_order",
        "PurchaseOrderChangeOrder",
        "change_code",
    ),
    "SALES_ORDER_CHANGE_CODE": (
        "apps.kuaizhizao.models.sales_order_change_order",
        "SalesOrderChangeOrder",
        "change_code",
    ),
    "OQC_INSPECTION_CODE": ("apps.kuaizhizao.models.oqc_inspection", "OQCInspection", "inspection_code"),
    "EIGHT_D_REPORT_CODE": ("apps.kuaizhizao.models.quality_8d_report", "Quality8DReport", "report_code"),
    "DEFECT_RECORD_CODE": ("apps.kuaizhizao.models.defect_record", "DefectRecord", "code"),
    "SCRAP_RECORD_CODE": ("apps.kuaizhizao.models.scrap_record", "ScrapRecord", "code"),
    "MATERIAL_CALL_CODE": ("apps.kuaizhizao.models.material_call_request", "MaterialCallRequest", "code"),
    "WORK_CENTER_CODE": ("apps.master_data.models.factory", "WorkCenter", "code"),
    "HAOLIGO_MOLD_TRIAL_SHEET_NO": ("apps.haoligo.models.mold_trial_sheet", "HaoligoMoldTrialSheet", "sheet_no"),
    "HAOLIGO_MOLD_BORROW_SHEET_NO": ("apps.haoligo.models.mold_borrow_sheet", "HaoligoMoldBorrowSheet", "sheet_no"),
    "HAOLIGO_MOLD_RETURN_SHEET_NO": ("apps.haoligo.models.mold_return_sheet", "HaoligoMoldReturnSheet", "sheet_no"),
    "HAOLIGO_MOLD_MAINTENANCE_REPAIR_SHEET_NO": (
        "apps.haoligo.models.mold_maintenance_sheet",
        "HaoligoMoldMaintenanceSheet",
        "sheet_no",
    ),
    "HAOLIGO_MOLD_MAINTENANCE_UPKEEP_SHEET_NO": (
        "apps.haoligo.models.mold_maintenance_sheet",
        "HaoligoMoldMaintenanceSheet",
        "sheet_no",
    ),
    "HAOLIGO_MOLD_MAINTENANCE_COMPLETE_SHEET_NO": (
        "apps.haoligo.models.mold_maintenance_complete_sheet",
        "HaoligoMoldMaintenanceCompleteSheet",
        "sheet_no",
    ),
    "HAOLIGO_MOLD_OUTSOURCE_MAINTENANCE_SHEET_NO": (
        "apps.haoligo.models.mold_outsource_maintenance_sheet",
        "HaoligoMoldOutsourceMaintenanceSheet",
        "sheet_no",
    ),
    "HAOLIGO_MOLD_OUTSOURCE_MAINTENANCE_COMPLETE_SHEET_NO": (
        "apps.haoligo.models.mold_outsource_maintenance_complete_sheet",
        "HaoligoMoldOutsourceMaintenanceCompleteSheet",
        "sheet_no",
    ),
    "HAOLIGO_EQUIPMENT_SPOT_CHECK_NO": ("apps.haoligo.models.equipment_operations", "HaoligoEquipmentSpotCheck", "sheet_no"),
    "HAOLIGO_EQUIPMENT_ROUTE_PATROL_NO": ("apps.haoligo.models.equipment_operations", "HaoligoEquipmentRoutePatrol", "sheet_no"),
    "HAOLIGO_PATROL_HAZARD_REPORT_NO": ("apps.haoligo.models.patrol", "HaoligoHazardReport", "sheet_no"),
    "HAOLIGO_EQUIPMENT_UPKEEP_SHEET_NO": ("apps.haoligo.models.equipment_upkeep", "HaoligoEquipmentUpkeepSheet", "sheet_no"),
    "HAOLIGO_EQUIPMENT_MAINTENANCE_REPAIR_SHEET_NO": (
        "apps.haoligo.models.equipment_upkeep",
        "HaoligoEquipmentUpkeepSheet",
        "sheet_no",
    ),
    "HAOLIGO_EQUIPMENT_UPKEEP_COMPLETE_SHEET_NO": (
        "apps.haoligo.models.equipment_upkeep",
        "HaoligoEquipmentUpkeepCompleteSheet",
        "sheet_no",
    ),
    "HAOLIGO_EQUIPMENT_OUTPUT_RECORD_NO": ("apps.haoligo.models.equipment_operations", "HaoligoEquipmentOutputRecord", "sheet_no"),
    "HAOLIGO_EQUIPMENT_STATUS_ADJUSTMENT_NO": (
        "apps.haoligo.models.equipment_operations",
        "HaoligoEquipmentStatusAdjustment",
        "sheet_no",
    ),
    "HAOLIGO_EQUIPMENT_ACCEPTANCE_NO": (
        "apps.haoligo.models.equipment_acceptance",
        "HaoligoEquipmentAcceptanceSheet",
        "sheet_no",
    ),
    "HAOLIGO_FINANCE_MATERIAL_ACCEPTANCE_NO": (
        "apps.haoligo.models.finance_invoice",
        "HaoligoFinanceMaterialAcceptance",
        "sheet_no",
    ),
    "master-data-factory-work-center": ("apps.master_data.models.factory", "WorkCenter", "code"),
    "WORK_GROUP_CODE": ("apps.master_data.models.factory", "WorkGroup", "code"),
    "master-data-factory-work-group": ("apps.master_data.models.factory", "WorkGroup", "code"),
    "RECEIVABLE_CODE": ("apps.kuaicaiwu.models.receivable", "Receivable", "receivable_code"),
    "kuaicaiwu-finance-receivable": ("apps.kuaicaiwu.models.receivable", "Receivable", "receivable_code"),
    "PAYABLE_CODE": ("apps.kuaicaiwu.models.payable", "Payable", "payable_code"),
    "kuaicaiwu-finance-payable": ("apps.kuaicaiwu.models.payable", "Payable", "payable_code"),
    "PURCHASE_INVOICE_CODE": (
        "apps.kuaicaiwu.models.purchase_invoice",
        "PurchaseInvoice",
        "invoice_code",
    ),
    "kuaicaiwu-finance-purchase-invoice": (
        "apps.kuaicaiwu.models.purchase_invoice",
        "PurchaseInvoice",
        "invoice_code",
    ),
    "SALES_INVOICE_CODE": (
        "apps.kuaicaiwu.models.invoice",
        "Invoice",
        "invoice_code",
    ),
    "kuaicaiwu-finance-sales-invoice": (
        "apps.kuaicaiwu.models.invoice",
        "Invoice",
        "invoice_code",
    ),
    "SETTLEMENT_CODE": ("apps.kuaicaiwu.models.settlement", "Settlement", "settlement_code"),
    "kuaicaiwu-finance-settlement": ("apps.kuaicaiwu.models.settlement", "Settlement", "settlement_code"),
    "PARTNER_STATEMENT_CODE": (
        "apps.kuaicaiwu.models.partner_statement",
        "PartnerStatement",
        "statement_code",
    ),
    "kuaicaiwu-finance-partner-statement": (
        "apps.kuaicaiwu.models.partner_statement",
        "PartnerStatement",
        "statement_code",
    ),
    "COST_CALCULATION_CODE": (
        "apps.kuaicaiwu.models.cost_calculation",
        "CostCalculation",
        "calculation_no",
    ),
    "kuaicaiwu-cost-calculations": (
        "apps.kuaicaiwu.models.cost_calculation",
        "CostCalculation",
        "calculation_no",
    ),
    "COST_RULE_CODE": ("apps.kuaicaiwu.models.cost_rule", "CostRule", "code"),
    "kuaicaiwu-cost-rules": ("apps.kuaicaiwu.models.cost_rule", "CostRule", "code"),
    "SALES_ORDER_CODE": ("apps.kuaizhizao.models.sales_order", "SalesOrder", "order_code"),
    "kuaizhizao-sales-order": ("apps.kuaizhizao.models.sales_order", "SalesOrder", "order_code"),
    "RD_PROJECT_CODE": ("apps.kuaiplm.models.rd_project", "RdProject", "project_code"),
    "kuaiplm-rd-project": ("apps.kuaiplm.models.rd_project", "RdProject", "project_code"),
    "DELIVERY_PROJECT_CODE": ("apps.kuaiplm.models.rd_project", "RdProject", "project_code"),
    "kuaiplm-delivery-project": ("apps.kuaiplm.models.rd_project", "RdProject", "project_code"),
    "ALERT_RULE_CODE": (
        "apps.kuaizhizao.models.inventory_alert",
        "InventoryAlertRule",
        "code",
    ),
    "kuaizhizao-warehouse-inventory-alert": (
        "apps.kuaizhizao.models.inventory_alert",
        "InventoryAlertRule",
        "code",
    ),
}

