"""
自定义字段功能页面配置

定义系统中所有支持自定义字段的功能页面，用于在自定义字段管理页面展示和配置。
以本配置为唯一数据源，保证页面列表完整（不依赖各应用 manifest 的 custom_field_pages）。
"""

from typing import List, Dict, Any

# 页面配置数据结构
CustomFieldPageConfig = Dict[str, Any]

# 功能页面配置列表（主数据 + 快格轻制造）
CUSTOM_FIELD_PAGES: List[CustomFieldPageConfig] = [
    # ==================== 主数据管理 ====================
    # 工厂建模
    {
        "page_code": "master-data-factory-plant",
        "page_name": "厂区管理",
        "page_path": "/apps/master-data/factory/plants",
        "table_name": "master_data_factory_plants",
        "table_name_label": "厂区表",
        "module": "主数据管理",
        "module_icon": "database",
    },
    {
        "page_code": "master-data-factory-workshop",
        "page_name": "车间管理",
        "page_path": "/apps/master-data/factory/workshops",
        "table_name": "master_data_factory_workshops",
        "table_name_label": "车间表",
        "module": "主数据管理",
        "module_icon": "database",
    },
    {
        "page_code": "master-data-factory-production-line",
        "page_name": "产线管理",
        "page_path": "/apps/master-data/factory/production-lines",
        "table_name": "master_data_factory_production_lines",
        "table_name_label": "产线表",
        "module": "主数据管理",
        "module_icon": "database",
    },
    {
        "page_code": "master-data-factory-workstation",
        "page_name": "工位管理",
        "page_path": "/apps/master-data/factory/workstations",
        "table_name": "master_data_factory_workstations",
        "table_name_label": "工位表",
        "module": "主数据管理",
        "module_icon": "database",
    },
    {
        "page_code": "master-data-factory-work-center",
        "page_name": "工作中心",
        "page_path": "/apps/master-data/factory/work-centers",
        "table_name": "master_data_factory_work_centers",
        "table_name_label": "工作中心表",
        "module": "主数据管理",
        "module_icon": "database",
    },
    # 仓库管理
    {
        "page_code": "master-data-warehouse-warehouse",
        "page_name": "仓库管理",
        "page_path": "/apps/master-data/warehouse/warehouses",
        "table_name": "master_data_warehouse_warehouses",
        "table_name_label": "仓库表",
        "module": "主数据管理",
        "module_icon": "database",
    },
    {
        "page_code": "master-data-warehouse-storage-area",
        "page_name": "库区管理",
        "page_path": "/apps/master-data/warehouse/storage-areas",
        "table_name": "master_data_warehouse_storage_areas",
        "table_name_label": "库区表",
        "module": "主数据管理",
        "module_icon": "database",
    },
    {
        "page_code": "master-data-warehouse-storage-location",
        "page_name": "库位管理",
        "page_path": "/apps/master-data/warehouse/storage-locations",
        "table_name": "master_data_warehouse_storage_locations",
        "table_name_label": "库位表",
        "module": "主数据管理",
        "module_icon": "database",
    },
    # 物料管理
    {
        "page_code": "master-data-material-group",
        "page_name": "物料分组",
        "page_path": "/apps/master-data/materials",
        "table_name": "master_data_material_groups",
        "table_name_label": "物料分组表",
        "module": "主数据管理",
        "module_icon": "database",
    },
    {
        "page_code": "master-data-material",
        "page_name": "物料管理",
        "page_path": "/apps/master-data/materials",
        "table_name": "master_data_materials",
        "table_name_label": "物料表",
        "module": "主数据管理",
        "module_icon": "database",
    },
    {
        "page_code": "master-data-engineering-bom",
        "page_name": "物料清单BOM",
        "page_path": "/apps/master-data/process/engineering-bom",
        "table_name": "master_data_boms",
        "table_name_label": "物料清单BOM表",
        "module": "主数据管理",
        "module_icon": "database",
    },
    # 工艺管理
    {
        "page_code": "master-data-defect-type",
        "page_name": "缺陷类型管理",
        "page_path": "/apps/master-data/process/defect-types",
        "table_name": "master_data_defect_types",
        "table_name_label": "缺陷类型表",
        "module": "主数据管理",
        "module_icon": "database",
    },
    {
        "page_code": "master-data-operation",
        "page_name": "工序管理",
        "page_path": "/apps/master-data/process/operations",
        "table_name": "master_data_operations",
        "table_name_label": "工序表",
        "module": "主数据管理",
        "module_icon": "database",
    },
    {
        "page_code": "master-data-process-route",
        "page_name": "工艺路线管理",
        "page_path": "/apps/master-data/process/routes",
        "table_name": "master_data_process_routes",
        "table_name_label": "工艺路线表",
        "module": "主数据管理",
        "module_icon": "database",
    },
    {
        "page_code": "master-data-manufacturing-bom",
        "page_name": "标准操作SOP",
        "page_path": "/apps/master-data/process/sop",
        "table_name": "master_data_sops",
        "table_name_label": "标准操作SOP表",
        "module": "主数据管理",
        "module_icon": "database",
    },
    # 供应链
    {
        "page_code": "master-data-customer",
        "page_name": "客户管理",
        "page_path": "/apps/master-data/supply-chain/customers",
        "table_name": "master_data_customers",
        "table_name_label": "客户表",
        "module": "主数据管理",
        "module_icon": "database",
    },
    {
        "page_code": "master-data-supplier",
        "page_name": "供应商管理",
        "page_path": "/apps/master-data/supply-chain/suppliers",
        "table_name": "master_data_suppliers",
        "table_name_label": "供应商表",
        "module": "主数据管理",
        "module_icon": "database",
    },
    # 绩效管理
    {
        "page_code": "master-data-holiday",
        "page_name": "节假日管理",
        "page_path": "/apps/master-data/performance/holidays",
        "table_name": "master_data_holidays",
        "table_name_label": "节假日表",
        "module": "主数据管理",
        "module_icon": "database",
    },
    {
        "page_code": "master-data-skill",
        "page_name": "技能管理",
        "page_path": "/apps/master-data/performance/skills",
        "table_name": "master_data_skills",
        "table_name_label": "技能表",
        "module": "主数据管理",
        "module_icon": "database",
    },
    # ==================== 快格轻制造 ====================
    {
        "page_code": "kuaizhizao-production-work-order",
        "page_name": "工单管理",
        "page_path": "/apps/kuaizhizao/production-execution/work-orders",
        "table_name": "apps_kuaizhizao_work_orders",
        "table_name_label": "工单表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-production-rework-order",
        "page_name": "返工单",
        "page_path": "/apps/kuaizhizao/production-execution/rework-orders",
        "table_name": "apps_kuaizhizao_rework_orders",
        "table_name_label": "返工单表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-production-outsource-order",
        "page_name": "委外单",
        "page_path": "/apps/kuaizhizao/production-execution/outsource-orders",
        "table_name": "apps_kuaizhizao_outsource_orders",
        "table_name_label": "委外单表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-production-outsource-work-order",
        "page_name": "委外工单",
        "page_path": "/apps/kuaizhizao/production-execution/outsource-work-orders",
        "table_name": "apps_kuaizhizao_outsource_work_orders",
        "table_name_label": "委外工单表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-purchase-order",
        "page_name": "采购订单",
        "page_path": "/apps/kuaizhizao/purchase-management/purchase-orders",
        "table_name": "apps_kuaizhizao_purchase_orders",
        "table_name_label": "采购订单表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-purchase-receipt",
        "page_name": "采购收货",
        "page_path": "/apps/kuaizhizao/purchase-management/purchase-receipts",
        "table_name": "apps_kuaizhizao_purchase_receipts",
        "table_name_label": "采购收货表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-purchase-return",
        "page_name": "采购退货",
        "page_path": "/apps/kuaizhizao/purchase-management/purchase-returns",
        "table_name": "apps_kuaizhizao_purchase_returns",
        "table_name_label": "采购退货表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-sales-order",
        "page_name": "销售订单",
        "page_path": "/apps/kuaizhizao/sales-management/sales-orders",
        "table_name": "apps_kuaizhizao_sales_orders",
        "table_name_label": "销售订单表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-sample-trial",
        "page_name": "样品试用",
        "page_path": "/apps/kuaizhizao/sales-management/sample-trials",
        "table_name": "apps_kuaizhizao_sample_trials",
        "table_name_label": "样品试用单表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-sales-delivery",
        "page_name": "销售发货",
        "page_path": "/apps/kuaizhizao/sales-management/sales-deliveries",
        "table_name": "apps_kuaizhizao_sales_deliveries",
        "table_name_label": "销售发货表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-sales-return",
        "page_name": "销售退货",
        "page_path": "/apps/kuaizhizao/sales-management/sales-returns",
        "table_name": "apps_kuaizhizao_sales_returns",
        "table_name_label": "销售退货表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-warehouse-inbound",
        "page_name": "生产领料",
        "page_path": "/apps/kuaizhizao/warehouse-management/inbound",
        "table_name": "apps_kuaizhizao_production_pickings",
        "table_name_label": "生产领料表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-warehouse-production-return",
        "page_name": "生产退料",
        "page_path": "/apps/kuaizhizao/warehouse-management/inbound",
        "table_name": "apps_kuaizhizao_production_returns",
        "table_name_label": "生产退料表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-warehouse-other-inbound",
        "page_name": "其他入库",
        "page_path": "/apps/kuaizhizao/warehouse-management/other-inbound",
        "table_name": "apps_kuaizhizao_other_inbounds",
        "table_name_label": "其他入库表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-warehouse-other-outbound",
        "page_name": "其他出库",
        "page_path": "/apps/kuaizhizao/warehouse-management/other-outbound",
        "table_name": "apps_kuaizhizao_other_outbounds",
        "table_name_label": "其他出库表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-warehouse-finished-goods-inbound",
        "page_name": "成品入库",
        "page_path": "/apps/kuaizhizao/warehouse-management/inbound",
        "table_name": "apps_kuaizhizao_finished_goods_receipts",
        "table_name_label": "成品入库表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-quality-incoming-inspection",
        "page_name": "来料检验",
        "page_path": "/apps/kuaizhizao/quality-management/incoming-inspection",
        "table_name": "apps_kuaizhizao_incoming_inspections",
        "table_name_label": "来料检验表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-quality-process-inspection",
        "page_name": "过程检验",
        "page_path": "/apps/kuaizhizao/quality-management/process-inspection",
        "table_name": "apps_kuaizhizao_process_inspections",
        "table_name_label": "过程检验表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-quality-finished-goods-inspection",
        "page_name": "成品检验",
        "page_path": "/apps/kuaizhizao/quality-management/finished-goods-inspection",
        "table_name": "apps_kuaizhizao_finished_goods_inspections",
        "table_name_label": "成品检验表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-plan-production-plan",
        "page_name": "生产计划",
        "page_path": "/apps/kuaizhizao/plan-management/production-plans",
        "table_name": "apps_kuaizhizao_production_plans",
        "table_name_label": "生产计划表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-equipment",
        "page_name": "设备台账",
        "page_path": "/apps/kuaizhizao/equipment-management/equipment",
        "table_name": "apps_kuaizhizao_equipment",
        "table_name_label": "设备表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-mold",
        "page_name": "模具台账",
        "page_path": "/apps/kuaizhizao/equipment-management/molds",
        "table_name": "apps_kuaizhizao_molds",
        "table_name_label": "模具表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
]
