"""
自定义字段功能页面配置

定义系统中所有支持自定义字段的功能页面，用于在自定义字段管理页面展示和配置。
以本配置为唯一数据源，保证页面列表完整（不依赖各应用 manifest 的 custom_field_pages）。
"""

from typing import List, Dict, Any

# 页面配置数据结构
CustomFieldPageConfig = Dict[str, Any]

# 功能页面配置列表（主数据 + 快格轻制造）
CUSTOM_FIELD_PAGES: List[CustomFieldPageConfig] = [
    # ==================== 主数据管理 ====================
    # 工厂建模
    {
        "page_code": "master-data-factory-plant",
        "page_name": "厂区管理",
        "page_path": "/apps/master-data/factory/plants",
        "table_name": "master_data_factory_plants",
        "table_name_label": "厂区表",
        "module": "主数据管理",
        "module_icon": "database",
    },
    {
        "page_code": "master-data-factory-workshop",
        "page_name": "车间管理",
        "page_path": "/apps/master-data/factory/workshops",
        "table_name": "master_data_factory_workshops",
        "table_name_label": "车间表",
        "module": "主数据管理",
        "module_icon": "database",
    },
    {
        "page_code": "master-data-factory-production-line",
        "page_name": "产线管理",
        "page_path": "/apps/master-data/factory/production-lines",
        "table_name": "master_data_factory_production_lines",
        "table_name_label": "产线表",
        "module": "主数据管理",
        "module_icon": "database",
    },
    {
        "page_code": "master-data-factory-workstation",
        "page_name": "工位管理",
        "page_path": "/apps/master-data/factory/workstations",
        "table_name": "master_data_factory_workstations",
        "table_name_label": "工位表",
        "module": "主数据管理",
        "module_icon": "database",
    },
    {
        "page_code": "master-data-factory-work-center",
        "page_name": "工作中心",
        "page_path": "/apps/master-data/factory/work-centers",
        "table_name": "master_data_factory_work_centers",
        "table_name_label": "工作中心表",
        "module": "主数据管理",
        "module_icon": "database",
    },
    # 仓库管理
    {
        "page_code": "master-data-warehouse-warehouse",
        "page_name": "仓库管理",
        "page_path": "/apps/master-data/warehouse/warehouses",
        "table_name": "master_data_warehouse_warehouses",
        "table_name_label": "仓库表",
        "module": "主数据管理",
        "module_icon": "database",
    },
    {
        "page_code": "master-data-warehouse-storage-area",
        "page_name": "库区管理",
        "page_path": "/apps/master-data/warehouse/storage-areas",
        "table_name": "master_data_warehouse_storage_areas",
        "table_name_label": "库区表",
        "module": "主数据管理",
        "module_icon": "database",
    },
    {
        "page_code": "master-data-warehouse-storage-location",
        "page_name": "库位管理",
        "page_path": "/apps/master-data/warehouse/storage-locations",
        "table_name": "master_data_warehouse_storage_locations",
        "table_name_label": "库位表",
        "module": "主数据管理",
        "module_icon": "database",
    },
    # 物料管理
    {
        "page_code": "master-data-material-group",
        "page_name": "物料分组",
        "page_path": "/apps/master-data/materials",
        "table_name": "master_data_material_groups",
        "table_name_label": "物料分组表",
        "module": "主数据管理",
        "module_icon": "database",
    },
    {
        "page_code": "master-data-material",
        "page_name": "物料管理",
        "page_path": "/apps/master-data/materials",
        "table_name": "master_data_materials",
        "table_name_label": "物料表",
        "module": "主数据管理",
        "module_icon": "database",
    },
    {
        "page_code": "master-data-engineering-bom",
        "page_name": "物料清单BOM",
        "page_path": "/apps/master-data/process/engineering-bom",
        "table_name": "master_data_boms",
        "table_name_label": "物料清单BOM表",
        "module": "主数据管理",
        "module_icon": "database",
    },
    # 工艺管理
    {
        "page_code": "master-data-defect-type",
        "page_name": "缺陷类型管理",
        "page_path": "/apps/master-data/process/defect-types",
        "table_name": "master_data_defect_types",
        "table_name_label": "缺陷类型表",
        "module": "主数据管理",
        "module_icon": "database",
    },
    {
        "page_code": "master-data-operation",
        "page_name": "工序管理",
        "page_path": "/apps/master-data/process/operations",
        "table_name": "master_data_operations",
        "table_name_label": "工序表",
        "module": "主数据管理",
        "module_icon": "database",
    },
    {
        "page_code": "master-data-process-route",
        "page_name": "工艺路线管理",
        "page_path": "/apps/master-data/process/routes",
        "table_name": "master_data_process_routes",
        "table_name_label": "工艺路线表",
        "module": "主数据管理",
        "module_icon": "database",
    },
    {
        "page_code": "master-data-process-drawing",
        "page_name": "图纸管理",
        "page_path": "/apps/master-data/process/drawings",
        "table_name": "apps_master_data_engineering_drawings",
        "table_name_label": "工程图纸表",
        "module": "主数据管理",
        "module_icon": "database",
    },
    {
        "page_code": "master-data-manufacturing-bom",
        "page_name": "标准操作SOP",
        "page_path": "/apps/master-data/process/sop",
        "table_name": "master_data_sops",
        "table_name_label": "标准操作SOP表",
        "module": "主数据管理",
        "module_icon": "database",
    },
    # 供应链
    {
        "page_code": "master-data-customer",
        "page_name": "客户管理",
        "page_path": "/apps/master-data/supply-chain/customers",
        "table_name": "master_data_customers",
        "table_name_label": "客户表",
        "module": "主数据管理",
        "module_icon": "database",
    },
    {
        "page_code": "master-data-supplier",
        "page_name": "供应商管理",
        "page_path": "/apps/master-data/supply-chain/suppliers",
        "table_name": "master_data_suppliers",
        "table_name_label": "供应商表",
        "module": "主数据管理",
        "module_icon": "database",
    },
    # 绩效管理
    {
        "page_code": "master-data-holiday",
        "page_name": "节假日管理",
        "page_path": "/apps/master-data/performance/holidays",
        "table_name": "master_data_holidays",
        "table_name_label": "节假日表",
        "module": "主数据管理",
        "module_icon": "database",
    },
    {
        "page_code": "master-data-skill",
        "page_name": "技能管理",
        "page_path": "/apps/master-data/performance/skills",
        "table_name": "master_data_skills",
        "table_name_label": "技能表",
        "module": "主数据管理",
        "module_icon": "database",
    },
    # ==================== 快格轻制造 ====================
    # 销售管理
    {
        "page_code": "kuaizhizao-quotation",
        "page_name": "报价单",
        "page_path": "/apps/kuaizhizao/sales-management/quotations",
        "table_name": "apps_kuaizhizao_quotations",
        "table_name_label": "报价单表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-customer-follow-up",
        "page_name": "客户跟进",
        "page_path": "/apps/kuaizhizao/sales-management/customer-follow-ups",
        "table_name": "apps_kuaizhizao_customer_follow_ups",
        "table_name_label": "客户跟进表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-sales-contract",
        "page_name": "销售合同",
        "page_path": "/apps/kuaizhizao/sales-management/sales-contracts",
        "table_name": "apps_kuaizhizao_sales_contracts",
        "table_name_label": "销售合同表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-sales-contract-change",
        "page_name": "销售合同变更",
        "page_path": "/apps/kuaizhizao/sales-management/sales-contracts",
        "table_name": "apps_kuaizhizao_sales_contract_changes",
        "table_name_label": "销售合同变更表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-sales-forecast",
        "page_name": "销售预测",
        "page_path": "/apps/kuaizhizao/sales-management/sales-forecasts",
        "table_name": "apps_kuaizhizao_sales_forecasts",
        "table_name_label": "销售预测表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-sales-order",
        "page_name": "销售订单",
        "page_path": "/apps/kuaizhizao/sales-management/sales-orders",
        "table_name": "apps_kuaizhizao_sales_orders",
        "table_name_label": "销售订单表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-sales-order-change",
        "page_name": "销售变更单",
        "page_path": "/apps/kuaizhizao/sales-management/sales-order-changes",
        "table_name": "apps_kuaizhizao_sales_order_change_orders",
        "table_name_label": "销售变更单表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-shipment-notice",
        "page_name": "发货通知单",
        "page_path": "/apps/kuaizhizao/sales-management/shipment-notices",
        "table_name": "apps_kuaizhizao_shipment_notices",
        "table_name_label": "发货通知单表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-sales-return",
        "page_name": "销售退货",
        "page_path": "/apps/kuaizhizao/sales-management/sales-returns",
        "table_name": "apps_kuaizhizao_sales_returns",
        "table_name_label": "销售退货表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    # 计划管理
    {
        "page_code": "kuaizhizao-demand-plan",
        "page_name": "需求计划",
        "page_path": "/apps/kuaizhizao/plan-management/demand-management",
        "table_name": "apps_kuaizhizao_demands",
        "table_name_label": "需求计划表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    # 采购管理
    {
        "page_code": "kuaizhizao-purchase-requisition",
        "page_name": "采购申请",
        "page_path": "/apps/kuaizhizao/purchase-management/purchase-requisitions",
        "table_name": "apps_kuaizhizao_purchase_requisitions",
        "table_name_label": "采购申请表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-purchase-inquiry",
        "page_name": "采购询价单",
        "page_path": "/apps/kuaizhizao/purchase-management/purchase-inquiries",
        "table_name": "apps_kuaizhizao_purchase_inquiries",
        "table_name_label": "采购询价单表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-purchase-order",
        "page_name": "采购订单",
        "page_path": "/apps/kuaizhizao/purchase-management/purchase-orders",
        "table_name": "apps_kuaizhizao_purchase_orders",
        "table_name_label": "采购订单表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-purchase-order-change",
        "page_name": "采购变更单",
        "page_path": "/apps/kuaizhizao/purchase-management/purchase-order-changes",
        "table_name": "apps_kuaizhizao_purchase_order_change_orders",
        "table_name_label": "采购变更单表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-receipt-notice",
        "page_name": "收货通知单",
        "page_path": "/apps/kuaizhizao/purchase-management/receipt-notices",
        "table_name": "apps_kuaizhizao_receipt_notices",
        "table_name_label": "收货通知单表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-purchase-return",
        "page_name": "采购退货",
        "page_path": "/apps/kuaizhizao/purchase-management/purchase-returns",
        "table_name": "apps_kuaizhizao_purchase_returns",
        "table_name_label": "采购退货表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    # 生产执行
    {
        "page_code": "kuaizhizao-production-work-order",
        "page_name": "工单管理",
        "page_path": "/apps/kuaizhizao/production-execution/work-orders",
        "table_name": "apps_kuaizhizao_work_orders",
        "table_name_label": "工单表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-production-reporting",
        "page_name": "报工管理",
        "page_path": "/apps/kuaizhizao/production-execution/reporting",
        "table_name": "apps_kuaizhizao_reporting_records",
        "table_name_label": "报工记录表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-production-rework-order",
        "page_name": "返工单",
        "page_path": "/apps/kuaizhizao/production-execution/rework-orders",
        "table_name": "apps_kuaizhizao_rework_orders",
        "table_name_label": "返工单表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-production-outsource-order",
        "page_name": "委外单",
        "page_path": "/apps/kuaizhizao/production-execution/outsource-management",
        "table_name": "apps_kuaizhizao_outsource_orders",
        "table_name_label": "委外单表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-production-outsource-work-order",
        "page_name": "委外工单",
        "page_path": "/apps/kuaizhizao/production-execution/outsource-management",
        "table_name": "apps_kuaizhizao_outsource_work_orders",
        "table_name_label": "委外工单表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-production-packing-binding",
        "page_name": "装箱绑定",
        "page_path": "/apps/kuaizhizao/production-execution/packing-binding",
        "table_name": "apps_kuaizhizao_packing_bindings",
        "table_name_label": "装箱绑定表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    # 质量管理
    {
        "page_code": "kuaizhizao-quality-incoming-inspection",
        "page_name": "来料检验",
        "page_path": "/apps/kuaizhizao/quality-management/incoming-inspection",
        "table_name": "apps_kuaizhizao_incoming_inspections",
        "table_name_label": "来料检验表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-quality-process-inspection",
        "page_name": "过程检验",
        "page_path": "/apps/kuaizhizao/quality-management/process-inspection",
        "table_name": "apps_kuaizhizao_process_inspections",
        "table_name_label": "过程检验表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-quality-finished-goods-inspection",
        "page_name": "成品检验",
        "page_path": "/apps/kuaizhizao/quality-management/finished-goods-inspection",
        "table_name": "apps_kuaizhizao_finished_goods_inspections",
        "table_name_label": "成品检验表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-quality-inspection-plan",
        "page_name": "质检方案",
        "page_path": "/apps/kuaizhizao/quality-management/inspection-plans",
        "table_name": "apps_kuaizhizao_inspection_plans",
        "table_name_label": "质检方案表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-quality-eight-d-report",
        "page_name": "8D报告",
        "page_path": "/apps/kuaizhizao/quality-management/eight-d-reports",
        "table_name": "apps_kuaizhizao_quality_8d_reports",
        "table_name_label": "8D报告表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-quality-system-document",
        "page_name": "体系文件",
        "page_path": "/apps/kuaizhizao/quality-management/system-documents",
        "table_name": "apps_kuaizhizao_qms_system_documents",
        "table_name_label": "体系文件表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-quality-internal-audit",
        "page_name": "内部审核",
        "page_path": "/apps/kuaizhizao/quality-management/internal-audits",
        "table_name": "apps_kuaizhizao_qms_internal_audits",
        "table_name_label": "内部审核表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-quality-management-review",
        "page_name": "管理评审",
        "page_path": "/apps/kuaizhizao/quality-management/management-reviews",
        "table_name": "apps_kuaizhizao_qms_management_reviews",
        "table_name_label": "管理评审表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-quality-fai-order",
        "page_name": "FAI首件检验",
        "page_path": "/apps/kuaizhizao/quality-management/fai-orders",
        "table_name": "apps_kuaizhizao_fai_orders",
        "table_name_label": "FAI首件检验表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-quality-oqc-inspection",
        "page_name": "出货检验",
        "page_path": "/apps/kuaizhizao/quality-management/oqc-inspection",
        "table_name": "apps_kuaizhizao_oqc_inspections",
        "table_name_label": "出货检验表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    # 设备 / 模具 / 工装台账
    {
        "page_code": "kuaizhizao-equipment",
        "page_name": "设备台账",
        "page_path": "/apps/kuaizhizao/equipment-management/equipment",
        "table_name": "apps_kuaizhizao_equipment",
        "table_name_label": "设备表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-mold",
        "page_name": "模具台账",
        "page_path": "/apps/kuaizhizao/equipment-management/molds",
        "table_name": "apps_kuaizhizao_molds",
        "table_name_label": "模具表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-tool",
        "page_name": "工装台账",
        "page_path": "/apps/kuaizhizao/equipment-management/tool-ledger",
        "table_name": "apps_kuaizhizao_tools",
        "table_name_label": "工装表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    # 仓储管理
    {
        "page_code": "kuaizhizao-warehouse-batching-order",
        "page_name": "配料单",
        "page_path": "/apps/kuaizhizao/warehouse-management/batching-center",
        "table_name": "apps_kuaizhizao_batching_orders",
        "table_name_label": "配料单表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-purchase-receipt",
        "page_name": "采购入库",
        "page_path": "/apps/kuaizhizao/warehouse-management/inbound",
        "table_name": "apps_kuaizhizao_purchase_receipts",
        "table_name_label": "采购收货表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-warehouse-inbound",
        "page_name": "生产领料",
        "page_path": "/apps/kuaizhizao/warehouse-management/inbound",
        "table_name": "apps_kuaizhizao_production_pickings",
        "table_name_label": "生产领料表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-warehouse-production-return",
        "page_name": "生产退料",
        "page_path": "/apps/kuaizhizao/warehouse-management/inbound",
        "table_name": "apps_kuaizhizao_production_returns",
        "table_name_label": "生产退料表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-warehouse-finished-goods-inbound",
        "page_name": "成品入库",
        "page_path": "/apps/kuaizhizao/warehouse-management/inbound",
        "table_name": "apps_kuaizhizao_finished_goods_receipts",
        "table_name_label": "成品入库表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-warehouse-semi-finished-inbound",
        "page_name": "半成品入库",
        "page_path": "/apps/kuaizhizao/warehouse-management/inbound",
        "table_name": "apps_kuaizhizao_semi_finished_goods_receipts",
        "table_name_label": "半成品入库表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-warehouse-other-inbound",
        "page_name": "其他入库",
        "page_path": "/apps/kuaizhizao/warehouse-management/other-inbound",
        "table_name": "apps_kuaizhizao_other_inbounds",
        "table_name_label": "其他入库表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-warehouse-customer-material-registration",
        "page_name": "代工来料",
        "page_path": "/apps/kuaizhizao/warehouse-management/customer-material-registration",
        "table_name": "apps_kuaizhizao_customer_material_registrations",
        "table_name_label": "代工来料表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-sales-delivery",
        "page_name": "销售发货",
        "page_path": "/apps/kuaizhizao/warehouse-management/outbound",
        "table_name": "apps_kuaizhizao_sales_deliveries",
        "table_name_label": "销售发货表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-warehouse-other-outbound",
        "page_name": "其他出库",
        "page_path": "/apps/kuaizhizao/warehouse-management/other-outbound",
        "table_name": "apps_kuaizhizao_other_outbounds",
        "table_name_label": "其他出库表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-warehouse-material-borrow",
        "page_name": "借料单",
        "page_path": "/apps/kuaizhizao/warehouse-management/material-borrows",
        "table_name": "apps_kuaizhizao_material_borrows",
        "table_name_label": "借料单表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-warehouse-material-return",
        "page_name": "还料单",
        "page_path": "/apps/kuaizhizao/warehouse-management/material-returns",
        "table_name": "apps_kuaizhizao_material_returns",
        "table_name_label": "还料单表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-delivery-notice",
        "page_name": "送货单",
        "page_path": "/apps/kuaizhizao/warehouse-management/delivery-notes",
        "table_name": "apps_kuaizhizao_delivery_notices",
        "table_name_label": "送货单表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-warehouse-material-call",
        "page_name": "产线叫料",
        "page_path": "/apps/kuaizhizao/warehouse-management/material-calls",
        "table_name": "apps_kuaizhizao_material_call_requests",
        "table_name_label": "产线叫料表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-warehouse-stocktaking",
        "page_name": "盘点单",
        "page_path": "/apps/kuaizhizao/warehouse-management/stocktaking",
        "table_name": "apps_kuaizhizao_stocktakings",
        "table_name_label": "盘点单表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-warehouse-inventory-transfer",
        "page_name": "调拨单",
        "page_path": "/apps/kuaizhizao/warehouse-management/inventory-transfer",
        "table_name": "apps_kuaizhizao_inventory_transfers",
        "table_name_label": "调拨单表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-warehouse-assembly-order",
        "page_name": "组装单",
        "page_path": "/apps/kuaizhizao/warehouse-management/assembly-orders",
        "table_name": "apps_kuaizhizao_assembly_orders",
        "table_name_label": "组装单表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
    {
        "page_code": "kuaizhizao-warehouse-disassembly-order",
        "page_name": "拆卸单",
        "page_path": "/apps/kuaizhizao/warehouse-management/disassembly-orders",
        "table_name": "apps_kuaizhizao_disassembly_orders",
        "table_name_label": "拆卸单表",
        "module": "快格轻制造",
        "module_icon": "tool",
    },
]
