"""Tortoise ORM 模块注册（运行时按应用中心启用状态加载）。"""

ORM_MODEL_MODULES: list[str] = [
    "apps.kuaicaiwu.models.account_balance",
    "apps.kuaicaiwu.models.accounting_event",
    "apps.kuaicaiwu.models.accounting_period",
    "apps.kuaicaiwu.models.bank_account",
    "apps.kuaicaiwu.models.bank_reconcile_item",
    "apps.kuaicaiwu.models.bank_transaction",
    "apps.kuaicaiwu.models.chart_of_account",
    "apps.kuaicaiwu.models.cost_calculation",
    "apps.kuaicaiwu.models.cost_rule",
    "apps.kuaicaiwu.models.finance_note",
    "apps.kuaicaiwu.models.gl_accrual_item",
    "apps.kuaicaiwu.models.gl_book_settings",
    "apps.kuaicaiwu.models.gl_cash_flow_item",
    "apps.kuaicaiwu.models.gl_cheque",
    "apps.kuaicaiwu.models.gl_project",
    "apps.kuaicaiwu.models.gl_tax_settings",
    "apps.kuaicaiwu.models.gl_transfer_template",
    "apps.kuaicaiwu.models.invoice",
    "apps.kuaicaiwu.models.partner_statement",
    "apps.kuaicaiwu.models.payable",
    "apps.kuaicaiwu.models.payment",
    "apps.kuaicaiwu.models.price_settlement_batch",
    "apps.kuaicaiwu.models.price_settlement_line",
    "apps.kuaicaiwu.models.purchase_invoice",
    "apps.kuaicaiwu.models.receipt",
    "apps.kuaicaiwu.models.receivable",
    "apps.kuaicaiwu.models.settlement",
    "apps.kuaicaiwu.models.standard_cost",
    "apps.kuaicaiwu.models.tax_period_record",
    "apps.kuaicaiwu.models.voucher",
    "apps.kuaicaiwu.models.voucher_line",
    "apps.kuaicaiwu.models.voucher_summary",
]
